### ISSUE TITLE
EVENTS: Kurspreise Datenmodell

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1002]
Als Kursadmin möchte ich für verschiedene Preiskategorien auf einem Kurs die Preise konfigurieren können.

## Model
Neu sollen folgende Attribute auf dem Kurs hinzgefügt werden (alle decimal precision: 8, scale: 2)
- price_member / Mitgliederpreis
- price_regular / Normalpreis
- price_subsidized / Subventionierter Preis
- price_js_active_member / J&S A-Mitgliederpreis
- price_js_active_regular / J&S A-Normalpreis
- price_js_passive_member / J&S P-Mitgliederpreis
- price_js_passive_regular / J&S P-Normalpreis

Auf der Teilnahme werden zwei neue Attribute hinzugefügt:
- price (decimal precision: 8,  scale: 2, nullable)
- price_category (integer, enum, nullable, mit allen Werten der Kurspreise (member, regular, subsidized, js_active_member, ...)

Sobal der Kurs im Status "Publiziert" ist, sollen die beiden Preise "Mitgliederpreis" und "Normalpreis" Pflichtfelder sein (gleich wie div. andere Felder).

In diesem Issue wird bewusst nur das Datenmodell erstellt, damit alle abhängigen Issues danach möglichst bald und parallel bearbeitet werden können. Bearbeiten, Anzeigen usw erfolgt also in separaten Issues. 

# ToDo

- [x] Migration erstellen
- [x] Model anpassen
- [x] Specs schreiben

**Comment by tobiasstern** [comment]
Datenmodell für mich nicht testbar, wird mit den anderen Tickets getestet wie z.b. #1005

**Comment by tobiasstern** [comment]
Preise funktionieren gut 👍  Noch besser wäre, wenn man keine negativen Preise eingeben könnte, aber das ist vernachlässigbar da UI nur von Admins verwendet wird und kein Missbrauchsrisiko besteht.
