### ISSUE TITLE
EVENTS: Preis bei Kursanmeldung anzeigen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1003]
Als Kurs-Teilnehmer*in will ich bei der Anmeldung den für mich relevanten Preis sehen.

Neu sollen im Kurs-Anmeldewizard bei der Kostenübersicht auf der rechten Seite die korrekten Preise angezeigt werden. Ein aktives SAC-Mitglied (`person.sac_membership_active?`) sieht dabei den Preis `price_member`, alle anderen Personen den Preis `price_regular`. 

Der Schritt "Subventionierung" soll nur angezeigt werden, falls die Person ein aktives SAC Mitglied ist und falls für den Kurs der `price_subsidized` nicht leer ist. Falls der User die Checkbox "Subventionierten Preis beantragen" auswählt, werden in der Kostenübersicht die folgenden Zeilen angezeigt:
- Kurskosten: CHF {price_member}
- -Subvention: CHF {price_member - price_subsidized}
- Total: CHF {price_subsidized}

Beim Abschluss des Wizards soll der gewählte Preis und die Preiskategorie auf der Teilnahme gespeichert werden.

# ToDo

- [x] View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Das klappt noch nicht ganz. Obwohl auf dem Kurs https://sac-cas.puzzle.ch/de/groups/1/events/65 kein subventionierter Preis angegeben ist, wir mir im Wizard der Schritt für die Subventionierung angezeigt. Bitte korrigieren.

**Comment by njaeggi** [comment]
@tobiasstern 

Bug ist gefixt und kann auf Integration getestet werden 🚀

**Comment by tobiasstern** [comment]
Passt 👍
