### ISSUE TITLE
EVENTS: Preis Platzhalter bei E-Mail Kursanmeldung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1004]
Neu soll bei den folgenden E-Mail Vorlagen ein zusätzlicher, optionaler Platzhalter `participation-price` verfügbar sein:

- Kurs: E-Mail Bestätigte Kursanmeldung
- Kurs: E-Mail Unbestätigte Kursanmeldung
- Kurs: E-Mail Unbestätigte Warteliste

Der Platzhalter wird auf den `price` der Teilnahme aufgelöst, welcher im Format "0.00" dargestellt wird.

# ToDo

- [x] Mailer anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Soweit meinen Tests werden diese E-Mails bei Anmeldung nicht mehr verschickt. Da scheint es ein Problem zu geben. Ev. durch das neue Datenmodell im Kurs mit den Preisen? Ich teste später nochmal.

**Comment by tobiasstern** [comment]
Hey @hunchr ich habs nochmal bestätigt, aktuell werden keine der drei E-Mails ausgelöst bei Anmeldung, es kommt nichts an. Der neue Platzhalter für den Preis habe ich aus der E-Mail-Vorlage entfernt mit gleichem Ergebnis. Kann es sein, das der Change hier das verursacht?

**Comment by hunchr** [comment]
danke für die info @tobiasstern, ich werde es mir anschauen

**Comment by hunchr** [comment]
gefixt, beim nächsten deploy sollte es gehen

**Comment by Largo** [comment]
@hunchr Koennen wir solche Faelle auch mit specs abfangen? Vielleicht beim naechsten mailer ticket?

**Comment by hunchr** [comment]
ja habe noch einen spec dazu geschrieben

**Comment by tobiasstern** [comment]
Mails gehen wieder 👍  Ich warte mit dem weiteren Testen dieser Story hier, bis Kursanmeldungen Preise haben können siehe #1006

**Comment by tobiasstern** [comment]
Preise werden korrekt verwendet in den Mails 👍
