### ISSUE TITLE
EVENTS: Kursrechnung an Abacus übermitteln

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1008]
blocked by #1002 

In diesem Ticket wird die technische Grundlage gelegt, um Kursrechnungen an Abacus zu schicken.

## Course Invoice

Analog zur MembershipInvoice braucht es eine Klasse `Invoices::Abacus::CourseInvoice`, welche eine Kursrechnung für Abacus vorbereitet.

Zur Initialisierung der Klasse wird eine Event::Participation eines Kurses übergeben. 

Eine Kursrechnung hat immer nur eine Position (`Invoices::Abacus::InvoicePosition`):
- name: "{participation.price_category} - {participation.event.kind.level}" (entsprechend mit I18n)
- grouping: gleich wie name
- amount: `participation.price`
- count: 1
- article_number: `Group.root.sac_membership_configs.active(participation.event.dates.order(:start_at).first.start_at).course_fee_article_number`
- cost_center: `participation.event.kind.cost_center.code`
- cost_unit: `participation.event.kind.cost_unit.code`

Als `additional_user_fields` werden folgende Felder gesetzt:
- user_field8: Kursnummer
- user_field9: Kursname
- user_field10: Kursdaten, falls mehrere kommasepariert, ohne Wochentag und Zeit. z.B. "16.05.2024 - 29.05.2024"

Die Methode `invoice?` gibt false zurück, falls der Betrag der Position null ist.

## CreateCourseInvoiceJob

Der bestehende `Invoices::Abacus::CreateInvoiceJob` erhält zwei neue Subklassen: `CreateMembershipInvoiceJob` und `CreateCourseInvoiceJob`. Die neue Basisklasse nimmt im `initialize` nur noch das Argument `external_invoice` und erhält eine leere Template Methode `invoice_data`, welche überall anstelle von `membership_invoice` aufgerufen wird. In `CreateMembershipInvoiceJob` entspricht die Implementation von `invoice_data` der jetztigen `membership_invoice` Methode. Die `assign_error` Methode wird in der Basisklasse ebenfalls vereinfacht, eine Methode `invoice_error_key` extrahiert, welche in `CreateMembershipInvoiceJob` mit der jetzigen Implementation überschrieben wird. Bisherige Verwendungen von CreateInvoiceJob müssen auf CreateMembershipInvoiceJob umgestellt werden.

Der neue `CreateCourseInvoiceJob` erstellt in `invoice_data` eine Instanz von `Invoices::Abacus::CourseInvoice` mit der Teilnahme aus dem `external_invoice.link`. Der restliche Ablauf bleibt identisch.

## ExternalInvoice::Course

Auf der Klasse `ExternalInvoice::Course` wird eine klassenseitige Methode `invoice_participation(participation)` erstellt, welche folgendes macht:

- Neue Instanz erzeugen mit den folgenden Attributen:
  - person: participation.person
  - issued_at: Date.current
  - sent_at: Date.current
  - state: :draft
  - total: participation.price
  - link: participation
  - year: participation.event.dates.order(:started_at).first.started_at.year
-  `Invoices::Abacus::CreateCourseInvoiceJob` enqueuen mit der neu erstellten External Invoice

Falls der Preis auf der Participation leer ist, wird keine External Invoice erzeugt und auch kein Job enqueued.

# ToDo

- [x] Domainklasse erstellen oder anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Etwas was glaube ich bei meiner Besprechung mit Pascal vergessen ging ist der Anzeige-Titel in der Rechnungsübersicht. Dort werden ja aktuell die Mitgliedschaftsrechnungen so angezeigt (vgl. Bild):
![image](https://github.com/user-attachments/assets/8eeaa37f-d93e-4548-8c49-fa416154c4ad)

Hat Pascal in diesem Ticket hier spezifiziert, wie der Titel sein soll für Kursrechnungen?

Falls nicht bitte wie folgt umsetzen:
Titel: {Kursname} ({Kursnummer})
Beispiel: "Lawinen Ski + Snowboard (2025-0524)"

**Comment by Largo** [comment]
Der Button zum Rechnung anlegen taucht teilweise bei mir lokal nicht auf... Das hängt aber nicht direkt mit diesem Ticket zusammen. Sollten wir beobachten. Bitte auf der INT nochmals testen ob der Titel stimmt. Ebenfalls ob man eine Rechnung stornieren darf und dann mit dem Knopf nochmals anlegen.

**Comment by tobiasstern** [comment]
Hey @Largo 

Ich habe auf drei Anmeldungen den Button geklickt und die Bestätigung erhalten, aber ich sehe keine erzeugte Rechnung. Es ist schon so, dass die Rechnung dann in den Rechnungen auf dem Userprofile erscheinen sollte, oder?

**Comment by Largo** [comment]
@njaeggi kannst du nochmals schauen und dem nachgehen?

**Comment by njaeggi** [comment]
https://github.com/hitobito/hitobito_sac_cas/pull/1116 @Largo ist ein kleiner Fix, dummer Fehler 😅 wäre cool wenn du das mergen könntest

**Comment by Largo** [comment]
@tobiasstern @njaeggi gemergt!

**Comment by tobiasstern** [comment]
Der Auftrag wird erzeugt, aber dann gibt es wohl noch ein Problem. Die Rechnungen bleiben im Status Entwurf und das Log füllt sich mit Fehlermeldungen. Vgl, Thread im Chat: https://chat.puzzle.ch/channel/hitobito-office?msg=kXpoGEfdER999qtEp Ich erstelle ein bug-ticket dazu.

**Comment by tobiasstern** [comment]
Ich muss auch testen, ob die erstellten Rechnungen wieder storniert werden können und wie sich die Rechnugnserzeugung danach verhält. Daher bleibt dieses Ticket solange offen =/

**Comment by tobiasstern** [comment]
Das 401 Unauthorized konnte behoben werden, indem die Abacus Credentials auf Int korrigiert wurden. 

Nun werden aber andere Fehler geworfen und die Auftragserstellung ist fehlerhaft, siehe Bilder:

![Image](https://github.com/user-attachments/assets/cb60c898-4003-4176-a647-6efc6200d352)
![Image](https://github.com/user-attachments/assets/a367766a-80a9-4534-9b6c-348ce3eda47c)

Könnt ihr dies bitte beheben?

**Comment by codez** [comment]
Abacus hat die entsprechenden Fehler behoben. @tobiasstern du kannst weiter testen

**Comment by tobiasstern** [comment]
Hat soweit geklappt und nachdem in der Konfiguration für Rechnungen noch als ProduktNr "KUR" eingesetzt ist, funktioniert nun die Rechnungsauslösung für normale Kursrechnung.

Verifikation in Abacus mit dem SAC ist noch ausstehend.

**Comment by tobiasstern** [comment]
Konnte die erzeugte Rechnung in Abacus prüfen und die Details stimmen jetzt.
