### ISSUE TITLE
EVENTS: Kursrechnung bei Statuswechsel auslösen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1011]
Als Kursadmin möchte ich, dass die Teilnehmenden automatisch eine Kursrechnung erhalten, wenn der Kurs in den Status "Bereit zur Durchführung" wechselt.

Neu soll in `Events::Courses::State#summon_assigned_participants` für jede Teilnahme die Methode `ExternalInvoice::Course.invoice_participation(participation)` aufgerufen werden. Diese Methode wird mit #1008 erstellt. Falls die beiden Issues parallel entwickelt werden, kann hier einfach eine leere Methode erstellt werden, damit wir nicht blockiert sind.

Falls für eine Teilnahme bereits eine External Invoice existiert, wird keine neue erzeugt und auch kein Job enqueued.

# ToDo

- [x] Model anpassen
- [x] Specs schreiben

**Comment by tobiasstern** [comment]
`Falls für eine Teilnahme bereits eine External Invoice existiert, wird keine neue erzeugt und auch kein Job enqueued.`

Deckt das auch den Fall ab, wenn bereits eine *stornierte* Rechnung vorhanden ist? In dem Fall müsste drum eine neue Rechnung angelegt werden können.

**Comment by hunchr** [comment]
> Deckt das auch den Fall ab, wenn bereits eine _stornierte_ Rechnung vorhanden ist? In dem Fall müsste drum eine neue Rechnung angelegt werden können.

es macht sinn, wenn das in #1008 ergänzt wird

**Comment by tobiasstern** [comment]
Hey, macht dieser Code aktuell etwas? Wenn ich einen Kurs in "Bereit zur Durchführung" setze, werden dann Rechnungen erzeugt? Oder wird das erst noch implementiert?

Ich habe den Kurs hier getestet https://sac-cas.puzzle.ch/de/groups/1/events/13 aber sehe aktuell noch keine Möglichkeit, das Ergebnis zu prüfen.

**Comment by hunchr** [comment]
> Hey, macht dieser Code aktuell etwas? Wenn ich einen Kurs in "Bereit zur Durchführung" setze, werden dann Rechnungen erzeugt? Oder wird das erst noch implementiert?

Nein, dass kommt noch mit #1008. Hier wurde einfach eine leere Methode erstellt, wie im Ticket erwähnt, damit wir nicht blockiert sind.

**Comment by tobiasstern** [comment]
Okay, dann teste ich hier nicht weiter. Danke

**Comment by tobiasstern** [comment]
Habe getestet in https://sac-cas.puzzle.ch/de/groups/1/events/70 und es scheint sehr gut zu funktionieren.

Dieser Punkt hier für den Edge Case wurde nicht umgesetzt:
> > Deckt das auch den Fall ab, wenn bereits eine _stornierte_ Rechnung vorhanden ist? In dem Fall müsste drum eine neue Rechnung angelegt werden können.
> 
> es macht sinn, wenn das in [#1008](https://github.com/hitobito/hitobito_sac_cas/issues/1008) ergänzt wird

Derzeit verhält es sich so: Wenn ich derzeit für eine Anmeldung manuell eine Rechnung erzeuge und dann storniere, und danach den Kursstatuswechsel vornehme, wird für diese Anmeldung keine neue Rechnung erzeugt.

Ich bin mir nicht sicher, wie schlimm das ist. Man kann ja immer noch manuell die Rechnung auslösen. Gefahr ist, dass man dies nicht weiss oder nicht sieht, dass die Rechnung noch fehlt.

@codez wie schwierig schätzt du die Umsetzung davon ein?

**Comment by codez** [comment]
@tobiasstern Das wäre etwa in einem halben Tag umsetzbar. Ich würde allerdings damit zuwarten, bis dieser Fall wirklich mal auftritt. Tönt für mich eher selten.
