### ISSUE TITLE
EVENTS: Kursrechnung bei TN-Statuswechsel "Aufbieten" auslösen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1013]
Als Kursadmin möchte ich, dass die Teilnehmenden automatisch eine Kursrechnung erhalten, wenn der TN-Status auf "Aufgeboten" wechselt.

Neu soll im `SacCas::Event::ParticipationsController` ein `after_summon` Callback registriert werden, welches für die Teilnahme die Methode `ExternalInvoice::Course.invoice_participation(participation)` aufruft. Diese Methode wird mit #1008 erstellt. Falls die beiden Issues parallel entwickelt werden, kann hier einfach eine leere Methode erstellt werden, damit wir nicht blockiert sind.

Falls für eine Teilnahme bereits eine External Invoice existiert, wird hier keine neue erzeugt und auch kein Job enqueued.

# ToDo

- [x] Model anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
#1008 muss dann noch gemergt werden.

**Comment by tobiasstern** [comment]
Funktioniert grundsätzlich! Beim Aufbieten wird eine Rechnung ausgelöst.

Der Teil scheint noch nicht ganz zu gehen:
`Falls für eine Teilnahme bereits eine External Invoice existiert, wird hier keine neue erzeugt und auch kein Job enqueued.`
Wenn ich eine Anmeldung nach dem Aufbieten nochmals aufbieten, wird erneut eine Rechnung ausgelöst und es hat dann mehrere. In meinem Testfall war die erste Rechnung noch im Status Entwurf dabei, falls das eine Rolle spielt.

@hunchr Kannst du bitte prüfen, ob sich das noch fixen lässt?

**Comment by tobiasstern** [comment]
Retest erfolgreich!
