### ISSUE TITLE
EVENTS: Kursrechnungen stornieren bei Kursabsage

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1015]
Als Kursadmin möchte ich, dass die Kursrechnungen automatisch storniert werden, wenn der Kurs in den Status "Annuliert" wechselt.

Neu soll in `Events::Courses::State` ein `after_update` Callback `cancel_invoices` erstellt werden, falls der Status auf `annuled` gewechselt hat.

Das Callback storniert alle Rechnungen aller Kursteilnehmenden (via `ExternalInvoice#link`) mittels `Invoices::Abacus::CancelInvoiceJob.new(invoice).enqueue!`

# ToDo

- [x] Model anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by njaeggi** [comment]
Was genau ist annuled? Diesen Status gibt es bisher noch nicht
1. Kann von jedem Status zu annuled gewechselt werden?
2. Kann nachdem ein Event "Annuliert" wird, nochmals in einen anderen Status gewechselt werden?

**Comment by tobiasstern** [comment]
@self Testing muss warten bis Kursrechnung erzeugt werden können.

**Comment by tobiasstern** [comment]
Erfolgreich getestet
