### ISSUE TITLE
PEOPLE: Beitragskategorie calculate sollte nicht nil zurückgeben

### ISSUE THREAD

**Issue by hunchr** [hitobito/hitobito_sac_cas#1023]
`SacCas::Beitragskategorie::Calculator#calculate` kann aktuell `nil` returnen, wenn die Person unter 6 oder über 199 Jahre alt ist. Diese Methode sollte aber laut @daniel-illi nie `nil` zurückgeben.

**Comment by daniel-illi** [comment]
Die Methode `#calculate` kann schon `nil` zurückgeben, denn die Beitragskategorie ist nur definiert für Alter von 6-199 Jahren.
Aber es dürfte keine Rolle erstellt werden für Personen ausserhalb dieser Altersspanne, daher sollte im Regelfall das `#calculate` für solche Personen auch gar nicht aufgerufen werden.

**Comment by hunchr** [comment]
@daniel-illi dann bleibt aber der bug bestehen, dass [hier](https://github.com/hitobito/hitobito_sac_cas/pull/969/files#diff-4bd4e8b70e264bae244485c7f113ed58d6e10bfa6ad325f06cec44f731971bca) die beitragskategorie nil sein kann und somit die translations als hash gerendert werden
