### ISSUE TITLE
PEOPLE: `nav1-1_people` Haupt-E-Mail und Duplikate

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#1079]
## Anpassungen in nav1-1_people

Im nav1-1_people Import gibt es mehrere Personen, die dieselbe Email besitzen. Dies ist oft bei Familienmitgliedern oder Firmen/Personen-Kombinationen der Fall. Neu sollen beim Import, sobald der Fehler einer bereits existierenden Haupt-Emailadresse auftritt, die Emailadresse unter additional_emails mit dem Label Duplikat abgelegt werden.

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_imports/people_importer.rb
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/sac_imports/person_entry.rb

# ToDo

- [x] Handling Emails Implementieren
- [x] Importer mit NAV1 csv lokal testen

**Comment by rnestler** [comment]
> Importer mit NAV1 csv lokal testen

Lokal laufen gelassen und report als `nav1-1_people_2024-10-07-14:29.csv` abgelegt.
