### ISSUE TITLE
SIGNUP: Anpassungen am Summary Screen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#1094]
Folgeticket zu #932

Folgende Punkte sind noch offen
- [x] Labels  kontrollieren (mittlerweile sind  #984, #985 und #986 gemerged und labels sollten stimmen)
- [x] Abstände zwischen Label und Text fehlt
- [x] Die Familienmitglieder wells sollten immer gleich gross sein
- [x] Bei den Checkboxen müssen die letzten 3 mit einem * als required markiert werden
- [x] Button soll "Mitgliedschaft beantragen" statt "Registrieren" heissen
- [x] Der blaue Info Alerttext muss vertauscht werden (Bei NeuanmeldungenNV gibt es den Sektionsfreigabeprozess)
- [x] Texte überlappen sich auf kleinen Screen grössen

**Comment by njaeggi** [comment]
Habe alle Labels überprüft, die einzigen nötigen Änderungen sind:
- Label für Email von "Haupt E-Mail" zu "E-Mail" ändern
- Geschlecht auf Zusammenfassung hinzufügen

**Comment by njaeggi** [comment]
Will be fixed with #1099
