### ISSUE TITLE
SIGNUP: Layouting issues

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#1099]
Das Layout beiden Wizards soll konsistent und einheitlich sein. Es gibt da noch verschiedene Probleme die wir hier sammeln und uns dann festlegen wie wir genau layouten wollen, bisher sehe ich normalen Formbuilder, `.w-50` und `.align-with-form` die nicht immer sauber zusammenspielen

- Abowizard alignment von info am summary Screen und Fehlermeldungen 
![Image](https://github.com/user-attachments/assets/e2c52f11-cbe5-4b7f-910c-a73b4d1192ee)

**Comment by ThomasEllenberger** [comment]
Ein weiterer Input vom SAC: 
![Image](https://github.com/user-attachments/assets/8804a612-339b-4425-919b-518da30a429b)

**Comment by njaeggi** [comment]
Gewünschte Änderungen aus: #1090 

![Image](https://github.com/user-attachments/assets/df067179-a443-403b-8e33-c604d0cb21be)

**Comment by njaeggi** [comment]
Die Bootstrap Klasse `w-50` war noch drin vom Zeitpunkt wo das aside noch nicht existiert hat im Abo Magazin Wizard, (damit die Tabelle nicht die ganze Seite eingenommen hat). Dies habe ich entferent. Grundsätzlich würde ich bei allen Wizard Summary Seiten align-with-form verwenden, damit alle Wizard Seiten gleich aligned sind.

**Comment by Largo** [comment]
Ich habe den Abstand zwischen Sektion und Eintrittsdatum noch mit dem der Kontaktperson angeglichen. Das Landlabel hatte noch einen Schreibfehler drin.
Ich habe im Jira noch nachgeschaut ob noch was offen ist. => scheint erstmal gut.

![image](https://github.com/user-attachments/assets/ffc0bd20-64c2-4110-a82c-23c33a8a26fb)
