### ISSUE TITLE
EMAILS: Nachbesserungen Sektions Signup Email

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#1101]
Im nachgang zu #941 soll ein neuer {person-details} Platzhalter eingeführt werden, welche die Darstellung der Personendaten übernimmt (analog `invoice-details`).  

Die Personen Platzhalter bis auf `{first-name}` können entfernt werden.

**Comment by ThomasEllenberger** [comment]
Issue ist obsoleth
