### ISSUE TITLE
EVENTS: Kursrollen anpassen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#1104]
Der SAC kennt für seine Kurse nur Kursleitung, Klassenleitung und Teilnehmer Rollen. Zudem können Leiter als selbständing oder unselbstständig erwerbend sein (relevant für die Abrechnung). 

Dafür sollen folgende Anpassungen gemacht werden. 

- `Event::Course.role_types` anpassen (Cook, Helper, Treasurer, Speaker entfernen)  
- Übersetzung für Leader anpassen (Kursleitung)
- Übersetzung für AssistantLeader anpassen (Klassenleitung)
- neues Attribut `self_employed: boolean, default: false` auf `Event::Roles` 
- `self_employed` im new und edit formular und im roles aside anzeigen (via render_extensions im core)

**Comment by tobiasstern** [comment]
`self_employed im new und edit formular und im roles aside anzeigen (via render_extensions im core)
`
Im New ist es noch nicht da:
![image](https://github.com/user-attachments/assets/d4da2b31-ca25-45c6-a2f9-60e3e28d22fa)

 
Ergänzung von Andreas Gurtner: zudem kann der Kurs nach dem Hinzufügen eines Kursleiters (mit Rolle bearbeiten und Flag selbstständig gesetzt) nicht mehr aufgerufen werden: https://sac-cas.puzzle.ch/de/groups/1/events/9 (500er Fehler). Bitte untersuchen, woran das liegt, ob es was mit dem zu tun hat.

**Comment by njaeggi** [comment]
Das Problem das die Checkbox im new nicht angezeigt wird, konnte ich fixen, sobald es gemerged ist, werde ich ein Int Deployment machen und dich hier informieren.

Das Problem das ein 500er Fehler kommt bei diesem Event: https://sac-cas.puzzle.ch/de/groups/1/events/9. Hat nichts mit diesem Isssue zutun.

Das Problem kommt von den Attachments auf dem Event und hat nichts mit diesem Ticket zutun. Ist da bereits ein Problem bekannt? Ich habe auf der Integration die Attachments auf dem Event entfernt, um zu sehen ob es daran liegt, das Event ist jetzt wieder aufrufbar.

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/72002/?environment=integration

**Comment by njaeggi** [comment]
@tobiasstern die Checkbox ist nun auch beim new Formluar auf der Integration:

https://sac-cas.puzzle.ch/de/groups/1/events/8/roles/new?event_role%5Btype%5D=Event%3A%3ARole%3A%3ALeader

**Comment by tobiasstern** [comment]
Okay danke!

Das 500er Issue konnte ich auf das Eckdatenblatt zurückführen. Habs beim https://sac-cas.puzzle.ch/de/groups/1/events/9 nochmal erzeugt und jetzt ist wieder Error 500. Hat aber mMn nichts mit diesem Ticket hier zu tun sonder dem hier: #993 ich kommentiere es dort.

**Comment by codez** [comment]
Folge Issue, damit "Selbständig erwerbend" nur bei Leitungsrollen angezeigt wird: #1196
