### ISSUE TITLE
EVENT: Abwesende Personen können nicht angezeigt werden.

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1115]
### Aktuelles Verhalten

Wenn man auf irgend einem Kurs in der “Teilnehmende”-Ansicht auf “Abwesende” klickt, wird ein 500er internal server error angezeigt.

Dabei scheint es egal zu sein, ob es dort Personen hat oder nicht.
![grafik](https://github.com/user-attachments/assets/120ad499-d847-4f66-955b-bbbc9d12d17d)

### Gewünschtes Verhalten

Keine Fehlermeldung mehr...

### Schritte zu reproduzieren

1. auf irgend einem Kurs in der “Teilnehmende”-Ansicht auf “Abwesende” klicken
2. 500er internal server error wird angezeigt.

### Wann ist der Fehler aufgetreten?

03.10.2024

### hitobito version

2.3.0

### Organisation

SAC

**Comment by hunchr** [comment]
war sogar ein problem im core

**Comment by ThomasEllenberger** [comment]
> war sogar ein problem im core

@hunchr inwiefern denn das? Das Feature "Abwesende" ist meines Erachens kein COre Feature...?

**Comment by hunchr** [comment]
> @hunchr inwiefern denn das? Das Feature "Abwesende" ist meines Erachens kein COre Feature...?

ob es abwesende im core auch gibt, weiss ich nicht, aber die filter methode, welche alle anderen personen rausfiltert, befand sich im core. vielleicht gab es diesen bug also auch noch bei anderen wagons, welche diese personenfilterliste benutzen

**Comment by tobiasstern** [comment]
Prima 👍
