### ISSUE TITLE
Bug: Rechnungserzeugung schlägt fehl

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#1124]
Aktuell werden die erstellten Rechnungsaufträge offenbar nicht korrekt an Abacus übermittelt. Sie bleiben im Status Entwurf und im HIT-Log werden Fehler geloggt. Es betrifft die Rechnungserzeugung durch den Button Mitgliedschaftsrechnung auf der Rechnungs-View in einem User-Profil sowie die Erzeugung bei Kursrechnungen manuell/automatisch.

![Image](https://github.com/user-attachments/assets/9c6ce190-630d-486d-9449-71a818e26bf9)

![Image](https://github.com/user-attachments/assets/8a9d9863-5452-402c-8c7d-b79df2a077fe)

Ausserdem lösen die Links im Log einen 500er Fehler aus.

**Comment by rnestler** [comment]
Das abacus credential wurde ja angepasst und scheinbar auch für den testing Mandanten (wäre unnötig gewesen). Wir müssen dies also auf der staging Umgebung anpassen.

**Comment by rnestler** [comment]
Wir haben die credentials aktualisiert und die jobs sollten nun wieder laufen.
