### ISSUE TITLE
EVENTS: Teilnahmen annullieren bei Kursabsage

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1139]
Als Kursadmin will ich, dass bei einer Kursabsage alle Anmeldungen des Kurses den Status auf Annulliert wechseln.

Akzeptanzkriterien:

Absage erfolgt durch bereits bestehende Funktion “Absagen” auf dem Kurs

Alle Anmeldungen für den betroffenen Kurs, unabhängig von ihrem Status, werden auf Annulliert gesetzt.

 
# ToDo

- [x] Modelanpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Funktioniert grundsätzlich, aber zwei Dinge:

- Der Status wird im UI als "Annulled" angegeben. Es sollte aber "Annulliert" heissen.
![Image](https://github.com/user-attachments/assets/44e3aa35-8896-4467-bbb8-df3a30313a19)
![Image](https://github.com/user-attachments/assets/b802da83-a1dc-4d29-94fd-790368df1b80)

- Die Anzeige auf "Teilnehmende" und "Anmeldungen" ist danach komisch: Die Personen werden zum Teil unter Teilnehmende und auch unter Abwesende aufgelistet, siehe Bilder. Ich kann mir nicht erklären, warum genau diese Personen so gehandhabt werden. Siehe mein Testkurs https://sac-cas.puzzle.ch/de/groups/1/events/41/participations?filter=revoked 
![Image](https://github.com/user-attachments/assets/06cbf85c-2b95-49b4-941b-e7ab358f769f)
![Image](https://github.com/user-attachments/assets/dda615e3-820a-4747-bb98-e8d43b93c681)
![Image](https://github.com/user-attachments/assets/ae06f80e-047d-4cd3-b1fd-69a8bdafea7a)


Dass die Kursleitung noch unter "Leitungsteam" aufgeführt wird, finde ich gut, das bitte so lassen


Bitte diese beiden Punkte noch beheben.

**Comment by tobiasstern** [comment]
@codez Du hast "Annuliert" falsch geschrieben, ein L statt zwei :D 

Und wenn ich einen Kurs absage, dann sehe ich die Leute Leitungsrollen nicht mehr auf dem Kurs. Hast du das bewusst geändert?

In z.B. https://sac-cas.puzzle.ch/de/groups/1/events/64/participations?returning=true gibt es noch die Participation von https://sac-cas.puzzle.ch/de/groups/1/events/64/participations/309 noch(korrekt im Status annulliert)  aber sie wird nicht mehr angezeigt.

**Comment by codez** [comment]
Ok, da spielt einiges zusammen, oder eben nicht. Ich habe es jetzt so angepasst, dass nur TN (egal welcher Status, insbesondere auch diejenigen, welche nicht am Kurs dabei sind wie Abgelehnte oder Warteliste) auf den Status annulliert gesetzt werden. 
Der Status von Personen im Leitungsteam wird eigentlich nie angepasst und muss "aktiv" bleiben, damit diese im "Leitungsteam" Tab erscheinen.

**Comment by tobiasstern** [comment]
Erfolgreich getestet
