### ISSUE TITLE
EVENTS: Rechnung für nicht erschienen bei Kursen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1145]
Als Kursadmin will ich, dass wenn ein/e TN als nicht erscheinen gekennzeichnet ist und ich den Kurs abschliesse, der Person die No-Show-Gebühr in Rechnung gestellt wird.

Die No-Show-Gebühr ist eine Annulationskostenrechnung (AKR) mit 100% der Kosten (Gemäss Kurs-AGBs)

Die AKR wird erzeugt, falls noch keine gleiche AKR vorhanden ist.

Die Buchungsposition dieser Rechnung soll analog den anderen AKR sein. Positionsbeschreibung: Bezeichnung + Kursstufe. Beispiel "100% Annulationskosten für SAC-Basiskurs"

Das Feld “Ersetzt Rechnung” wird mit dem UserField 22 gesetzt, analog andere AKR

Bereits vorhandene Kursrechnungen (bezahlt oder nicht) werden storniert.

Wenn bei einer Nicht erschienen Anmeldung der Button “Rechnung erstellen” geklickt wird, soll eine solche AKR 100% erzeugt werden.

# ToDo

- [ ] Domainklasse anpassen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Getestet hier https://sac-cas.puzzle.ch/de/groups/1/events/70/participations?filter=revoked mit User https://sac-cas.puzzle.ch/de/groups/4255/people/340459/external_invoices

Es scheint zu funktionieren in Hitobito. 
In Abacus bin ich mir nicht sicher: 
- Es hat da eine Gutschrift erzeugt für den Kunden.
- Und auf der AKR fehlt noch das Feld "Ersetzt Rechnung"
