### ISSUE TITLE
EVENTS: Kurs abschliessen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1150]
Als Kursadmin will ich beim Abschliessen eines Kurses, dass TN Status automatisch angepasst werden.

Neu soll beim Statuswechsel zu "Abgeschlossen"/`closed` der Status aller TN, welche sich im Status "Aufgeboten"/`summoned` befinden, in den Status "Teilgenommen"/`attended` wechseln. Diese Funktionalität existiert bereits ähnlich im Youth Wagon und muss entprechend im SAC Wagon überschrieben werden (`update_attended_participants_state` und auch `update_assigned_participants_state`, Teilnahmen im Status `assigned` ändern im SAC nicht).

Ausserdem soll auf dem Button für den Statuswechsel auf dem Kurs bei "Abschliessen" noch ein Confirmation Dialog mit folgendem Text angezeigt werden, bevor der Request abgeschickt wird:

> Das Abschliessen versetzt alle Anmeldungen mit Status _Aufgeboten_ in den Status _Teilgenommen_. Für alle Anmeldungen im Status _Nicht erschienen_ wird eine Annulationskostenrechnung 100% erzeugt.

# ToDo

- [x] Model/View anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Klappt 👍
