### ISSUE TITLE
Fehlermeldung bei Austritt

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1154]
### Aktuelles Verhalten

Klickt man pei Person https://sac-cas.puzzle.ch/de/groups/4255/people/150896/history auf "Austritt" bekommt man einen 500er Fehlter

### Gewünschtes Verhalten

Keine Fehlermeldung mehr - Austritt wird korrekt vorgenommen

### Schritte zu reproduzieren

1. ![grafik](https://github.com/user-attachments/assets/53ff94a2-deae-4ada-b3a2-a6dec8a596fe)
2. ![grafik](https://github.com/user-attachments/assets/458e4e2f-2a22-4c3e-9ac4-4bb77bd16b8b)

### Wann ist der Fehler aufgetreten?

18.10.2024

### hitobito version

2.3.0

### Organisation

SAC

**Comment by Largo** [comment]
Grund: Familie hat keine Mainperson

**Comment by rnestler** [comment]
> Grund: Familie hat keine Mainperson

Soll das einfach in den Daten auf staging angepasst werden oder sollen wir diesen Fall handeln?

**Comment by ThomasEllenberger** [comment]
Das sollte auf Prod mit dem neusten Import ja nicht mehr möglich sein.
Gehe desshalb davon aus, dass sich dieses Problem von alleine löst, wenn wir auf Int einmal neue Daten seeden.

Übernehme dies und mache einen entsprechenden Kommentar im Jira Ticket.

**Comment by ThomasEllenberger** [comment]
Da das Verhalten mit den neuen Imports nicht mehr nachgestellt werden kann, wird dieses Ticket geschlossen.
