### ISSUE TITLE
Hitobito Log 500 Error

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#1165]
Aktuell (seit ca. 16:00 Uhr ev früher) auf der Integration gibt die Hitobito-Logseite eine 500 Fehlermeldung:
https://sac-cas.puzzle.ch/de/hitobito_log_entries
![Image](https://github.com/user-attachments/assets/6e2d3440-3ea7-449e-9b0e-b91174b09db4)

Heute Vormittag hatte sie noch funktioniert.

Update:
Auf dem Rechnungs-Tab in dem Profil wird ebenfalls ein 500er Fehler angezeigt. Hängt ev. zusammen?
https://sac-cas.puzzle.ch/de/groups/2/people/600147/external_invoices

**Comment by Largo** [comment]
Weitere Erkentniss: Der Fehler ist auf dem Rechnungstab.

**Comment by mtnstar** [comment]
```
ActionView::Template::Error

The single-table inheritance mechanism failed to locate the subclass: 'ExternalInvoice::Course'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite ExternalInvoice.inheritance_column to use another column for that information.
```

**Comment by codez** [comment]
Die Klasse wurde umbenannt zu ExternalInvoice::CourseParticipation. Da habe ich die Migration vergessen. Hab's manuell auf der Integration angepasst. 

Es besteht allerdings noch das Problem, dass wenn eine Event::Participation gelöscht wurde, die Rechnung momentan nicht gelöscht wird und dann beim Anzeigen der Rechnung weiterhin ein Fehler auftritt, weil die Verknüpfung zum Anlass fehlt. @tobiasstern wie wollen wir damit umgehen? Soll eine Rechnung ebenfalls gelöscth werden, wenn die Teilnahme gelöscht wird? Oder darf eine Teilnahme/Kurs nicht mehr gelöscht werden, sobald Rechnungen dafür existieren?

**Comment by tobiasstern** [comment]
@codez Wenn bereits eine Rechnung vorhanden ist, soll die Anmeldung nicht mehr gelöscht werden können.

Der ordentliche Weg fürs Fach ist dann, die Anmeldung abzumelden.
