### ISSUE TITLE
Wizards: SAC Austritt Anpassungen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#1205]
- [x] Beim aktivieren der ersten checkbox (Aufbewahrung deiner Daten), sollen die anderen 2 checkboxes ebenfalls aktiviert werden. Dazu den `form_field_check_dependent_controller.js` im core erweitern, konfigurierbar via [stimulus value](https://stimulus.hotwired.dev/reference/values)

- [x] Text im blauen Bereich Anpassen, daten werden zwölf und nicht sechs Monate aufbewahrt

Die Texte der 3 Checkboxen anpassen:
  - [x] Checkbox im blauen Bereich: Ich möchte, dass meine Daten nach dem SAC Austritt erhalten bleiben.
  - [x] Checkbox: Ich möchte über Neuigkeiten vom SAC informiert bleiben und den SAC-Newsletter weiterhin erhalten.
  - [x] Checkbox: Ich möchte die SAC-Hüttenpost weiterhin erhalten und über Spendenaktionen vom SAC informiert werden.

---

 - [x] Zudem sollen die Texte der Checkboxen rechts von der Checkbox stehen und richtig aligniert sein.

 - [x] Checkboxen sollen gleich aligniert sein wie das dropdown

 - [ ] Die Vordefinierten Austrittsgründe Anpassen (eventuell schon passiert, siehe https://saccas.atlassian.net/issues/HIT-38, besprechen mit @daniel-illi)

**Comment by rnestler** [comment]
@amaierhofer Ich bin mir nicht sicher wie ich das dem alignment lösen soll. `labeld` ist ja im core definiert: Soll ich das ändern, so dass es es label und checkbox auch swappen kann? Oder den Helper gar nicht verwenden?

**Comment by rnestler** [comment]
Varianten:

Aktuell:
![image](https://github.com/user-attachments/assets/3081c913-b85f-4b15-9b3a-fdd998ddd94c)


1 Checkbox im blauen info Fenster:
![image](https://github.com/user-attachments/assets/52d2a7e6-d0af-4e8f-b150-a10465aff7ce)

Die checkboxen hier zu alighnen könnte etwas mühsam werden.

Checkboxen aller ausserhalb:
![image](https://github.com/user-attachments/assets/671982da-861d-4349-a954-2fae581ccccc)
