### ISSUE TITLE
PEOPLE: Sortierung nach "Rollen" führt zu 500er

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1217]
### Aktuelles Verhalten

Filtert man im SAC-Wagon in einer Personenliste die Spalte "Rolle" so führt dies zu einem 500er.

### Gewünschtes Verhalten

Filter funktioniert korrekt.

### Schritte zu reproduzieren

1. Auf beliebige Personenliste navigieren
2. Auf "Rollen" klicken um danach zu sortieren.

### Wann ist der Fehler aufgetreten?

06.11.2024

### hitobito version

2.3.4

### Organisation

SAC

### Screenshots, weiterer Kontext

![grafik](https://github.com/user-attachments/assets/88a5c419-e00c-4176-93ae-2253a9f7d767)

### ToDos

- [x] Alle anderen Spaltenparameter manuell durchklicken um sicherzustellen, dass bei anderen auch alles korrekt funktioniert.

**Comment by njaeggi** [comment]
After reviews, only merge Core and SAC Pull Request, since it's a bug only appearing in SAC. Add the Mergefreeze Tag and assign it to me again, so that I can merge the last SBV Pull Request after the sac-master has been merged into master.
