### ISSUE TITLE
IMPORT: Rake tasks zum exportieren von tabellen in seeds dateien

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#1229]
Da wir für den prod datenimport die ganze DB droppen und wieder einspielen, sollen gewisse models vorgängig exportiert und anschliessend wieder importiert werden können. 

Dazu ein simples Ruby PORO erstellen, welches die Tabelle ausliest und im seed-fu format ablegt. Folgende Tabellen müssen berücksichtigt werden

- CustomContents (von int)
- OAuth::Application (von prod)
- ServiceToken (von prod)

**Comment by daniel-illi** [comment]
bereits gemergt mit #1266
