### ISSUE TITLE
PEOPLE: Abgelehnte Neuanmeldung

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#124]
Refs: #109

Wenn eine Neuanmeldung abgelehnt wird, soll das Login dieser  Person gesperrt werden sofern sie keine weitere Rolle hat.

Der Ablehnungsgrund wird bisher als Notiz hinterlegt. Muss diese Person irgendwie noch mit Blacklist oder so gekennzeichnet werden? Muss klar ersichtlich sein wenn diese Person mal abgelehnt wurde? und wenn ja, von wem?

**Comment by tobiasstern** [comment]
Gemäss https://saccas.atlassian.net/browse/HIT-147 soll bei Ablehnung:

```
- wird die Mitgliedschaft nicht aktiviert, 
- das Mitglied über diesen Entscheid informiert und 
- der Antrag von der Pufferliste entfernt.
- Achtung: in diesem Kontext müssen potenziell weitere Events ausgelöst werden, z.B. Rechnungsstorno und Gutschrift, sofern bereits bezahlt wurde!
```

Es scheint hier noch Klärungsbedarf zu geben, was alles passieren muss.

**Comment by mtnstar** [comment]
Laut @sykesonrocks reicht es momentan so wie es implementiert ist.
wir sperren den Zugang nicht und es ist auch OK wenn sich diese Person dann über eine andere Sektion als Neumitglied anmeldet. Das jemand abgelehnt wird kommt angeblich sehr selten vor.
Faktura Themen werden wir sicher noch anschauen. Im Moment scheint es so als ob dies aber weit vor der Fakturierung geschieht und diese nicht tangiert wird.
