### ISSUE TITLE
Bei Kurs-Anmeldung falsche E-Mail-Vorlage

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#1262]
Wenn man sich für einen Kurs anmeldet und die Anmeldung als unbestätigt aufgenommen wird, dann wird fälschlicherweise auch noch die alte Anlas-E-Mail verschickt, zusätzlich zur neuen Kurs-Email.

Vgl. Bild aus Mailtrap:
![Image](https://github.com/user-attachments/assets/c5428301-e257-4bdb-8d3c-c65b3c77ecd3)

Die alte Vorlage ist glaube ich diese hier https://sac-cas.puzzle.ch/de/custom_contents/11/edit

Bitte sichergehen, dass keine alte Vorlagen verwendet werden für die Kurse

**Comment by amaierhofer** [comment]
Scheint als ob wir hier im Wagon was dazugebaut haben, was aber auch schon via core bis zu einem Grad abgedeckt wird. Die Situation ist wie folgt: 

Voranmeldung eingegangen kommt vom core (CustomContent(key: event_application_pending)) siehe `Event::ParticipationMailer::confirmation` via `Event::ParticipationConfirmationJob`  und `Event::ParticipantAssigner{add_participant,remove_participant}` ()

Unbestätigte Kursanmeldung kommt vom wagon (CustomContent(key: "course_application_confirmation_unconfirmed")) via `Event::ApplicationConfirmationMailer` 

muss noch genauer angeschaut werden, was hier nicht richtig verhängt wird und was angepasst werden muss

**Comment by tobiasstern** [comment]
Hey @amaierhofer das geht noch nicht auf der Integration. Habe ich zu früh getestet?

**Comment by tobiasstern** [comment]
Erfolgreich getestet
