### ISSUE TITLE
EVENTS: Mails manuell auslösen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#1267]
## Ist
Die Mail “Kursvorbereitungen abschliessen“/`Event::LeaderReminderMailer::REMINDER_NEXT_WEEK` wird heute 1 Woche vor Kursbeginn automatisch ausgelöst und an alle Leitungsrollen geschickt. Je nachdem ist aber die Kursadmin noch nicht soweit und hat die im Mail referenzierten Dokumente noch nicht zum Kurs hochgeladen.

Die Mail “Umfrage“/`Event::SurveyMailer::SURVEY` wird heute 3 Tage nach Kursbeginn automatisch ausgelöst und an alle aktiven Teilnehmenden geschickt. Es wird  geprüft, ob der Umfragelink ausgefüllt ist. Je nachdem wird die Mail nicht verschickt.

## Soll

Als Kursadmin will ich den Versand dieser Mails selber steuern können, damit ich sicher bin, dass alle notwendigen Infos bereits vorhanden sind, bevor die Leute informiert werden.

Neu werden die beiden Mails nicht mehr automatisch verschickt, wenn das entsprechende Datum erreicht ist. Der Servey Job wird ausgebaut, der Leader Reminder Job verschickt nur noch das Mail 8 Wochen vor dem Event.

Neu ist auf der Kurs Info Seite ein neuer Dropdown Button "Mailversand" vorhanden, welcher nur für Kursadmins sichtbar ist (`can?(:create, event)`). Der Button wird nur angezeigt, wenn der Kurs-Status "Bereit zur Durchführung" oder "Abgeschlossen" ist.

Im Dropdown sind zwei Optionen vorhanden:
- “Kursleitung: Vorbereitung abschliessen“
- “Teilnehmende: Umfrage“

Klick auf eine Option soll einen einfachen Confirmation Dialog zeigen: “Bist du sicher, dass du diese Mails versenden willst?”. Bei Bestätigung wird der Versand der E-Mail gemäss den obigen Vorlagen ausgelöst (via deliver_later).

Der LeaderReminderMailer geht neu nur noch an die Rollen "Kursleitung" (ohne Klassenleitung). Der SurveyMailer geht neu an alle aktiven Teilnehmenden (`Event#participants_scope`).

Als Flash Success Message erscheint die Meldung "Es wurden {n} E-Mails verschickt."

Falls beim Versenden der Umfrage Mails der `link_survey` leer ist, wird ein Flash Alert angezeigt: "Es wurden keine E-Mails versendet, da kein Umfrage Link erfasst wurde."

# ToDo

- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Mailversand auch getestet, funktioniert 👍
