### ISSUE TITLE
Abos: Anmeldung button führt zu 500er

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#1276]
1. Neues Abo erstellen
2. Auf dem Info Tab Anmelde Button drücken -> 500er

```
ActionController::RoutingError at /de/groups/1050/mailing_lists/4/subscriptions/user
uninitialized constant Subscriber::UserController
```

Gibt es den Controller? stimmt die route? Gab es hier changes?

**Comment by njaeggi** [comment]
500er Error und Button Darstellung wurde vorerst auf das aktuell MailingList#subscribed angepasst und kann gemerged werden.

MailingList#subscribed verhält sich aktuell noch nicht genau so wie es sein sollte, dazu wurde ein weiteres Ticket erstellt: https://github.com/hitobito/hitobito_sac_cas/issues/1307
