### ISSUE TITLE
PEOPLE: Sektions Mitglieder Import löst Mails aus

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#130]
`FILE=tmp/xlsx/sektions_mitglieder.xlsx rails import:sektions_mitglieder`

löst auf der Integrationsumgebung hunderte Mails aus:

```
Mail sent. mailer: "Devise::Mailer", subject: "Anleitung zur Bestätigung Deiner E-Mail-Adresse", from: ["noreply@sac-cas.puzzle.ch"], to: ["blablixblu@gmx.ch"], message_id: "65427e00ef8a9_25751a401856e@delayed-job-54d85fb648-79bsj.mail", date: Wed, 01 Nov 2023 17:34:08 +0100
Delivered mail 65427e00ef8a9_25751a401856e@delayed-job-54d85fb648-79bsj.mail (2358.3ms)
```

Der Import wird dadurch auch irgendwie extrem langsam.

# Gewünschtes Verhalten

es sollten keine Mails gesendet werden während des Imports. Vorerst müssen die E-Mails eigentlich auch nicht als confirmed angeschaut werden.

- Es sollten nie Mails versendet werden während dem Import. Auf der Produktion wäre es eine Katastrophe wenn hunderte Mails an Personen versendet würden. Lässt sich das irgendwie blockieren?
- Lässt man den Import lokal laufen (docker dev setup), habe ich das Verhalten bisher nicht beobachten können. Sprich es werden nie Mails versendet
- Es macht den Import in der Integration extreeeem langsam

**Comment by amaierhofer** [comment]
Wurde durch löschen und re-importieren der Liste gelöst, das nochmalige importieren hat dabei keine Emails mehr ausgelöst
