### ISSUE TITLE
Geburtstage im Wizzard können nicht mit punkten geschrieben werden

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1334]
## Ausgangslage: 
In diversen SAC-Wizzards kann das Geburtsdatum, wenn als Sprache FR oder IT gewählt wurde, nur mit einem "/" getrennt werden, obwohl der Hilfetext dies mit einem "." anzeigt.
Ist die Sprache DE ausgewählt funktioniert es mit einem "." zwischen den Datumswerten, dafür nicht mit einem "/".

## Anforderungen:
Hat man den Wizzard auf FR oder IT eingestellt sollen im Datumsfeld auch "." als Trennung akzeptiert werden.

Dies kann zum Beispiel im Self-Registration Wizzard getestet werden: https://portal.sac-cas.ch/groups/6012/self_registration
Weiter Orte wo dies bekannt ist: 
- Onboarding die Alpen
- Onboarding Fan

## Mockup

Anmeldewizzard ist auf Französisch eingestellt. In der Vorschau wird das Geburtsdatum mit punkten getrenne. im Feld Geburtsdatum können aber keine punkte eingegeben werden.
![grafik](https://github.com/user-attachments/assets/1991fd47-49e2-4410-83ac-6b40b491fb33)

## ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by rnestler** [comment]
Ist das Problem möglicherweise, dass fr_FR anstelle von fr_CH verwendet wird? In Frankreich wird das Datum effektiv JJ/MM/AAAA geschrieben: https://en.wikipedia.org/wiki/Date_and_time_notation_in_France
