### ISSUE TITLE
Anpassungen Onboarding Wizzard

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1339]
Im Onboarding Wizzard hat es noch kleine Textliche Anpassungen welche vorgenommen werden sollen:

1.  Rechtschreibefehler in grauer Box. SAC-Geschäftsstelle schreibt sich mit Bindestrich
![grafik](https://github.com/user-attachments/assets/525f48de-fe45-4870-9130-8742bae050e3)

2. Rechtschreibefehler in der grauen Box. Leerschlag fehlt beim 01. November (noch 01. fehlt der Leerschlag)
![grafik](https://github.com/user-attachments/assets/4d6b2154-e0e3-4d48-8705-c36760971cd1)

3. Anpassung Text Checkbox Newsletter: Ich möchte den SAC-Newsletter abonnieren. &  Rechtschreibefehler Text Checkbox Beitragsreglement: Ich habe das Beitragsreglement gelesen und stimme diesem zu (diesem statt diesen)
![grafik](https://github.com/user-attachments/assets/62ecd0e5-68b1-4d41-8b60-d14c129fddeb)

**Comment by rnestler** [comment]
Ist "Ich habe die Datenschutzerklärung gelesen und stimme **diesen** zu" nicht auch ein Typo? Sollte doch "Ich habe die Datenschutzerklärung gelesen und stimme **dieser** zu" sein.

**Comment by njaeggi** [comment]
@rnestler Ich habe diese Änderung gemacht, da "diesen" grundsätzlich falsch ist 👍 

Nach kurzer Absprache mit @ThomasEllenberger haben wir uns entschieden die weiteren "SAC Geschästsstelle" Texte, welche nicht mit dem Onboarding Wizard zutun haben, noch nicht anzupassen und dies zuerst mit dem SAC abzusprechen
