### ISSUE TITLE
PEOPLE: AHV-Nummer auf Personendaten ausblenden

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1346]
## Ausgangslage:
Im Umfang von https://github.com/hitobito/hitobito_youth/issues/59 werden die AHV-Nummern im Youth Wagon auf den Personendaten gelöscht und sind fortan nur noch auf den Events als Eventfrage vorhanden. Dies wird erst im Q1 2025 erledigt. Damit beim SAC in der Zwischenzeit keine Personen eine AHV ausfüllen können, sollen die entsprechenden Felder im SAC-Wagon im UI ausgeblendet werden.

## Gewünschtes Verhalten:
Das Feld "AHV-Nummer" soll in den Personendaten im UI ausgeblendet werden, damit dieses für Benutzer nicht mehr ersichtlich und nicht mehr befüllbar ist.

# Mockup
Ist:
![grafik](https://github.com/user-attachments/assets/5872228a-b118-4680-b18e-88d94f203063)

Soll:
![grafik](https://github.com/user-attachments/assets/eeb1dc10-3b12-480e-827a-12cf4dd59b06)

# Tech-Spec

Views überschreiben und mit Kommentar hinweisen, dass das temporär ist.

# ToDo

- [ ] Views überschreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by rnestler** [comment]
Ich geh mal davon aus, dass es auch von der Profil Ansicht entfernt werden soll?

![image](https://github.com/user-attachments/assets/b33ccce3-13fe-46f4-bf64-fb7abeed5cfc)
