### ISSUE TITLE
Mailers: Anpassen der bcc für Membership mailers

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#1381]
Das bcc von folgenden Mailers soll einheitlich gestalltet werden und sowohl die Email Adresse der Sektion (falls hinterlegt) und die MV Email `SacCas::MV_EMAIL` im bcc enthalten.

- Signup::SektionMailer
- Memberships::SwitchStammsektionMailer
- Memberships::LeaveZusatzsektionMailer

Beim `Memberships::SwitchStammsektionMailer` wird aktuell die Sektion noch nicht übergeben, das fehlt noch. Ebenfalls soll geprüft werden ob die Operation nicht auch ohne dem lonely operator funktionieren kann. Die Rolle sollte ja existieren wenn ich den Wizard verwenden kann.

**Comment by njaeggi** [comment]
@amaierhofer Was genau ist gemeint mit "Operatio nicht auch ohne dem lonely operator funktionieren kann"?
