### ISSUE TITLE
E-Mail deaktivieren für Release

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1385]
## Beschreibung

Während dem GoLive des SAC sollen gewisse Emails noch nicht versendet werden. Da Mailtrap für die Produktiv-Umgebung bereits am 27.12.2024 deaktiviert wird, und zum Jahresbeginn diverse Emails automatisiert versendet werden, sollen diese für dieses Jahr noch deaktiviert werden.

## Deaktivierung Auto-Emails

Es sollen die folgenden automatisierten E-Mails komplett deaktiviert werden.

Vorlagen: 

    Qualifikation: Erinnerungsmail in 1 Jahr

    Qualifikation: Erinnerungsmail in 2 Jahren

    Qualifikation: Erinnerungsmail morgen

## Prüfung weitere Auto-E-mails

Im System prüfen, ob mit dem Jahreswechsel noch weitere automatische Mails verschickt werden und hier rückmelden.
# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by rnestler** [comment]
Ich denke dieses Ticket muss eine Person übernehmen die einen guten Überblick über Hitobito hat und sehr gut abschätzen kann wo weitere E-Mails versendet werden könnten.

**Comment by njaeggi** [comment]
Ticket zum Mailer reaktivieren: https://github.com/hitobito/hitobito_sac_cas/issues/1429
