### ISSUE TITLE
Textkorrektur: Teilnahmbestätigung Confirm

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#1390]
Wenn eine unbestätigte Kursanmeldung erstellt wird, wird dem User diese Info angezeigt (in gelb):

![Image](https://github.com/user-attachments/assets/0079ef9f-1198-4f1c-8153-743b10b7413f)

Textversion davon:

```
Es wurde eine Voranmeldung für Teilnahme von Thomas Pfister in SAC Tourenleiter/in 1 Winter Schneeschuhe erstellt. Die Teilnahme ist noch nicht definitiv und muss von der Anlassverwaltung bestätigt werden.
Für die definitive Anmeldung musst du die Teilnahmebestätigung über Drucken ausdrucken, unterzeichnen und per Post an die entsprechende Adresse schicken.
```

### ToDo
Der Text ist nicht richtig und soll wie folgt lauten:

"
Es wurde eine Voranmeldung erstellt. Diese ist noch nicht definitiv und muss von der Kursverwaltung bestätigt werden.
"

**Comment by rnestler** [comment]
Ich finde nicht heraus wo diese Meldung angezeigt wird. Bei mir sieht es so aus:
![image](https://github.com/user-attachments/assets/e93b1fdc-024e-4da6-a7e0-9b27c548d506)

Frisch nach der Erstellung der Anmeldung zeigt es gar keine Meldung an.

**Comment by ThomasEllenberger** [comment]
Der Text erscheint nur wenn im Kurs das Flag "Automatische Zuteilung" nicht gesetzt ist.

**Comment by tobiasstern** [comment]
Ach, das wusste ich nicht. Hat die Option "Zweitunterschrift" auch einen Effekt?

Lass den Teil bitte drin. Wir haben diese Option in allen Kursen deaktiviert. Ich finds zwar nicht ideal, aber man muss halt das System kennen, wenn man diese Funktionen anfängt zu nutzen.

**Comment by rnestler** [comment]
> Hat die Option "Zweitunterschrift" auch einen Effekt?

Auf den Text dieser Benachrichtigung nicht soweit ich das sehe. Aber das generierte PDF hat dann ein Unterschriftenfeld mehr:

Settings:
![image](https://github.com/user-attachments/assets/d663fa24-9304-471d-a163-d1a0cbee99db)


PDF:
![image](https://github.com/user-attachments/assets/41cae997-e40b-412f-a282-eb6e9f83de5a)

**Comment by tobiasstern** [comment]
Ok danke. Und wo/wann wird das PDF generiert?

Wie gesagt, bitte drinlassen diese Logiken.

**Comment by rnestler** [comment]
> Ok danke. Und wo/wann wird das PDF generiert?


https://github.com/user-attachments/assets/a82070e9-f71e-4dd3-b03b-cdeaab606a27
