### ISSUE TITLE
Als SAC Fan die Alpen abonnieren funktioniert nicht

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1404]
# Ausgangslage
Ich möchte als SAC Fan nun das SAC Die Alpen Abo abonnieren. Als Fan habe ich ein aktiven Fankonto mit hinterlegter E-Mail Adresse. 

- Ich gehe auf die Webseite und starte dort das Onboarding für die Alpen und komme auf den Onboarding Prozess 
- Im Schritt 1 gebe ich meine E-Mail Adresse ein
- Das System stellt fest, dass meine E-Mail Adresse bereits existiert und leitet mich auf die Login Maske
![image](https://github.com/user-attachments/assets/c080401e-5b50-441c-921b-d646e5c242fc)
- Ich gebe das Passwort ein uns sollte nun in auf Schritt 2 Personalien landen. 
**ERWARTETES VERHALTEN:** Ich gebe das Passwort ein uns sollte nun auf Schritt 2 Personalien landen und die bekannten Personalien sind geladen.
**TATSÄCHLICHES VERHALTEN:** Ich lande auf Schitt 1
![image](https://github.com/user-attachments/assets/5af676f7-45ed-4bac-9156-22a75f7542d0)
- Ich gebe in Schritt 1 die E-Mail Adresse nochmals ein und lande auf der Personalien Maske mit ausgefüllten bekannten Parametern
![image](https://github.com/user-attachments/assets/c20c3356-eb00-4cf8-a319-19d457121f67)
- Ich gebe alle fehlenden muss Parameter ein und gehe weiter zu Schritt 3
- In Schritt 3 klicke ich auf Abo Kostenpflichtig bestellen und nichts passiert.
![image](https://github.com/user-attachments/assets/df43546d-e441-4d29-a561-808073f9f65e)
![image](https://github.com/user-attachments/assets/bf334435-d133-46bb-90ff-de9033e9c646)

# Anforderungen
- Hat man bereits ein SAC-Konto und will die Alpen abonieren, landet man nach dem Eingeben von Mail & PW direkt im zweiten Schritt des Anmeldewizards
- Der Vorgang kann erfolgreich abgeschlossen werden

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by njaeggi** [comment]
Das Problem war mehr das Benutzen des Abo Wizards bei eingeloggten Usern, mit der Pull Request habe ich mehrere Probleme gelöst:
- Email Formular wird für eingeloggte Benutzer gar nicht mehr angezeigt
- Submit für eingeloggte Person funktioniert wieder

Ein paar kleine Anzeigefehler sind mir zudem noch aufgefallen, welche ich hier mal festgehalten habe: https://github.com/hitobito/hitobito_sac_cas/issues/1423

Eventuell muss das genauere Verhalten noch mit dem SAC besprochen werden, gerade das Info Feld "Fragen zur Mitgleidschaft?" anzuzeigen bei eingeloggten Usern oder doch nicht usw.

**Comment by njaeggi** [comment]
Die beiden referenzierten Tickets wurden ebenfalls implementiert, ausserdem sollte #1421 auch funktionieren.

Wichtig ist es jede Wizard Art einmal durchzuklicken, um sicherzugehen das sich jeder korrekt verhält, ob eingeloggt oder nicht!
