### ISSUE TITLE
API Ergänzung KVS

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1406]
## Ausgangslage

Typo3/sac-cas.ch Webseite Kursprogramm Aufnahmebedingung fehlen. Feld ist in api nicht vorhanden/war nicht spezifiziert.

## Anforderung

Events api ergänzen mit dem Textfeld 

Kurs->Anmeldung->Aufnahmebedingungen (i18n)

## ToDo

- [ ] Domainklasse erstellen oder anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by codez** [comment]
Bereits umgesetzt
