### ISSUE TITLE
E-Mail unlock_instructions Footer anpassen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1407]
## Anforderungen
Passt ein Mitglied seine Emailadresse in Hitobito an, wird ein Email zur Bestätigung der neuen Emailadresse ausgelöst. 

Das Mail hat noch einen inhaltlichen Fehler, der in allen Sprachen anzupassen ist: 
Footer : “Bergsportliche Grüsse” an Stelle von “Diese E-Mail wurde von Hitobito gesendet"

Bitte sicherstellen, dass es auch in den anderen Sprachen korrekt angepasst wird,
FR Salutations sportives
IT: Saluti sportivi

## Mockup

![image](https://github.com/user-attachments/assets/d39b428f-39e8-43b7-b287-9e6d3824cbae)

## ToDo

- [x] In `config/locales/wagon.de.yml` anpassen
- [x] In Transifex für Italienisch und Französisch anpassen

**Comment by rnestler** [comment]
Soll das gleiche auch grad für die unlock_instructions gemacht werden?

![image](https://github.com/user-attachments/assets/b98d8567-61dd-4d5c-9589-eb8bbefc3839)
