### ISSUE TITLE
504 Gateway Timeout beim Aufruf von SAC/CAS -> Abos -> Die Alpen - Zeitschrift des SAC

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1408]
# Anforderungen
504 Gateway Timeout beim Aufruf von SAC/CAS -> Abos -> Die Alpen - Zeitschrift des SAC

Timeout als quick-fix oder richtiger fix. was für MVP noch reicht.

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by amaierhofer** [comment]
Wahrscheinlich mit https://github.com/hitobito/hitobito/commit/696aa6144f0321897b64dfc840365ae583c5ae3f behoben
