### ISSUE TITLE
Profilbild wird nicht angezeigt

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_sac_cas#1411]
### Aktuelles Verhalten

Lade ich auf einer Person ein Profilfoto hoch, so wird dieses auf dem Profil nicht korrekt angezeigt.
In der Personenliste wird es hingegen angezeigt.

### Gewünschtes Verhalten

Profilbild soll auf der Person korrekt angezeigt werden

### Schritte zu reproduzieren

1. Bild hochladen
2. Bild erscheint nicht

BsP: https://portal.sac-cas.ch/de/groups/7727/people/635102

### Wann ist der Fehler aufgetreten?

16.12.2024

### hitobito version

2.3.8

### Screenshots, weiterer Kontext

![grafik](https://github.com/user-attachments/assets/c54d5ab1-281d-43c2-9b52-eee61ebdfc7e)
![grafik](https://github.com/user-attachments/assets/0dfebf77-0a66-49fb-889c-5d85cf4cf700)

**Comment by rnestler** [comment]
Ich habe noch eine Testperson auf der Integrationsumgebung erstellt: https://sac-cas.puzzle.ch/de/groups/6005/people/254059

Im korrekten Fall wird das Bild von https://hit-sac-cas-int-uploads.objects.rma.cloudscale.ch/vzp9hgfnwwqf0s9zyxwbbppuqtpy?response-content-disposition=inline%3B%20filename%3D%22Create_an_artificial%252C_clearly_stylized_profile_pic.jpg%22%3B%20filename%2A%3DUTF-8%27%27Create_an_artificial%252C_clearly_stylized_profile_pic.jpg&response-content-type=image%2Fjpeg&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=5TE0DM0B4N8K760FWVBD%2F20241216%2Fnone%2Fs3%2Faws4_request&X-Amz-Date=20241216T165826Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=9192f1e4bc1a82d749d5cf949166a1fc3538312153d839bb81ecb330e1c86fcc geholt.

Im fehlerhaften fall sehe ich zwei requests: https://sac-cas.puzzle.ch/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a125941893817756e0c1f409db9609b68633d05c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIU1NJSE56SUdPd1pVU1NJSE56SUdPd1pVIiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--ac61143639db874dc790d91482c3fa5536d6caf9/Create_an_artificial,_clearly_stylized_profile_pic.jpg?locale=de / https://sac-cas.puzzle.ch/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a125941893817756e0c1f409db9609b68633d05c/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIU1NJSU5URXlCanNHVkVraUNEVXhNZ1k3QmxRPSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--7bb9caf14c817f014bf15536afd237d576b5acf8/Create_an_artificial,_clearly_stylized_profile_pic.jpg?locale=de welche beide einen 500er auslösen.

**Comment by rnestler** [comment]
Ich denke https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#active-storage-default-variant-processor-changed-to-vips ist der Grund.
