### ISSUE TITLE
ROLES: Validierungen Mitglieder/Neuanmeldung Rollen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#145]
blocked by: #150 

Eine Person kann innerhalb einer Sektion (Layer) nur eine aktive Mitglieder oder pendente Neuanmeldung Rolle haben. 
Mit diesem Ticket sollen entsprechende Validierungen auf diesen Rollen eingeführt werden:

- Hauptsektion-Mitglieder Rollen: 
  * `Group::SektionsMitglieder::Mitglied`
  * `Group::SektionsNeuanmeldungenSektion::Neuanmeldung`
  * `Group::SektionsNeuanmeldungenNv::Neuanmeldung`

- Zweitsektion-Mitglieder Rollen: 
  * `Group::SektionsMitglieder::MitgliedZweitsektion`
  * `Group::SektionsNeuanmeldungenSektion::NeuanmeldungZweitsektion` 
  * `Group::SektionsNeuanmeldungenNv::NeuanmeldungZweitsektion`

- Die Gültigkeitsspanne einer Rolle definiert sich durch: 
  + Beginn:  `created_at`. Bei FutureRole: `convert_on`
  + End: `[delete_on, deleted_at.to_date, archived_at.to_date].compact.min || created_at.to_date.end_of_year`. Bei FutureRole: `convert_on.end_of_year`

- Eine Mitglied Rolle muss immer ein Von UND ein Bis Datum haben, bei Neuanmeldung braucht es kein Bis Datum, dies auch bei FutureRole prüfen
- Eine Person darf nicht mehrere gleichzeitig gültige Mitglieder Rollen in einer Sektion haben. Error beim Erstellen einer `Mitglied` oder `Neuanmeldung` Rolle: 
  + Diese Person ist bereits Mitglied (bis 31.12.2023)
  + Diese Person hat besitzt eine Neuanmeldung (ab 1.1.2024)
- Hauptsektion-Mitglieder Rollen einer Person dürfen keine überschneidende Gültigkeit haben
- Zweitsektion-Mitglieder Rollen einer Person in einer Sektion dürfen keine überschneidende Gültigkeit haben
- Für eine Zweitsektion-Mitglieder Rolle muss die ganzen Gültigkeitsdauer durch mindestens eine Mitgliederrolle abgedekt sein

- FutureRoles (hitobito/hitobito#2237) welche eine Mitglied-/Neuanmeldung-Rolle werden sollen (convert_to), ebenfalls berücksichtigen

- Beim Personen-Importer wird das Bis-Datum der Rolle falls diese aktiv ist auf den 31.12 des aktuellen Jahres gesetzt
- Alle Validierungen sollen beim Erstellen und Updaten der Rollen durchgeführt werden
- Auch archivierte/inaktive Rollen dürfen nicht überlappen (von/bis) (abgedeckt durch obenstehende Definition der Gültigkeitsspanne)

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/sac_cas/role/mitglied.rb
- https://github.com/hitobito/hitobito_sac_cas/blob/master/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb

# ToDo

- [x] Validierungen Mitglied, Neuanmeldung und entsprechenden FutureRole implementieren
- [x] Import Sektions Mitglieder anpassen
- [x] manuelles Testen
- [ ] CHANGELOG entry

**Comment by daniel-illi** [comment]
refs hitobito/hitobito#2285
