### ISSUE TITLE
PEOPLE: Verhalten von Familien beim Einschreiben in der Sektion

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#153]
Aktuell berücksichtigt das Einschreiben in der Sektion den Familien Kontext nicht. Mit diesem Ticket wird das Verhalten für Familien spezifiert. Text darunter wurde aus aus #132 extrahiert.

## 1. Wechsel der Stammsektion
- Wechsel Stammsektion kann in einer Familie nur durch eines der beiden Erwachsenen erfolgen. In diesem Fall werden die Rollen aller Familienmitglieder terminiert bzw. in Neuanmeldungen erstellt.

## 2. Antrag Zusatzsektion
- Im Gegensatz zu 1. kann dies auch durch ein Kind oder für die ganze Familie erfolgen

**Comment by sykesonrocks** [comment]
Bei einem Familienantrag ist mir aufgefallen, dass die Familienmitglieder korrekterweise einzeln als Person in der Gruppe "Neuanmeldungen" angelegt werden. Jedoch fällt mir auf, dass die Adressangaben nicht übernommen werden. Bitte berücksichtigen, danke.

**Comment by mtnstar** [comment]
> Bei einem Familienantrag ist mir aufgefallen, dass die Familienmitglieder korrekterweise einzeln als Person in der Gruppe "Neuanmeldungen" angelegt werden. Jedoch fällt mir auf, dass die Adressangaben des Familienoberhaupts nicht übernommen werden.
> 
> Bei Neuanmeldungen in Sektionen mit Freigabe: dies habe ich noch nicht getestet. Denkt bitte daran, dass nur der Antrag des Familienoberhaupts genehmigt werden muss.
> 
> E-Mail und Telefon: sollte für erwachsene Personen obligatorisch sein.

@sykesonrocks danke für dein Feedback. 
wir haben zwei Tickets erstellt, eines für die Adresse zu fixen, und eines E-Mail und Telefon obligatorisch zu machen: https://github.com/hitobito/hitobito_sac_cas/issues/417 und https://github.com/hitobito/hitobito_sac_cas/issues/418

Freigabe Neuanmeldung Familie haben wir etwas anderst gelöst: https://github.com/hitobito/hitobito_sac_cas/issues/340
meldest du mir es falls das so nicht gelöst werden kann?

**Comment by daniel-illi** [comment]
Diese Punkte wurden mit dem HIT-355 umgesetzt.
