### ISSUE TITLE
PEOPLE: Selbstregistrierung Personenfelder

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#169]
Die Personenfelder bei der Selbstregistrierung sollen gemäss folgendem Mockup angeordnet werden:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/c62bf7e5-1ac5-41e2-8b05-d0589868eedd)

Quelle: https://raw.githubusercontent.com/hitobito/hitobito_sac_cas/master/doc/SAC%20Hitobito%20Balsamiq-Mockups.pdf#page=5

## Abgrenzung
Adresszusatz machen wir vorerst nicht (related: https://github.com/hitobito/hitobito/issues/2226). Die Adressfelder sollen so gerendert werden wie überall sonst in hitobito.
Familienmitglieder bleiben vorerst in einem separaten Schritt
Hinweis-Text Familie wurde schon mit #171 umgesetzt

# TODO
- [ ] Felder für [MainPerson](https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/sac_cas/self_registration/main_person.rb) gemäss Mockup anordnen und ergänzen (obligatorische Telefonnummer)

**Comment by sykesonrocks** [comment]
Früher vervollständigte eine Auto-Complete Funktion während der Eingabe die Adresse. Dies ist heute nicht mehr der Fall:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/936dbbf4-93c6-4a64-b726-77abda6d5877)
Ist diese Auto-Complete Funktion noch vorgesehen oder werden wir es aus dem Scope nehmen?
