### ISSUE TITLE
PEOPLE: Selbstregistrierung Erklärungstext Familienmitgliedschaft

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#171]
Bei der Selbstregistrierung können Familienmitglieder erfasst werden. Bisher ändert sich dann der Submit Button Text von "Weiter als Einzelmitglied" zu "Weiter als Familienmitgliedschaft". In diesem Ticket soll ein zusätzlicher Hinweistext angezeigt werden, der die Folgen erklärt wenn man Familienmitglieder hinzufügt oder nicht.

![Screenshot 2023-11-30 at 18-10-24 SAC Hitobito Balsamiq-Mockups pdf](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/2bbcbe1f-362a-4815-9118-7bf72b60ec36)
Quelle: https://raw.githubusercontent.com/hitobito/hitobito_sac_cas/master/doc/SAC%20Hitobito%20Balsamiq-Mockups.pdf#page=6

Der Text soll natürlich übersetzbar sein, aber kann einfach als Rails I18n Text erfasst werden, er muss vorerst nicht dynamisch durch die User anpassbar sein.

# TODO
- [ ] Im [Partial](https://github.com/hitobito/hitobito_sac_cas/blob/master/app/views/groups/self_registration/_household.html.haml) Hinweistext gemäss Mockup einfügen (aber den Satz mit Hauptkontakt auslassen, den gibt es vorerst nicht)

**Comment by mtnstar** [comment]
@carlobeltrame Hauptkontakt gibt es zurzeit noch nicht. 
ggf. definieren wir dies dann einfach über die person die die rechnung bezahlt
