### ISSUE TITLE
PEOPLE: Selbsteinschreibung timestamps setzen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#178]
Spezifizieren und implementieren, was bei der Selbsteinschreibung für timestamps gesetzt werden sollen für created_at/convert_on und delete_on/deleted_at.

Relevant für Mitglied/MitgliedZusatzsektion Rollen

Hier muss der Code entsprechend angepasst werden:

app/models/self_inscription.rb:120 (beim TODO comment)

**Comment by Largo** [comment]
Nach [ROLES: Neuanmeldungs-Rollen sollten kein Enddatum haben · Issue #535 · hitobito/hitobito_sac_cas](https://github.com/hitobito/hitobito_sac_cas/issues/535), soll deleted_on null sein. 
Dann fehlt wohl noch created_at/convert_on/deleted_at

**Comment by daniel-illi** [comment]
duplicate of #178
