### ISSUE TITLE
PEOPLE: Personen Import Rollen Handhabung bei mehrmaligem ausführen 

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#180]
Der Import ist halbwegs idempotent, er kann mehrfach durchgeführt werden und aktualisiert dann bestehende Personeneinträge statt neue anzulegen. Die Personen werden dabei anhand der navision_id identifiziert.

Bisher hat der Importer der Einfachheit halber die Rollen bestehender Personen gelöscht und dann neu angelegt.
Da auf den Rollen keine navision_id vorhanden ist, kann bei bestehenden Personen nicht direkt identifiziert werden, welche Rolle durch den Import erstellt wurde. Daher ist es auch nicht einfach möglich, diese Rolle im Import zuverlässig zu identifizeren und zu aktualisieren.

Ich habe den Import angepasst, dass nur eine neue Rolle angelegt wird, falls es nicht bereits eine gibt bei welcher diese Attribute übereinstimmen:

`Import::Sektion::Mitglied#build_role(person)`
```
        person.roles.find_or_initialize_by(
          group: @group,
          type: Group::SektionsMitglieder::Mitglied.name,
          beitragskategorie: category,
          created_at: created_at,
          deleted_at: deleted_at,
          delete_on: delete_on
        )
```

Diese Logik muss überprüft werden, entspricht das dem gewünschten Verhalten?

**Comment by openscript** [comment]
Vorerst soll dies nicht umgesetzt werden. Die Schwierigkeiten wären:

- Nicht bei allen Entitäten haben wir einen stabilen Identifier. Dieser müsste erst noch geschaffen werden.
- Das Thema Import wird komplexer.
- Der Import könnte durch zusätzliche Abfragen die entstehen, länger dauern.

Dieses Feature könnte notwendig sein, wenn:

- Neue Daten mit bestehenden Daten über einen Import zusammengeführt werden sollen.
- Die Iteration von Daten importieren, korrigieren und Daten erneut importieren zu lange dauert.
