### ISSUE TITLE
ROLES: Import Kündigungsinfo Mitgliedschaft

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#198]
Feld im Export File: Letztes Austrittsdatum
terminated flag entsprechend setzen

klären ob gekündigte Mitgliedschaften überhaupt importiert werden sollen, ob man dies überhaupt darf aus datenschutzgründen

**Comment by mtnstar** [comment]
es werden nur die aktiven Mitglieder importiert, sprich der SAC stellt uns nur die Daten der aktiven Mitglieder in den Export Files zur Verfügung. Damit hat sich der Import der Kündigungsinfo erübrigt.

**Comment by ThomasEllenberger** [comment]
Ersetzt durch https://github.com/hitobito/hitobito_sac_cas/issues/1085
