### ISSUE TITLE
GROUPS: Anpassungen Gruppen und Rollen Top-Layer

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#221]
![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/eb00a648-171c-4dea-9820-275b9da6ae70)

**Comment by sykesonrocks** [comment]
Anforderung
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/29a32b8e-d795-4a3d-a3f8-bba0544a51e3)
vs. Umsetzung
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/a2738074-b7ff-43b6-8e86-0029521455e7)
Gab es ein Grund weshalb man es anders benannt hat?

**Comment by mtnstar** [comment]
@sykesonrocks ich habe die Bezeichnungen der Rollen wie in der Spez angepasst und die Änderungen sollten bald auf der Integrationsumgebung sein.
