### ISSUE TITLE
EVENTS: Seed für Kurs- und Qualifikationsarten & Kurskategorien

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#228]
Entsprechende Seed Daten für diese Modelle im Wagon erstellen. 

## Qualifikationsarten

Gültigkeit 6 Jahre, 4 Jahre reaktivierbar, 3 Forbildungstage notwendig:

- SAC Tourenleiter/in 1 Winter
- SAC Tourenleiter/in 2 Winter
- SAC Tourenleiter/in 1 Sommer
- SAC Tourenleiter/in 2 Sommer
- SAC Tourenleiter/in Sportklettern
- SAC Tourenleiter/in Alpinwandern
- SAC Tourenleiter/in Mountainbike

- SAC Tourenleiter/in Bergwandern
- Leiter/in Familienbergsteigen

unbeschränkt gültig, Tourenchef kann bearbeiten:

- Bergführer/in SBV
- Kletterlehrer/in SBV
- Wanderleiter/in 
- Schneeschuhleiter/in
- Mountainbikeleiter/in
- Diverse Leiter/in

## Kurskategorien & -arten

Unterhalb die zugehörign Kursarten

* SAC Leiterausbildung Winter (Kursarten vergeben entsprechende Quali)
  * Tourenleiter/in 1 Winter
  * Tourenleiter/in 2 Winter
* SAC Leiterausbildung Sommer (Kursarten vergeben entsprechende Quali)
  * Tourenleiter/in 1 Sommer
  * Tourenleiter/in 2 Sommer
  * Tourenleiter/in Bergwandern
  * Tourenleiter/in Mountainbike
* SAC Leiterfortbildung Winter (Kursarten verlängern alle Qualis, 2 Ausbildungstage)
  * Skitouren Freeride
  * Skitourenleiter/in Winter - Refresher
  * Rettung - Erste Hilfe
* SAC Leiterfortbildung Sommer (Kursarten verlängern alle Qualis, 2 Ausbildungstage)
  * Bergsteigen Sommer
  * Entscheidungsfindung
  * Rettung - Erste Hilfe 
* Skitechnik (Kursarten verlängern alle Qualis, 1 Ausbildungstag)
   * Skitechnik Stufe 1
   * Skitechnik Stufe 2
   * Skitechnik Stufe 3
* Lawinen (Kursarten verlängern alle Qualis, 1 Ausbildungstag)
  * Lawinen Ski + Snowboard
  * Lawinen Schneeschuhe
* Sportklettern (Keine Quali)
  * Sportklettern 
* Alpinwandern (Keine Quali)
  * Alpinwandern Stufe 1
  * Alpinwandern Stufe 2

**Comment by codez** [comment]
@sykesonrocks Kannst du bitte 5-10 Namen von unterschiedlichen Qualifikationsarten hinzufügen?

**Comment by sykesonrocks** [comment]
@codez Im Anhang findest du die ganze Liste an Qualifikationen.
[Liste_der_Qualifikationen_in_Navision-20240125.xlsx](https://github.com/hitobito/hitobito_sac_cas/files/14051172/Liste_der_Qualifikationen_in_Navision-20240125.xlsx)

Wichtig: die Qualifikationen sind kategorisiert (QUAL-1, QUAL-2, QUAL-3). Diverse Mechanismen sind von der Kategorie abhängig; z.B. es bestimmt wer die Qualifikation nachtragen/erfassen darf (Tourenchef und/oder Geschäftsstelle); es bestimmt die Verlängerungslogik (betreffend Fortbildungsstunden) etc.. Aus diesem Grund gehe ich aktuell schwer davon aus, dass wir in Hitobito eine Kategorisierung der Qualis berücksichtigen müssen.

**Comment by codez** [comment]
Danke für die Liste. Für dieses Ticket ist die Kategorisierung nicht relevant. Wir werden dies separat besprechen und spezifische Tickets machen.
