### ISSUE TITLE
PEOPLE: Selbsteinschreibung zu Zusatzsektion funktioniert nicht

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#235]
## Aktuelles Verhalten
Wenn man versucht einer Zusatzsektion beizutreten, kommt nach dem Bestätigungs-Dialog nur eine weisse Seite.

## Erwartetes Verhalten
Einschreibung bei der Neuanmeldungs-Gruppe für eine Zusatzsektion funktioniert normal.

## Schritte zum Reproduzieren
1. Den Selbstregistrierungslink einer Sektion A heraussuchen
2. Ein Mitglied einer anderen Sektion B imitieren
3. Den Selbstregistrierungslink von Sektion A besuchen
4. "Eintritt als Zusatzsektion" aktivieren
5. Beitreten anklicken
6. Im Dialog "Beitrag beantragen" klicken
7. Weisser Screen taucht auf

## Weitere Infos, Kontext
Mit einer lokal geseedeten Person kommt man schon gar nicht so weit: Da gibts schon Validierungsfehler von irgendeiner simulierten Rolle nach Schritt 3.
Wenn möglich, dies gleich mitfixen, z.B. via Anpassung der Seeds. Es sieht so aus als fehlen auf irgendeiner geseedeten Rolle irgendwelche Timestamps, aber ich kann nicht genau erkennen ob man einfach diese Spalten befüllen müsste, oder ob die Logik in mitglied_no_overlap_validation.rb mehr Fehler-Handling braucht.

**Comment by daniel-illi** [comment]
Es wird versucht, eine Rolle vom falschen Typ zu erstellen, eine `Group::SektionsNeuanmeldungenNv::Neuanmeldung` statt eine `Group::SektionsNeuanmeldungenNv::NeuanmeldungZusatzsektion`

**Comment by daniel-illi** [comment]
@carlobeltrame die Selbsteinschreibungs-Funktionalität scheint mir noch nicht fertig implementiert zu sein. 
Im Form gibt es zwar ein "Eintritt als Zusatzsektion", dieses hat aber keine Wirkung. Es wird immer eine Rolle erstellt von dem Typ, der auf der Gruppe konfiguriert ist für die Selbstregistrierung.
IMO ist für die Selbsteinschreibung die Selbstregistrierungsrolle irrelevant. Der Rollentyp müsste anhand der gewählten Option eruiert werden.
Ausserdem sollten abhängig von den bestehenden Rollen der Person nur gültige Optionen zur Verfügung stehen.

**Comment by mtnstar** [comment]
@carlobeltrame ich denke bei der Selbsteinschreibung sind auch noch nicht alle möglichen Funktionen implementiert.
wir können uns gerne mal über alle mögliche Use Cases da unterhalten
