### ISSUE TITLE
PEOPLE: Import Nicht-Mitglieder Rollen Sektionen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#242]
Folgende Rollen/Personen sollen via Importer in den Sektionen erstellt werden:

Untergruppe **Funktionäre**:

- Präsidium
- Mitgliederverwaltung

Untergruppe **Tourenkommission**:

- Tourenchef*in Sommer
- Tourenchef*in Winter
- Tourenchef*in Klettern
- Tourenchef*in Senioren
- Tourenleiter*in

Untergruppe **Hüttenkommission**:

- Hüttenobmann*frau

Die Hütten sowie deren Rollen/Personen werden via Hüttenimporter importiert

**Comment by sykesonrocks** [comment]
Welche Spalten benötigst du in welcher Reihenfolge - ich habe mir Folgendes aufgeschrieben:
1. Mitglied Nr
2. Mitgliederart
3. Sektion
4. Verteiler Code

Wie sieht es mit anderen Rollen aus, die zusätzlich im Bezeichnungsfeld beschrieben werden müssen (siehe Beispiele unten)?

Könntest du mit einem solchen Output arbeiten?
111111 | aktiv | 00005400 | Präsidium/Présidence
111111 | aktiv | 00005400 | Finanzen / Finances
111111 | aktiv | 00005400 | Mitgliederdienst/Gestion de membres
111111 | aktiv | 00005400 | Redaktion/Rédaction
111111 | aktiv | 00005400 | Commerce Portal Benutzer
111111 | aktiv | 00005400 | Vize-Präsidium/Vice-Président
111111 | aktiv | 00005400 | Sekretär/Aktuar Sektion
111111 | aktiv | 00005400 | Geschäftsführer Sektion
111111 | aktiv | 00005400 | Sonstige Vorstandsmitglieder Sektion
111111 | aktiv | 00005400 | Touren-Chef Sommer / Préposé aux courses d'été
111111 | aktiv | 00005400 | Touren-Chef Winter / Préposé aux courses d'hiver
111111 | aktiv | 00005400 | Touren-Chef Senioren / Préposé aux courses seniors
111111 | aktiv | 00005400 | Touren-Chef Klettern
111111 | aktiv | 00005400 | JO-Chef / Chefe OJ
111111 | aktiv | 00005400 | J+S Coach / Coach J+S
111111 | aktiv | 00005400 | KiBE-Chef / Chef AJ
111111 | aktiv | 00005400 | FaBe-Chef / Chef Alfa
111111 | aktiv | 00005400 | Kommissionspräsident
…

**Comment by openscript** [comment]
Wird mit https://github.com/hitobito/hitobito_sac_cas/issues/770 umgesetzt.
