### ISSUE TITLE
GROUPS: Sektion Attribut Sprache + Import

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#244]
Auf der Sektion wird ein Attribut benötigt für die Sprache.

# Tech-Spec

Auf Group::Sektion sowie Group::Ortsgruppe:

- Neues mounted_attr, :language, enum: DE, FR, IT, default: DE
- Sicherstellen das dieses Attribut auch im JSON:API abgerufen werden kann /api/groups/:id, spec!

# ToDo

- [x] Attribut auf Sektion erstellen
- [x] Anpassen Sektionen Import sodass Sprache abgefüllt wird (Source Feld Export-File: Sprachcode)
- [x] manuell Testen

**Comment by sykesonrocks** [comment]
@mtnstar neben der Sprache sehe ich im Tab "Sektions Attribute" weitere Felder, die notwendig sind:
- Bezeichnung auf Mitgliederausweis: Freitextfeld/String
- Anzahl Jahre für Befreiung: Freitextfeld/Integer
- Reduktion Sektionsbeitrag: Freitextfeld/Dezimal
- Ehrenmitglied zulässig: Drop-Down oder Radio Button/Boolean
- Begünstigte zulässig: Drop-Down oder Radio Button/Boolean
- Art Ehrenmitglied: Drop-Down oder Radio Button (mögliche Werte: "beides erlassen/Les deux parts remises", "Sektionsanteil erl./Part de la section remise", "ZV-Beitrag erl./Part de la cotisation au CC remise")
- Art Begünstigte: Drop-Down oder Radio Button (mögliche Werte: "beides erlassen/Les deux parts remises", "Sektionsanteil erl./Part de la section remise", "ZV-Beitrag erl./Part de la cotisation au CC remise")
--> Diese Sektionsangaben sind im Import-File ebenfalls enthalten, siehe "Sektion_Export_20230629.xlsx" unter https://saccas.atlassian.net/wiki/spaces/RDIE/pages/3883040775/Datenmigrationskonzept#Export/Import-Dateien

Weiter wurde im KVS-Projekt diskutiert, ob man auf dem Top-Layer (SAC/CAS) und auf der Sektion verschiedene Kontaktpersonen für unterschiedliche Themenbereiche anbieten sollte - dies insbesondere im Hinblick auf die Zustellung von E-Mails. Eine Kursbuchung soll z.B. in Form einer E-Mail auch der Kursadministration zugestellt werden. Der Empfänger dieser E-Mail würde Hitobito mit dieser Erweiterung aus der "Gruppenkarte" ablesen (z.B. Kontakt für Kurswesen: alpin@sac-cas.ch). Im Hinblick auf das TVS Projekt würde es ebenfalls Sinn machen, solche Kontakte auf der Sektionskarte definieren zu können.
