### ISSUE TITLE
EVENTS: Kursstatus anpassen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#245]
Die possible_states eines Event::Course werden im SAC Wagon auf folgende Werte und Labels geändert:

* created (Entwurf)
* application_open (Publiziert)
* application_paused (Anmeldung pausiert)
* application_closed (Anmeldung abgeschlossen)
* assignment_closed (Zuteilung abgeschlossen)
* ready (Bereit zur Durchführung)
* canceled (Abgesagt)
* closed (Abgeschlossen)

**Comment by sykesonrocks** [comment]
Ich gehe davon aus, dass das spezifizierte Statuskonzept auch für Paarkurse gilt. Ich habe verstanden, dass wir in HIT nur 1x den Kurs anlegen müssen. Im Gegensatz zu NAV hat man in HIT die Möglichkeit mehrere Zeiträume zu definieren:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/9e2e4947-9342-483a-af8c-b6a2ca29216d)

Frage: Durchläuft dann dieser Kurs den Status "Bereit zur Durchführung" einmal oder zwei mal (1x für Teil 1 und 1x für Teil 2)?

**Comment by codez** [comment]
Bei Kursen mit mehreren Daten wird der Status nur einmal durchlaufen.

**Comment by sykesonrocks** [comment]
Die possible_states eines Event::Course wurden im SAC Wagon auf die spezifizierten Werte und Labels geändert.
