### ISSUE TITLE
EVENTS: Aside bei Kursanmeldung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#246]
Der Anmeldeprozess für einen Kurs (nicht für reguläre Events) soll im SAC Wagon um zwei Asides auf der rechten Seite erweitert werden, welche in jedem Schritt angezeigt werden.

_Kostenübersicht_

![image](https://github.com/hitobito/hitobito_sac_cas/assets/271590/bdb05098-1449-489e-90f5-7313dde7d611)

Der obige Screenshot ist aus der heutigen SAC Website. Neu steht nur noch der Titel "Zusammenfassung" und die Tabelle mit der Kostenübersicht. Anstelle der Kursbezeichnung, Daten, Ort und Sprache steht nur "Kurskosten".

Falls eine Subvention beantragt wurde, erscheint diese als zusätzliche Zeile "- Subvention" (siehe #249).

Annulationskosten würden ebenfalls wie im Screenshot als eigene Zeile aufgelistet, kommen aber erst später.

Zuunterst steht eine Total Zeile.

Die kann vorerst mit statischen Beträgen implementiert werden, die Preisberechnung erfolgt später. Siehe für Styling auch SelfRegistration::FeeComponent

_Fragen zur Anmeldung_

![image](https://github.com/hitobito/hitobito_sac_cas/assets/271590/560e1685-f580-455d-9d88-2d8d0986426e)

Der Inhalt ist identische mit den Screenshot und vorerst statisch.
Siehe für Styling auch SelfRegistration::InfoComponent

**Comment by sykesonrocks** [comment]
Ich sehe die Aside-Komponente im Kursregistrierungsformular auf der rechten Seite:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/03f57a36-d61e-47ad-947f-bcbb393fc0ce)
Ich verstehe die Implementierung so, dass es hartcodiert ist (der Preis, die Rabattierung und die Gesamtkosten) und dass noch keine dynamische Preisberechnung stattfindet. Da es in diesem Ticket rein um die Darstellung des Asides handelt (und nicht zusätzlich um die dynamische Preisberechnung), kann dieses Ticket geschlossen werden.
