### ISSUE TITLE
EVENTS: Anmeldewizard Kontaktangaben

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#247]
Im SAC Wagon wird das Partial `event/participation_contact_datas/_form` komplett überschrieben und mit dem selben Layout und Feldern ersetzt, wie sie bei der Selbstregistrierung verwendet werden. Die Felder sollen vorausgefüllt sein. Dieses soll möglichst mit dem bestehenden Controller funktionieren.

Die beiden Attribute `required_contact_attrs` und `hidden_contact_attrs` werden im SAC Wagon aus den `used_attributes`  des Events und des Kurses entfernt. Im Core braucht es im Event Form Partial noch eine zusätzliche Prüfung, dass das `contact_attr_fields` Partial und das zugehörige Tab nur angezeigt werden, wenn eines dieser beiden Attribute `used?` ist.

Die `Event::ParticipationContactData` wird im SAC Wagon entsprechend angepasst, dass nur noch die verwendeten Attibute in `contact_attrs` enthalten sind und alle ebenfalls in den `mandatory_contact_attr` enthalten sind.

Zuunterst erscheint zusätzlich der folgende Hinweis: "Bitte beachte, dass die hier eingegebenen Anpassungen in dein Profil übernommen werden.“

**Comment by codez** [comment]
@sykesonrocks Wir haben die Möglichkeit, Attribute komplett aus dieser [Ansicht](https://sac-cas.puzzle.ch/de/groups/1/events/3/edit#contact_attrs) zu entfernen, so dass diese auch nicht mehr konfigurierbar sind. Ist es allenfalls gewünscht, einige der neu als nicht angezeigten (hidden) Attribute ganz zu entfernen? Falls ja, welche?

**Comment by carlobeltrame** [comment]
Zur AHV-Nummer auf Anmeldung statt Person siehe auch https://github.com/hitobito/hitobito/issues/2162, wo die Youth-Community sich gerade sammelt um das umzusetzen. Allenfalls kann der SAC sich da auch einbringen, oder zumindest die Implementation für Wiederverwendung abgestimmt werden.

**Comment by tobiasstern** [comment]
Platzhalter für Testing-Feedback

- Formular abschicken ohne Geburtsdatum löst keine Fehlermeldung aus

**Comment by amaierhofer** [comment]
@tobiasstern 30161d4be2975b6d65a1aa468964f2ae4e968fe1 wird jetzt auch die Telefonnummer validiert

**Comment by tobiasstern** [comment]
Retest erfolgreich
