### ISSUE TITLE
EVENTS: Anmeldewizard - Neuer Schritt Versicherungskosten

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#248]
Im Anmeldewizard von Kursen wird im SAC Wagon vor dem Schritt "Anmeldung" wird ein Schritt "Versicherungskosten" hinzugefügt.

Die Seite ist wie folgt aufgebaut:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/271590/aa678b03-d20c-4e51-aaf0-757cdec5177c)

Titel und Infobox sind wie auf dem Screenshot.  Der Link zu den AGBs ist möglichst im übersetzten Text enthalten. Die verlinkte Datei ist öffentlich auf der SAC Webseite und nicht in hitobito enthalten.

Der Text ist nun "Ich möchte für diesen Kurs eine Annulationskostenversicherung beantragen"

Die Tabelle mit dem Kurs fällt weg, anstelle kommt direkt eine Checkbox mit dem Label "Annulationskostenversicherung für CHF 75 hinzufügen"

Wenn die Checkbox geklickt wird, erscheint im Aside mit der Kostenzusammenfassung eine weitere Zeile "+ Annulationskosten-VS   CHF 75". Der Totalbetrag wird entsprechend aktualisiert. Momentan ist der Betrag von 75.- hardcoded, dieser wird später berechnet.

Der Wert der Checkbox wird auf der Event Participation persistiert. Es braucht dazu ein neues boolean Attribut `annulation_insurance`.

**Comment by ThomasEllenberger** [comment]
Am 30.01. wurde mit Reto besprochen, dass dies nicht teil des MVP wird.
Im zuge des MVP soll lediglich im neuen Schritt "Zusammenfassung" (https://github.com/hitobito/hitobito_sac_cas/issues/251) ein Verweis eingeblendet werden: "Versicherung ist Sache der Teilnehmenden"

**Comment by sykesonrocks** [comment]
@tobiasstern ich bitte dich das Jira-Ticket https://saccas.atlassian.net/browse/HIT-255 zu finalisieren (ich habe es dir soeben zugewiesen, bitte berücksichtige auch mein Kommentar in Jira). Danach bitte dieses Ticket aktualisieren (lassen) und in die Umsetzung geben - danke dir!
