### ISSUE TITLE
EVENTS: Anmeldewizard - Neuer Schritt Subventionsbeitrag

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#249]
Im Anmeldewizard von Kursen wird im SAC Wagon als dritter Schritt "Subventionsbeitrag" hinzugefügt.

Dieser Schritt wird nur bei Usern mit der Rolle `SacCas::Role::MitgliedHauptsektion` angezeigt. Später wird eine weitere Bedingung dazu kommen (subventionierte Preisgruppe muss für Kurs konfiguriert sein).

Der Aufbau ist wie folgt:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/271590/2637e975-90ca-48dd-a86c-72a31bafcdb5)

Anstelle der Tabelle mit dem Kurs erscheint nur eine Checkbox "Subventionierten Preis von CHF xxx beantragen"

Wenn die Checkbox ausgewählt wird, wird der Kurspreis im Aside ersetzt. Momentan ist der Betrag von 620.- hardcoded, dieser wird später berechnet.

Der Link zum Subventionsantrag ist möglichst im übersetzten Text enthalten. Die verlinkte Datei ist öffentlich auf der SAC Webseite und nicht in hitobito enthalten: https://www.sac-cas.ch/fileadmin/Ausbildung_und_Wissen/Kurse/Subventionsantrag/2023_Subventionsantrag_de.pdf

Der Wert der Checkbox wird auf der Event Participation persistiert. Es braucht dazu ein neues boolean Attribut `subsidy`.

**Comment by sykesonrocks** [comment]
@codez _Dieser Schritt wird nur bei Usern mit der Rolle SacCas::Role::MitgliedHauptsektion angezeigt._
+
der Kurs muss mit der entsprechenden Debitorenpreisgruppe (z.B. SUBV) konfiguriert sein.

**Comment by tobiasstern** [comment]
Hi @TheWalkingLeek wie kann ich das testen, gibt es einen subventionierten Kurs im Testsystem?

**Comment by codez** [comment]
@tobiasstern Siehe oben: "Dieser Schritt wird nur bei Usern mit der Rolle SacCas::Role::MitgliedHauptsektion angezeigt." Es wird momentan bei allen Kursen angezeigt, wenn der User die entsprechende Rolle hat.

**Comment by tobiasstern** [comment]
Danke!

Zwei kleine Ergänzungen bitte:

- Im ersten Text noch ein Komma nach "Möglichkeit" einfügen.
- Den Link auf das Formular in einem neuen Fenster öffnen statt im selben tag laden. --> Weil, wenn ich jetzt drauf klicke, dann Browser-"zurück" zum Form, bin ich in Schritt 2, statt wie vorher in Schritt 3. Und die bereits eingegebenen Daten in Schritt 2 sind verloren.

**Comment by tobiasstern** [comment]
Test erfolgreich, ticket wird geschlossen.
