### ISSUE TITLE
EVENTS: Anmeldewizard - Schritt Anmeldung umbenennen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#250]
Im Anmeldewizard für Kurse wird im SAC Wagon der Schritt "Anmeldung" umbenannt zu "Zusatzdaten". 

Das Feld "Bemerkungen (Allgemeines, ..)" soll umbenannt werden zu "Kommentar"

**Comment by tobiasstern** [comment]
Hi @TheWalkingLeek bei mir sind diese Änderungen nicht vorhanden. Muss ich noch warten mit testen?

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/eccd12b6-1302-4be7-aaba-012c29987142)

**Comment by codez** [comment]
@tobiasstern Das wird morgen auf der Integration sein. Das Ticket war noch nicht dir oder Stefan zugewiesen, daher war es noch nicht im Hauptbranch.

**Comment by tobiasstern** [comment]
Hi @TheWalkingLeek 

Das Feld Bemerkungen soll gemäss Spez. "Kommentar" heissen:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/89557921-e959-4bbc-9368-cba98071c66a)

Bitte noch anpassen.

**Comment by tobiasstern** [comment]
Passt, danke!
