### ISSUE TITLE
EVENTS: Anmeldewizard - Neuer Schritt Zusammenfassung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#251]
Im SAC Wagon wird im Anmeldewizard für Kurse ein neuer letzter Schritt "Zusammenfassung" erstellt.

Links stehen nochmals die relevanten Angaben zum Kurs:

> Kursname (Kursnummer)
> Daten (von - bis, Ort)

Danach erscheint ein weiterer Abschnitt "Kontakdaten". Dort werden alle Kontaktdaten vom ersten Schritt nochmals angezeigt. z.B.:

> Herr
> **Pascal Zumkehr**
> 
> Belpstrasse 37
> 3007 Bern
> CH
>
> Geburtstag: 01.01.1970
> Telefon: +41313816222
> E-Mail: zumkehr@puzzle.ch

Danach folgt ein Abschnitt "Zusatzdaten" werden die Kursfragen und Antworten sowie der Kommentar angezeigt:

> *Frage 1*
> Antwort 1
> *Frage 2*
> Antwort 2
> *Kommentar*
> Mein Kommentar

Im letzten Abschnitt wird ein blauer Hinweiskasten mit dem folgenden Inhalt angezeigt:

> Der Abschluss einer Annullationskostenversicherung wird empfohlen. Folgende Rücktrittskosten würden bei Abmeldung vor Kursbeginn durch den Kunden/die Kundin getragen:
> 
> 30 - 20 Tage: 50 % des Preises
> 19 - 10 Tage: 75 % des Preises
> 09 - 00 Tage: 100 % des Preises

Im Aside rechts ist weiterhin die Kostenübersicht zu sehen.

**Comment by codez** [comment]
@sykesonrocks kannst du bitte den Text für die SAC Mitglieder oben noch einfügen?

**Comment by sykesonrocks** [comment]
@codez Done

Folgender Text erscheint als nicht-SAC-Mitglied:
Schliesse nach der Anmeldung innerhalb von 7 Tagen eine SAC-Mitgliedschaft ab und profitiere von einem SAC-Mitgliederrabatt in Höhe von bis zu 120 CHF.
Können wir dies garantieren? Evt. kurz mit @mtnstar abklären (betrifft CRM, KVS, ERP). Nach erfolgtem Onboarding des Mitglieds müsste diese Kurs-Faktura im Nachhinein angepasst werden (Gutschrift?). Wenn zuerst das Onboarding gemacht werden muss, dann müsste man diesen Text anpassen.

**Comment by codez** [comment]
@sykesonrocks Die Hinweistexte für SAC Mitglieder und Nichtmitglieder sind nicht mehr Teil des Jira Tickets. Ich habe sie hier entsprechend entfernt.

**Comment by tobiasstern** [comment]
Testergebnis:

- Es fehlt der Ort des Kurses
- Beim Mitglied wird "Mann" angezeigt statt "Herr"
- Bei den Zusatzangaben sollen die Fragen jeweils Kursiv dargestellt werden, nicht fett.
- Bei der Kostentabelle bitte als Titel "Kostenübersicht" statt "Zusammenfassung" nehmen.
- Bei Geldbeträgen ist es üblich, die Währung vor dem Betrag zu stellen, also "CHF 1'300.00". Bitte in der Kostenübersicht anpassen.

@TheWalkingLeek kannst du dies bitte noch beheben?

**Comment by tobiasstern** [comment]
Wenn in den Zusatzangaben nichts angegeben wird, dann wird dies in der Zusammenfassung unterschiedlich dargestellt, siehe Bild:

![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/cd788062-d728-4611-9837-43d5fe821052)

Es gibt "(nicht beantwortet)", "-" und "". Kann man das vereinheitlichen, sodass auch bei den beiden Notfallkontakt-Fragen das "(nicht beantwortet)" kommt?

**Comment by tobiasstern** [comment]
Angaben werden jetzt einheitlich dargestellt:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/2921f82d-7a93-4c4e-9729-e2954c8a0dbd)

Und CHF steht jetzt vor dem Betrag.

Danke und -> closed
