### ISSUE TITLE
EVENTS: Anmeldewizard - Zusammenfassung mit AGB

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#252]
Im SAC Wagon erscheint für alle Kurse, welche auf der Root Ebene angehängt sind, im Anmeldewizard auf dem Schritt "Zusammenfassung" zuunterst zwei Checkboxen:

- "Ich bestätige dass ich mindestens 18 Jahre als bin …." (gleicher Text wie bei Selbstregistrierung)
- "Ja, ich erkläre mich mit den [AGB](https://www.sac-cas.ch/fileadmin/Ausbildung_und_Wissen/Kurse/AGB-Kurse/SAC_Ausbildung-Touren_2023_AGB_DE.pdf) einverstanden." 

Der Link ist Teil des übersetzten statischen Textes und zeigt auf ein PDF auf der SAC Webseite, ausserhalb von hitobito.

Nur wenn diese beiden Checkboen angewählt wurde, kann die Anmeldung abgeschickt werden, ansonsten erscheint ein Validierungsfehler. Die Werte müssen nicht auf der Anmeldung persistiert werden.

Kurse auf anderen Ebenen haben diese Checkboxen nicht.

**Comment by sykesonrocks** [comment]
Tip top

**Comment by tobiasstern** [comment]
@TheWalkingLeek scheint grösstenteils korrekt implementiert. Die beiden Checkboxen sind da.

Mir ist jedoch aufgefallen, dass ich die gelbe Meldung hier erhalte, siehe Bild. Dies ist ein Fehler, diese Meldung darf nicht erscheinen, wenn ich mich noch nicht angemeldet habe.

![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/aca810f4-0483-4357-97f1-970ea9df801b)


Kannst du das bitte beheben?

**Comment by codez** [comment]
Wird mit https://github.com/hitobito/hitobito/pull/2593 gefixt

**Comment by tobiasstern** [comment]
Klappt! -> Close
