### ISSUE TITLE
EVENTS: Ausbildungstage

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#256]
Qualifikationsart hat neu ein Feld "Erforderliche Ausbildungstage für Verlängerung" / `required_training_days` (decimal, precision: 5, scale: 2, nullable).  Zusätzlicher Hilfetext beim Input: "Mindestens so viele Ausbildungstage sind während der Gültigkeitsdauer zu absolvieren, um bestehende Qualifikationen zu verlängern. Diese können auch über mehrere Kurse aufgeteilt werden. Leer lassen, um Ausbildungstage nicht zu berücksichtigen und Qualifikationen unmittelbar bei jedem entsprechenden Kursbesuch zu verlängern."

Kurs hat neu ein Feld "Ausbildungstage" / `training_days` (decimal, precision: 5, scale: 2, nullable). Dieses ist bereits im Youth Wagon vorhanden und soll in den Core aufgenommen/verschoben werden, inklusive der Anzeige auf der Infoseite des Events und im Formular. Letzteres wird somit im Youth Wagon entfernt. Übrige Funktionalität, welche bisher im Youth Wagon ist und dieses Feld betrifft, bleibt dort.

**Comment by codez** [comment]
@ThomasEllenberger / @mtnstar seht ihr das im Core, Youth, oder Sac? Wahrscheinlich könnte das für alle interessant sein (Logik folgt in weitern Tickets).

**Comment by mtnstar** [comment]
aus technischer Sicht sehe ich keine Probleme wenn wir das in den Core verschieben.
Fachlich kann vermutlich @ThomasEllenberger das besser beurteilen

**Comment by ThomasEllenberger** [comment]
Wir hatten auch schon Anfragen welche in diese Richtung giengen, denk desshalb dass das im Core umgesetzt werden kann.
Zwingend notwendig ist dabei sicher der Hilfetext.

**Comment by codez** [comment]
Stellt sich noch die Frage, ob wir #261, falls wir das bauen, dann auch in den Core nehmen wollen?

**Comment by sykesonrocks** [comment]
@codez Nachfolgend meine Testergebnisse.

- Qualifikationsart hat neu ein Feld "Erforderliche Ausbildungstage für Verlängerung" und der Hilfetext wird wie oben spezifiziert dargestellt. Somit Ok.
- Das neue Feld auf dem Kurs, "Ausbildungstage", kann ich aktuell nicht testen. Wenn ich versuche einen neuen Kurs anzulegen, erhalte ich folgende Fehlermeldung:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/de1f4dc4-fce3-4eeb-a06e-b9b0c4131f2b)

**Comment by codez** [comment]
@sykesonrocks Jetzt sollte alles funktionieren

**Comment by sykesonrocks** [comment]
@codez Danke. Habe es soeben getestet und sehe auf dem Kurs das neu eingeführte Feld "Ausbildungstage", somit OK.
