### ISSUE TITLE
EVENTS: Ausbildungstage bei Qualifikationsverlängerungen berücksichtigen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#257]
Im Event::Qualifier im Core wird folgende Anpassung vorgenommen:

Hat eine zu verlängernde Qualifikationsart einen Wert im Feld "Erforderliche Ausbildungstage" / `required_training_days` gesetzt, wird eine bestehende Qualifikation nicht unmittelbar verängert, sondern erst nach der folgenden Prüfung:

1. Vergangene Kurse, an welchen die Person teilgenommen hat, werden wie folgt ausgewählt:
    * Teilnahme ist als `qualified` markiert
    * Die Kursart des Kurses verlängert die entsprechende Qualifikationsart
    * Qualifikationsdatum des Kurses (siehe `Event::Course#qualification_date)` liegt in der Zeitspanne vom Qualifikationsdatum des aktuellen Kurses minus die Gültigkeitsjahre der Qualifikationsart
2. Die Ausbildungstage (`training_days`) dieser Kurse werden summiert. Dies erfolgt chronologisch rückwärts (nach Qualifikationsdatum) um einen Kurs nach dem anderen. Für nach jedem Kurs wird 3.) überprüft und abgebrochen, falls die Bedingung erfüllt ist.
3. Falls die Summe >= der erforderlichen Ausbildungstage der Qualifikationsart sind, wird die Qualifikation verlängert. Das heisst, es wird eine neue Qualifikation mit Startdatum = Qualifikationsdatum des momentanen Kurses aus 2.) erstellt. Als Ursprung der Qualifikation wird allerdings der Name des Kurses eingetragen, für welche der Qualifier aufgerufen wurde.
4. Ansonsten erfolgt keine Veränderung an den Qualifikationen.

Um das Auffinden des zugehörigen Kurses zu einer Qualifikation etwas einfacher zu gestalten, wird auf der Qualifikation ein zusätzliches Attribut `qualified_at` (Date, nullable) hinzugefügt. Dieses erhält in jedem Fall das Qualifikationsdatum des akutellen Kurses (auch bei neu vergebenen Qualis oder Arten ohne Ausbildungstage). In der Migration wird bei allen bestehenden Qualis `qualified_at` auf `start_at` gesetzt. Bei manuell erstellen Qualifikationen bleibt jedoch `qualified_at` künftig leer. Die `obtained` Qualifikationen prüfen neu dieses Datum anstelle von `start_at`. So können die zu löschenden Qualifikationen weiterhin einfach gefunden werden.

Wir gehen hier davon aus, dass Qualifikationen immer nur für den zuletzt besuchten Kurs noch verändert werden, ignorieren also die Auswirkungen, welche die erreichten Ausbildungstage auf nachfolgende, bereits erfasste Kurs haben können. Weiters folgt in #262

**Comment by sykesonrocks** [comment]
Sieht gut aus, aktuell in Verifikation beim Fach. Siehe auch mein Kommentar unter https://github.com/hitobito/hitobito_sac_cas/issues/257.
