### ISSUE TITLE
EVENTS: Qualifikationen von Tourenchef bearbeitbar

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#258]
Im SAC Wagon gibt es für Qualifikationsarten ein neues Attribut "Von Tourenchef bearbeitbar" / `tourenchef_may_edit` (boolean, default false)

Die QualificationAbility wird im Wagon entsprechend angepasst, dass alle Tourenchef Rollen (siehe Group::SektionsTourenkommission) eine Qualifikation einer Person in ihrer Gruppe erstellen und löschen können, wenn die Qualifikationsart das entsprechende Flag gesetzt hat. 

Im QualificationsController muss die Liste der verfügbaren Qualifikationsarten für Tourenchefs entsprechend zusätzlich gefiltert werden.

**Comment by sykesonrocks** [comment]
@codez @TheWalkingLeek 

Gemäss Referenztabelle darf ein Tourenchef nur Qualifikationen der Arten "Bergführer/In SBV", "Bikeleiter/In" und "Wanderleiter/In" erfassen:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/c9609a6a-15c8-4b4b-b9dc-191eafa1e2d1)

Wenn ich ein Tourenchef imitiere (bspw. https://sac-cas.puzzle.ch/de/groups/1239/people/177849), stelle ich fest, dass die Drop-Down-Liste "Qualifikation" nicht eingeschränkt angezeigt wird (sprich das Flag "Vom Tourenchef bearbeitbar" wird ignoriert). Ich kann z.B. Qualifikationen basierend auf "SAC Tourenleiter/in 1 Sommer" erfassen. Hängt es allenfalls mit der kombinierten Rollenzuweisung zusammen (Tourenchef + Mitgliederverwaltung)?

**Comment by codez** [comment]
Ja genau. Berechtigungen sind immer kummulativ. Mit der Rolle Mitgliederverwaltung können alle Qualifikationen erstellt werden.
