### ISSUE TITLE
EVENTS: Qualifikationen Bis Datum bearbeitbar

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#259]
Neu soll im SAC Wagon beim Erstellen einer Qualifikation das Enddatum gesetzt werden können, wenn die ausgewählte Qualifikationsart eine unbeschränkte Gültigkeit hat. Falls eine solche Qualifikationsart ausgwählt wird, wird das Feld "Bis" eingeblendet, wo ein beliebiges Datum eingegeben werden kann. Bei anderen Qualifikationsarten wird das Feld nicht angezeigt.

**Comment by codez** [comment]
@sykesonrocks Ist das wirklich notwendig? Wie erwähnt ist das bisher bei keiner anderen Organisation möglich, weil dies auch eine grosse Fehlerquelle darstellen kann. Der Use Case, dass Tourenchefs an sich unbeschränkte Qualifikationen "beenden" können, wäre auch dadurch abbildbar, dass die Qualifikation einfach gelöscht wird. Diese Aktion ist im Log der Person sichtbar.

**Comment by sykesonrocks** [comment]
@codez Ich habe verstanden, dass diese Frage nur die Qualifikationen betrifft und (noch) nicht die Bearbeitung der Ausbildungshistory. Ich werde den Punkt intern klären und dir nächste Woche eine Rückmeldung geben. Im Jahr 2023 gab es 1'090 solcher Mutationen.

**Comment by sykesonrocks** [comment]
@codez Nachfolgend meine Testergebnisse.

Alles OK, ausser folgender Punkt: wenn ich das bis-Datum 31.12.9999 eingebe und versuche zu speichern, erhalte ich folgende Fehlermeldung: "Bis muss vor 31.12.9999 sein". Zudem ist danach das Bis-Feld nicht mehr sichtbar. Um den Fehler zu reproduzieren, wie folgt vorgehen:

- Schritt 1: Bis-Datum 31.12.9999 eingeben
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/e16b7d9d-15d7-42fb-b27e-490e116c5582)

- Schritt 2: Fehlermeldung ohne bis-Datumsfeld
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/39a54696-483f-4ebf-ad62-80ec10a647ec)

Falls man dieses Systemverhalten mit ein paar Stunden Aufwand optimieren kann, gerne, ansonsten belassen wir es so wie es ist resp. instruieren die Nutzer, dass wenn es unbeschränkt gültig sein soll, das Feld leer gelassen werden muss.

**Comment by sykesonrocks** [comment]
Ich kann bestätigen, dass das Bis-Feld korrekt ein- und ausgeblendet wird, abhängig davon, welche Qualifikation(sart) ausgewählt wird.
