### ISSUE TITLE
EVENTS: E-Mails bevor Qualifikation abläuft

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#260]
Im SAC Wagon soll ein jährlicher Job am 31. 12. nachts prüfen, welche Qualifikationen ablaufen und entsprechende E-Mails verschicken. Die Texte der E-Mails sind als "Texte" bearbeitbar.

Dabei werden alle Qualifikationen einer Person, deren Qualiarten eine Gültigkeitsdauer haben, gemeinsam berücksichtigt. Erst wenn die letzte all dieser Qualifikationen vor dem Ablaufen steht, wird eine entsprechende Nachricht gesendet. Wenn also nur eine Quali abläuft, jedoch noch eine andere mit einer anderen Qualiart länger gültig bleibt, wird keine Nachricht verschickt.

Folgende Emails werden verschickt: 

* 2 Jahre bevor eine Qualifikation abläuft, bekommt die Person eine Nachricht: 
    “Liebe(r) Tourenleiter(in), in 2 Jahren läuft deine TL-Anerkennung ab. Plane rechtzeitig deine Fortbildungskurse in Absprache mit deinem(r) Tourenchef(in)."

* 1 Jahr vor dem Ablauf bekommt die Person eine weitere Nachricht: 
    “Liebe(r) Tourenleiter(in), per Ende Jahr läuft deine TL-Anerkennung ab. Absolviere bitte die nötigen Fortbildungstage, damit du per Ende Jahr nicht sistiert wirst."

* Am Tag des Ablaufs bekommt die Person diese Nachricht:
    “Liebe(r) Tourenleiter(in), deine TL-Anerkennung ist ab morgen sistiert. Du darfst keine Touren für deine Sektion mehr leiten. Bitte absolviere die nötigen Fortbildungstage, um wieder als aktive(r) Leiter(in) registriert sein zu können."

# Tech-Spec

- https://github.com/hitobito/hitobito_pbs/blob/master/db/seeds/custom_contents.rb
- Beispiel für einen Job https://github.com/hitobito/hitobito_pbs/blob/master/app/jobs/alumni_invitations_job.rb

# Todo

**Comment by codez** [comment]
Da die einen Mails nur am 31.12. verschickt werden, kann dieses Feature kaum getestet werden. Deshalb werden temporär täglich alle E-Mails verschickt. Sobald das Ticket abgenommen ist, wird der entsprechende Kommentar wieder entfernt.

**Comment by hunchr** [comment]
@codez wann können wir den kommentar entfernen? wurde dies bereits getestet?

**Comment by codez** [comment]
Habe @sykesonrocks gebeten, mir mitzuteilen, wann die Tests abgeschlossen sind. Bis dahin lassen wir es noch so drin.
