### ISSUE TITLE
EVENTS: Externe Ausbildungen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#261]
Es gibt im SAC Wagon ein neues Model "Externe Ausbildung" / `ExternalTraining`. Dieses ist notwendig, um extern absolvierte Ausbildungen und Fortbildungsstunden zu erfassen. 

Das Model hat folgende Attribute:

* Person / `person_id` (not null)
* Kursart / `event_kind_id` (not null)
* Name / `name` (string, not null)
* Anbieter / `provider` (string)
* Startdatum / `start_at` (date, not null)
* Enddatum / `finish_at` (date, not null)
* Ausbildungstage / `training_days` (decimal, scale 1, not null)
* Link / `link` (string)
* Bemerkung / `remarks` (string)

Die Externen Ausbildungen werden im bestehenden Tab "Mitgliedschaften/Verlauf" zuunterst aufgelistet. Dazu ist eine group_full, group_and _below_full, layer_read oder layer_and_below_read Berechtigung notwendig. Neueste Ausbildungen erscheinen zuoberst.

Ausbildungen können dort auch erstellt und gelöscht werden. Dazu ist zusätzlich eine Berechtigung group_full oder group_and_below_full, layer_full oder layer_and_below_full notwendig.

Das Bearbeiten von externen Ausbildungen ist nicht möglich, da beim Erstellen und Löschen ebenfalls Qualifikationen vergeben werden (siehe #262)

**Comment by sykesonrocks** [comment]
@codez @amaierhofer @TheWalkingLeek 

Kursart / event_kind_id (not null) ist nullable, sollte ein Pflichtfeld sein:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/bac00245-ba8e-423a-bed6-1011fa8391c0)

**Comment by amaierhofer** [comment]
@sykesonrocks Kursart ist jetzt wie definiert ein Pflichtfeld

**Comment by sykesonrocks** [comment]
@tobiasstern @amaierhofer Ein Stern (*) fehlt (analog Name und Kursnummer):
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/41460eff-0935-4789-9b46-cf7aed49d18b)

**Comment by tobiasstern** [comment]
In diesem Ticket geht es um die Maske hier: https://sac-cas.puzzle.ch/de/groups/977/people/600203/external_trainings/new 
Der rote Stern ist da beim Feld Kursart korrekt drin. Der Screenshot von @sykesonrocks  stammt von einer Kurs-Maske wie https://sac-cas.puzzle.ch/de/groups/1/events/13/edit und dort fehlt der Stern tatsächlich.

@amaierhofer Ist das ev. ein generelles Problem mit dem Feld Kursart, dass der rote Stern überall noch hinzugefügt werden muss?

**Comment by amaierhofer** [comment]
@tobiasstern war ein grundsätzliches Problem bei Kurse, wird mit f628016096b62dfec1f5c68832165f0fe82569eb behoben.

**Comment by sykesonrocks** [comment]
@tobiasstern Ich kann bestätigen, dass der Stern (*) nun bei den externen Ausbildungen ersichtlich ist:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/2d2796bd-1675-4bac-a265-23248182cc79)

Der Stern fehlt aber bei der Kurserfassungsmaske (siehe mein Kommentar oben). Wird dieser Bug mit diesem GIT Issue gelöst? Kannst du mir das GIT Issue bitte mitteilen.

**Comment by amaierhofer** [comment]
@sykesonrocks das kommt mit dem nächtlichen Deployment und sollte morgen dann auf int ersichtlich sein.

**Comment by tobiasstern** [comment]
Konnte es testen, ist nun gelöst. -> Close
