### ISSUE TITLE
MAILING_LISTS: Labels für neue Abo Anmeldeoptionen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#273]
wir haben kurz mit UX noch über das Naming der neuen Optionen für die An/Abmeldung von Abos geredet. 

Bitte die DE-Übersetzungen anpassen:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/c33a716d-646c-4278-8e7a-e4fbd5cf0297)

# ToDo

- [x] Übersetzungen anpassen
- [x] sicherstellen das alle Specs noch sauber durchlaufen

**Comment by TheWalkingLeek** [comment]
https://github.com/hitobito/hitobito/commit/2533860205e6c3c37fd6b3bce2673ffbdf7a802b
