### ISSUE TITLE
PEOPLE: Korrespondenzsprache englisch deaktivieren

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#274]
Der SAC akzeptiert heute keine Personen mit Korrespondenzsprache englisch. Diese Sprache soll daher auf der Person im Sprachauswahl-Dropdown nicht angeboten werden.

Achtung: Die UI-Sprache englisch soll weiterhin verfügbar bleiben. Nur der speicherbare Wert auf der Person soll angepasst werden.

## TODO
- [x] Korrespondenzsprache englisch rausnehmen
- [x] Überprüfen ob noch Fixtures, Tests, Seeds, Importer oder Daten auf Integration existieren welche die Korrespondenzsprache englisch referenzieren, und gegebenenfalls beheben

**Comment by daniel-illi** [comment]
@amaierhofer ich nehme an, dieses Ticket ist versehentlich im 'closed' gelandet? Der PR ist jedenfalls noch nicht gemergt...
