### ISSUE TITLE
ROLES: Verbesserungen Mitglieder-Import

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#291]
Der Mitglieder Import wurde auf der Integrationsumgebung mit sämtlichen Mitgliederdaten angewendet. Mit diesem Ticket hier sollen diverse Verbesserungen angebracht werden.

Es werden viele Mitglieder nicht importiert: (Rollen werden nicht erstellt/assigned)

Ehrenmitglied / Begünstigt:

- Es werden etwa die Hälfte der erwarteten Ehrenmitglied / Begünstigt Rollen angelegt
- Es ist gut möglich das dies mit dem oben Beschriebenen Problem zusammenhängt

Das Reporting soll verbessert werden:
* Für jedes importierte Mitglied die erstellte resp. aktualisierte Rolle ausgeben
* Report in file schreiben, z.B. als yaml (maschinenlesbar zum Auswerten)
* Am Ende des Imports den Pfad zum Report file ausgeben
* Auswerten, dass
    - für jede row eine Rolle erstellt/aktualisiert wird
    - nicht dieselbe Rolle für mehrere rows aktualisiert wird

Ziel dieses Tickets: Es werden alle Mitglieder-Rollen für die im Export-File vorhandenen Mitglieder erstellt

# Tech-Spec

https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/import/sektion/memberships_importer.rb

- Beispiele von nicht richtig importierten Einträgen: https://files.puzzle.ch/apps/files/files?dir=/swe/projects/SAC_SchweizerAlpenClub/Hitobito/7_Verschiedenes/navision-exporte/mitglieder-import&openfile=6074039

# ToDo

**Comment by sykesonrocks** [comment]
- Vereinzelte Funktionäre wurden nicht als Mitglied importiert 
 (siehe z.B. Jean-Christophe Rossand) - aus dem Error Report kann hierzu nichts entnommen werden.
- Vereinzelte Funktionäre wurden ohne E-Mail Adresse importiert 
 (siehe z.B. Carole Mäder) - aus dem Error Report kann hierzu nichts 
entnommen werden.
- E-Mail-Adresse von Mieke Bumann wurde abgeschnitten importiert: 
azur@saas-fee.ch anstatt mieke@azur-saas-fee.ch - aus dem Error Report kann hierzu nichts entnommen werden.

**Comment by mtnstar** [comment]
wird mit #726 umgesetzt
