### ISSUE TITLE
PEOPLE: Error Personen-Export

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#292]
### Aktuelles Verhalten

Unter Sektion > Mitglieder einen Export aller Personen starten. (beliebige Sektion)

Folgender Fehler tritt auf: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/65531/?environment=integration

### Gewünschtes Verhalten

Der Export kann ohne Probleme ausgeführt werden

### Schritte zu reproduzieren

siehe oben

### ToDos

- [ ] Spec erstellen der sicherstellt das dieser Export beim SAC Wagon funktioniert

**Comment by sykesonrocks** [comment]
@mtnstar Ich kann dies nicht testen, ich kann das Migrationsskript nicht ausführen :)
