### ISSUE TITLE
PEOPLE: Navigation im Selbstregistrierungsformular

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#298]
### Aktuelles Verhalten

Wenn man das Selbstregistrierungsformular (in einer Neuanmeldungen-Gruppe) ausfüllt und bis zum vierten Schritt "Zusatzdaten" gegangen ist, dann zwei Mal "Zurück" und ein Mal "Weiter" klickt, dann ist man wieder auf Schritt 4.

- Auf den Schritt 1 kommt man mit Zurück auch nicht mehr zurück

### Gewünschtes Verhalten

Vom Schritt 4 zwei Schritte zurück und einer nach vorne müsste bei Schritt 3 landen.

### Schritte zu reproduzieren

Siehe oben (Report von Stefan)

### Wann ist der Fehler aufgetreten?

7.2.2024

### hitobito version

latest

### Organisation

SAC

**Comment by mtnstar** [comment]
dieser Bug besteht immer noch ... 19.02.2024, 11:32
96dc254c531d40863f75774d8b86e18b8731660b

**Comment by mtnstar** [comment]
@sykesonrocks diese Changes waren gestern noch nicht auf der Integration.
wie bereits erklärt, wenn Tickets geschlossen werden, dann dauert es bis zum nächsten Tag bis die Änderungen auf der Integrationsumgebung vorhanden sind.

**Comment by sykesonrocks** [comment]
@mtnstar kannst du mir das Ticket bitte zuweisen, sobald es testbereit ist - danke.

**Comment by daniel-illi** [comment]
Auf Step 2 gibt es aktuell noch keinen "Zurück" Link.
@carlobeltrame sollte noch eingefügt werden?

**Comment by daniel-illi** [comment]
@sykesonrocks das Navigieren funktioniert nun wie es soll.

**Comment by daniel-illi** [comment]
@sykesonrocks wir haben momentan noch ein Problem mit dem Deployen auf Integration, drum kann das noch nicht getestet werden. Ich assigne dir das Ticket sobald es auf Integration bereit ist.

**Comment by sykesonrocks** [comment]
@mtnstar Ich konnte das Verhalten nicht reproduzieren, somit ok.

**Comment by mtnstar** [comment]
> @mtnstar Ich konnte das oben festgehaltene fehlerhafte Verhalten nicht reproduzieren, somit ok.
> 
> Jedoch ist mir gelungen, in ein Zustand zu gelangen, in der ich im Schritt 3 (Familienmitglieder) nicht mehr weiterkomme, auch wenn ich den Knopf "Weiter als Familienmitgliedschaft" tätige: ![image](https://private-user-images.githubusercontent.com/132900428/313200878-39184a58-26be-47a4-a611-e62aa6c3aa4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjgzNDEsIm5iZiI6MTcxMDc2ODA0MSwicGF0aCI6Ii8xMzI5MDA0MjgvMzEzMjAwODc4LTM5MTg0YTU4LTI2YmUtNDdhNC1hNjExLWU2MmFhNmMzYWE0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMzIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODdiNTBiZTBlZjc1MGMwNTMzNTk5NjY5ZjYyZThkODc5Yzg5MGQ0OTMxMWQ0NTcyMWEwMDk3OTA5YjhhMWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GNGzvQed1auwB1-O-Ak1tHGR3yj3uuNsySzGgkCHVzA) Um den Fehler zu reproduzieren, wie folgt vorgehen:
> 
>     1. Im Schritt 1 E-Mail Adresse eingeben
> 
>     2. Auf "Weiter" klicken
> 
>     3. Im Schritt 2 Personendaten eingeben
> 
>     4. Auf "Weiter" klicken
> 
>     5. Im Schritt 3 Familienmitglieder hinzufügen
> 
>     6. Auf "Weiter als Familienmitgliedschaft" klicken
> 
>     7. Auf "Zurück" klicken
> 
>     8. Auf "Zurück" klicken
> 
>     9. Auf "Weiter" klicken
> 
>     10. Auf "Weiter als Familienmitgliedschaft" klicken
> 
>     11. Auf "Zurück" klicken
> 
>     12. Auf "Weiter als Familienmitgliedschaft" klicken --> passiert nichts mehr

das Verhalten konnte ich gerade heute Morgen auch nachvollziehen und @daniel-illi ist das bereits am fixen. Sollte mit der Umsetzung von #284 gefixt sein.

**Comment by daniel-illi** [comment]
@sykesonrocks dies ist inzwischen auf Integration gefixt
