### ISSUE TITLE
PEOPLE: Selbstregistrierungsformular Land Schweiz vorauswählen

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#299]
Als Person die sich für eine Mitgliedschaft registrieren will
möchte ich das Land nicht extra auswählen müssen wenn ich in der Schweiz wohne,
um eine niederschwelligere UX bei der Registrierung zu haben.

Neu soll im Selbstregistrierungsformular im Land-Dropdown Schweiz vorausgewählt sein.

# Mockup
![Screenshot 2024-02-12 at 12-10-32 hitobito - Registrierung zu SAC Matterhorn](https://github.com/hitobito/hitobito_sac_cas/assets/7566995/efa49a28-cbbb-470e-8b64-4b902949823c)

# Tech-Spec

- **Achtung!** Die Adressfelder werden vom Template contactable/address_fields im Core gerendert. Wir hatten dort schon mal einen Fallback auf das default country drin, aber der verursachte im Zusammenhang mit Haushalten und Zugriffsrechten über lange Zeit hinweg schwer zu verstehende Probleme und musste in https://github.com/hitobito/hitobito/commit/f86b2dc8484de822718cfa14c1eab66fb83ddb93 entfernt werden.
  - Das Problem im Detail: Zwei Personen sind zusammen im Haushalt, beide haben aktuell kein Land eingetragen (kein Land zu haben ist im Core ein valider Use Case). Eine Leitperson bearbeitet eine der beiden Haushalts-Personen, ändert irgendwelche Felder (oder auch gar keine) und klickt auf Speichern. Da das Formular den Fallback enthielt, wird dabei das Land der bearbeiteten Person auf Schweiz gestellt. Wenn die Leitperson nun keinen Zugriff auf die zweite Haushalts-Person hat, dann verhindert eine Validierung die gesamte Speichern-Operation, da das Land immer gleich für den ganzen Haushalt aktualisiert wird und man dafür Schreibrechte auf allen Personen im Haushalt haben muss. Workaround ist, beim Bearbeiten jedes Mal manuell das Land zurück auf den leeren Wert zu setzen.
- Eine bessere Lösung welche nur das SAC-Selbstregistrierungsformular verändert wäre, auf dem SelfRegistration MainPerson ActiveModel einen Default-Wert für das country Attribut anzulegen

# ToDo

- [ ] Default-Wert für country Attribut auf SAC MainPerson ActiveModel erfassen (oder andere Lösung umsetzen)
- [ ] Specs schreiben
- [ ] **Mit angemessener Rolle "durchklicken", insbesondere auch das Bearbeiten einer Person welche in einem Haushalt ist und bei welcher man auf die Haushaltspartner keine Schreibrechte hat**

**Comment by sykesonrocks** [comment]
@mtnstar OK
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/40a05c64-0cd7-4219-8ff3-90fa9df279a8)
