### ISSUE TITLE
PEOPLE: Qualifikationen im Verlauf

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#317]
Im Tab "Verlauf" einer Person sind zuunterst alle aktiven und nicht aktiven Qualifikationen chronologisch aufgelistet.

Neueste Qualifikationen werden zuoberst angezeigt (Gültig Bis DESC, nulls first). Der Name der jeweils aktuellsten Qualifikation einer Qualifikationsart wird fett dargestellt, falls die Qualifikation noch erneuerbar ist. Folgende Spalten werden angezeigt:

* Name (der Qualifikationsart)
* Ursprung
* Gültig von
* Gültig bis
* Reaktivierbar bis

Spalte "Offene Ausbildungstage" wird in #332 hinzugefügt.

**Comment by sykesonrocks** [comment]
@codez Nachfolgend meine Testergebnisse.

- Im Tab "Verlauf" einer Person sind zuunterst alle aktiven und nicht aktiven Qualifikationen korrekt aufgelistet:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/a4faefba-cbe9-4781-8432-8eea603ede66)
- Neueste Qualifikationen werden zuoberst angezeigt (Gültig Bis DESC, nulls first). Der Name der jeweils aktuellsten Qualifikation einer Qualifikationsart wird fett dargestellt, falls die Qualifikation noch erneuerbar ist. 
- Folgende Spalten werden angezeigt: Name (der Qualifikationsart), Ursprung, Gültig von, Gültig bis, Reaktivierbar bis

Somit OK.
