### ISSUE TITLE
PEOPLE: Kursteilnahmen im Verlauf

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#318]
Die Tabelle mit den Event Teilnahmen im Verlauf einer Person soll um eine zusätzliche Spalte ergänzt werden. Diese enthält nur bei Kursen den folgenden Inhalt:

* Erste Zeile "Bestanden"/"Nicht bestanden" (qualified)
* Zweite Zeile: "n Ausbildungstage"

**Comment by sykesonrocks** [comment]
@tobiasstern works as designed. Ich fände es benutzerfreundlich, wenn die Headers mit angezeigt wären:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/ce8bf7ed-880c-4b6e-92bd-dd0409c5497b)
