### ISSUE TITLE
GROUPS: Weitere Attribute auf Sektion

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#321]
DRAFT

              @mtnstar 3 Rückmeldungen

1 - Neben der Sprache sehe ich im Tab "Sektions Attribute" weitere Felder, die notwendig sind:
- Bezeichnung auf Mitgliederausweis: Freitextfeld/String
- Anzahl Jahre für Befreiung: Freitextfeld/Integer
- Reduktion Sektionsbeitrag: Freitextfeld/Dezimal
- Ehrenmitglied zulässig: Drop-Down oder Radio Button/Boolean
- Begünstigte zulässig: Drop-Down oder Radio Button/Boolean
- Art Ehrenmitglied: Drop-Down oder Radio Button (mögliche Werte: "beides erlassen/Les deux parts remises", "Sektionsanteil erl./Part de la section remise", "ZV-Beitrag erl./Part de la cotisation au CC remise")
- Art Begünstigte: Drop-Down oder Radio Button (mögliche Werte: "beides erlassen/Les deux parts remises", "Sektionsanteil erl./Part de la section remise", "ZV-Beitrag erl./Part de la cotisation au CC remise")

--> Diese Sektionsangaben sind im Import-File ebenfalls enthalten, siehe "Sektion_Export_20230629.xlsx" unter https://saccas.atlassian.net/wiki/spaces/RDIE/pages/3883040775/Datenmigrationskonzept#Export/Import-Dateien

2 - Weiter wurde im KVS-Projekt diskutiert, ob man auf dem Top-Layer (SAC/CAS) und auf der Sektion verschiedene Kontaktpersonen für unterschiedliche Themenbereiche anbieten sollte - dies insbesondere im Hinblick auf die Zustellung von E-Mails. Eine Kursbuchung soll z.B. in Form einer E-Mail auch der Kursadministration zugestellt werden. Der Empfänger dieser E-Mail würde Hitobito mit dieser Erweiterung aus der "Gruppenkarte" ablesen (z.B. Kontakt für Kurswesen: alpin@sac-cas.ch). Im Hinblick auf das TVS Projekt würde es ebenfalls Sinn machen, solche Kontakte auf der Sektionskarte definieren zu können.

3 - Für die Steckbriefe der Sektionen (siehe z.B. https://www.sac-cas.ch/de/der-sac/sektionen/sac-bern/) dient Typo3 als Master (z.B. Beschreibungstext). Pro Sektion werden auch die Angebote ausgegeben (z.B. Jugendorganisation, Seniorengruppe, Rettungskolonne). Wäre es möglich, dass diese Boolean-Werte ebenfalls auf der Sektionskarte angeboten werden? Ansonsten müsste Typo3 für diese Flags weiterhin als Master dienen.

_Originally posted by @sykesonrocks in https://github.com/hitobito/hitobito_sac_cas/issues/244#issuecomment-1952068226_

**Comment by sykesonrocks** [comment]
Dieses Issue ist mit https://github.com/hitobito/hitobito_sac_cas/issues/471 obsolet, weshalb ich dieses Ticket schliesse.
