### ISSUE TITLE
PEOPLE: Filter Qualifikationen - Keine gültige

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#334]
Als Gruppenadmin möchte ich Personen ohne bestimmte Qualifikationen filtern.

Neu soll auf dem Personenfilter im Panel Qualifikationen eine zusätzliche Option "Keine gültigen Qualifikationen" zur Verfügung stehen. Für diese erscheint ebenfalls das Eingabefeld "Stichdatum". Siehe auch #333.

# Tech-Spec

Das Problem beim Query besteht darin, das mehrere zeitlich überlappende Qualifikationen mit gleicher Qualiart vorhanden sein können. Zum Beispiel:
1. Quali A von 2016 - 2020
2. Quali A von 2018 - 2022
3. Quali A von 2020 - 2024 
4. Quali B von 2018 - 2022
5. Quali C von 2022 - 2026

Wir gehen davon aus, dass Qualiart A und B angezeigt werden sollen. Die Auswahl "Person hat mindestens EINE dieser Qualifikationen" und "Person hat ALLE diese Qualifikationen" ist für diese Option nicht relevant.

* Für das Jahr 2024 wird die Person nicht angezeigt, da 3. noch gültig ist
* Für das Jahr 2025 wird die Person angezeigt, da weder A noch B gültig ist.
* Falls nur Qualiart D angezeigt werden soll, erscheint die Person immer, da sie keine solche Quali hat.

# ToDo

- [x] Filterquery anpassen
- [x] View anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
@codez @daniel-illi Ich werde dieses Ticket testen sobald "PEOPLE: Zusätzliche Default Personenfilter für Tourenleitende #336" umgesetzt ist.
