### ISSUE TITLE
PEOPLE: Filter Rollen - Nicht aktive Rollen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#335]
Als Gruppenadmin möchte ich Personen ohne bestimmte Rolle filtern.

Neu soll auf dem Personenfilter im Panel Rollen eine zusätzliche Option "war die Rolle nicht aktiv" zur Verfügung stehen. 

# Tech-Spec

Diese Option ist eine Art Inversion von "war die Rolle aktiv". Es werden alle Personen angezeigt, welche im gewählten Scope (aktuelle Ebene und darunter / nur aktuelle Ebene / aktuelle Gruppe) und allenfalls Zeitraum (falls im Filter ausgefüllt) eine beliebige Rolle haben, ausser den ausgewählten Rollen. Sobald eine Person mindestens eine der gewählten Rollen hat, wird sie in den Resultaten nicht angezeigt.

# ToDo

- [ ] Filter anpassen
- [ ] View anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sykesonrocks** [comment]
Wird im Zuge von https://github.com/hitobito/hitobito_sac_cas/issues/336 getestet.
