### ISSUE TITLE
PEOPLE: Zusätzliche Default Personenfilter für Tourenleitende

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#336]
Neu soll auf jeder Ebene im SAC Wagon die folgenden Personenfilter standardmässig zur Verfügung stehen:

- Aktive Tourenleiter: alle mit Rolle “Tourenleiter*in” + mit aktiven Qualifikationen “SAC Tourenleiter/in 1 Winter” oder “SAC Tourenleiter/in 1 Sommer” usw. 
- Sistierte Tourenleiter: alle mit Rolle “Tourenleiter*in” + mit keinen aktiven, aber reaktivierbaren Qualifikationen “SAC Tourenleiter/in 1 Winter” oder “SAC Tourenleiter/in 1 Sommer” usw. 
- Inaktive Tourenleiter: alle ohne Rolle “Tourenleiter*in” + mit aktiven Qualifikationen “SAC Tourenleiter/in 1 Winter” oder “SAC Tourenleiter/in 1 Sommer” usw. 
- Keine Tourenleiter: alle ohne Rolle “Tourenleiter*in” + mit keinen aktiven Qualifikationen “SAC Tourenleiter/in 1 Winter” oder “SAC Tourenleiter/in 1 Sommer” usw. 

Es werden alle Personen auf der aktuellen Ebene und darunter angezeigt. Die Filter enthalten jeweils alle Qualifikationen, welche eine Gültigkeitsdauer haben.

Diese Filter sollen entsprechend im SAC Wagon für Sektionen und Nationalverband hinzugefügt werden, damit sie automatisch im Dropdown erscheinen. Die Namen der Filter müssen mehrsprachig sein können. Die Methode `FilterNavigation::People#add_people_filter_links` kann im Wagon entsprechend erweitert werden, damit diese Filter bei den genannten Layer zuunterst im Dropdown angezeigt werden.

**Comment by codez** [comment]
@mtnstar Siehe letzter Absatz oben. Die Jubla hat solche globalen Filter. Weisst du, ob die auch für die "neuen" Filter Chains funktionieren? Gibt es in MV auch vordefinierte Filter? Falls ja, wie setzt ihr die um?

**Comment by mtnstar** [comment]
@codez ja, es gibt bereits so einen filter auf dem Top-Layer: https://github.com/hitobito/hitobito_sac_cas/blob/master/app/helpers/sac_cas/filter_navigation/people.rb, #96
Es waren diverse solche Filter geplant und wir hatten sogar eine Überarbeitung des UIs geplant da sonst das Drop-Down unbrauchbar wird. https://github.com/hitobito/hitobito/issues/2340
Austausch mit dem SAC hat aber ergeben das es zurzeit gerade unklar ist wie viele solche Filter effektiv eingerichtet werden sollen. 
es braucht hier sicher noch eine saubere technische Konzeption wie wir solche Filter einrichten können, es scheint immer wieder mal Bedarf bei Kunden. Das diese auch übersetzbar sind scheint mir sinnvoll, das hatten wir aber bisher gar nicht auf dem Radar.

**Comment by sykesonrocks** [comment]
Testing im Gange. Wird am 16.04 mit dem Fach zusammen angeschaut.

**Comment by sykesonrocks** [comment]
@codez Ich habe die Listen heute getestet und in Rücksprache mit dem Fach, kann ich bestätigen, dass die Filter nicht korrekt umgesetzt wurden.

### SOLL

**«Aktive Tourenleiter»**
Scope: Alle Personen mit Rolle «Tourenleiter*in» + mind. 1 gültige Qualifikation

**«Sistierte Tourenleiter»** 
Scope: Alle Personen ohne Rolle «Tourenleiter*in» + mind. 1 sistierte Qualifikation + 0 gültige Qualifikationen

**«Inaktive Tourenleiter»** 
Scope: Alle Personen ohne Rolle «Tourenleiter*in» + mind. 1 gültige Qualifikation

**«Keine Tourenleiter»** 
Scope: Alle Personen ohne Rolle «Tourenleiter*in» + 0 gültige Qualifikationen+ 0 sistierte Qualifikationen+ 0 abgelaufene Qualifikationen

### Neu
**«Abgelaufene Tourenleiter»** 
Scope: Alle Personen ohne Rolle «Tourenleiter*in» + 0 gültige Qualifikationen+ 0 sistierte Qualifikationen+ mind. 1 abgelaufene Qualifikation

**Systemprüfung bei Rollenzuweisung (Tourenleiter*in)**
- Hitobito muss bei der Rollenzuweisung (Tourenleiter*in) prüfen, ob mind. 1 gültige Qualifikation vorliegt 
- Hitobito muss täglich prüfen, ob die Rolle weiterhin zulässig ist (und ansonsten terminieren) 
- Hitobito muss, wenn eine Qualifikation gelöscht wird, prüfen, ob die Rolle weiterhin zulässig ist (und ansonsten terminieren)
Ich habe hierzu eine neue Story in Jira eröffnet: https://saccas.atlassian.net/browse/HIT-84.

Bitte teile mir mit, ob ich für die neue Liste "Abgelaufene Tourenleiter" ebenfalls eine neue Story eröffnen soll.

**Comment by sykesonrocks** [comment]
@codez Ich habe die Listen heute getestet und in Rücksprache mit dem Fach, kann ich bestätigen, dass die Filter nicht korrekt umgesetzt wurden.

### SOLL
**«Aktive Tourenleiter»**
Scope: Alle Personen mit Rolle «Tourenleiter*in» + mind. 1 gültige Qualifikation

**«Sistierte Tourenleiter»**
Scope: Alle Personen ohne Rolle «Tourenleiter*in» + mind. 1 sistierte Qualifikation + 0 gültige Qualifikationen

**«Inaktive Tourenleiter»**
Scope: Alle Personen ohne Rolle «Tourenleiter*in» + mind. 1 gültige Qualifikation

**«Keine Tourenleiter»**
Scope: Alle Personen ohne Rolle «Tourenleiter*in» + 0 gültige Qualifikationen+ 0 sistierte Qualifikationen+ 0 abgelaufene Qualifikationen

### Neu

**«Abgelaufene Tourenleiter»**
Scope: Alle Personen ohne Rolle «Tourenleiter*in» + 0 gültige Qualifikationen+ 0 sistierte Qualifikationen+ mind. 1 abgelaufene Qualifikation

**Systemprüfung bei Rollenzuweisung (Tourenleiter*in)**
- Hitobito muss bei der Rollenzuweisung (Tourenleiter*in) prüfen, ob mind. 1 gültige Qualifikation vorliegt
- Hitobito muss täglich prüfen, ob die Rolle weiterhin zulässig ist (und ansonsten terminieren)
- Hitobito muss, wenn eine Qualifikation gelöscht wird, prüfen, ob die Rolle weiterhin zulässig ist (und ansonsten terminieren)

Ich habe hierzu eine neue Story in Jira eröffnet: https://saccas.atlassian.net/browse/HIT-84.
Bitte teile mir mit, ob ich für die neue Liste "Abgelaufene Tourenleiter" ebenfalls eine neue Story eröffnen soll.

**Comment by codez** [comment]
Die Anpassungen werden in entsprechenden Folgetickets angegangen: #499, #500, #501

**Comment by sykesonrocks** [comment]
Follow-up Aufträge werden wie oben kommentiert in weiteren Issues bearbeitet.
