### ISSUE TITLE
PEOPLE: Selbstregistrierung Step 2: Adult consent muss akzeptiert werden

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#344]
### Aktuelles Verhalten

Wenn man beim Selbstregistrierungsformular hin und zurück navigiert in den Steps, dann erscheint plötzlich auf Schritt 2 der Fehler: Adult consent muss akzeptiert werden. 

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/b41a6721-ca0e-4605-b11e-463047702336)

### Gewünschtes Verhalten

Die Fehlermeldung sollte nie auf Step 2 auftauchen

### Schritte zu reproduzieren

1. Selbstregistrierungslink einer Sektion aufrufen (im icognito mode)
2. Felder ausfüllen und bis Step 4 navigieren
3. Zurück navigieren bis auf Schritt 2
4. Dann wieder Weiter, die Fehlermeldung wird angezeigt

**Comment by sykesonrocks** [comment]
@mtnstar Ich konnte die Fehlermeldung nicht reproduzieren, somit ok.
