### ISSUE TITLE
INVOICES: Kostenstellen & Kostenträger verwalten

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#348]
Als Verbandsadmin
möchte ich Kostenstellen und Kostenträger global verwalten,
um eine automatisierte Verrechnung zu ermöglichen.

Neu soll im SAC Wagon unter Einstellungen zwei Menupunkte "Kostenstellen" und "Kostenträger" (alphabetisch eingeordnet) stehen, unter welchem globale Admins die Kostenstellen bzw. die Kostenträger verwalten können.

# Tech-Spec

Die Models sind beide gleich definiert:

*Kostenstellen* (cost_centers) und *Kostenträger* (cost_units)
- code (string, not null, unique)
- label (string, not null, translatable)
- created_at
- updated_at
- deleted_at

Reguläre Crud Controller und Views. Die Liste wird jeweils nach Code sortiert. 
Als Anzeige der Models (to_s) wird jeweils der Code und das Label in der aktuellen Sprache verwendet, getrennt durch " – ".

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller erstellen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez Wenn kein Mehraufwand besteht, gerne mehrsprachig - ansonsten OK für mich.

- label_de (string, not null, translatable)
- label_fr (string, not null, translatable)

**Comment by codez** [comment]
"translatable" bedeutet bereits mehrsprachig. hitobito arbeitet nicht mit Sprachsuffixen (_de).

**Comment by sykesonrocks** [comment]
@codez Nachfolgend meine Testergebnisse.

- Neu finde ich im SAC Wagon unter Einstellungen zwei Menupunkte "Kostenstellen" und "Kostenträger", unter welchem ich als Admin die Kostenstellen bzw. die Kostenträger verwalten kann. Somit Ok.
- Ich kann Kostenstellen erfassen und mutieren, somit OK:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/420bedc1-452d-479f-a073-d6ed7fe0c296)
- Ich kann Kostenträger erfassen und mutieren, somit OK:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/539dea3d-fc56-4501-b39b-ead47f17ac41)
- Ich kann jedoch keine bestehenden Einträge unter "Kostenstellen" und "Kostenträger" löschen. Beim Löschen erhalte ich folgende Fehlermeldung:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/204bc572-a12f-4f83-8ce7-917eef1b6235)
