### ISSUE TITLE
EVENTS: Zusätzliche Attribute Kurskategorie

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#349]
Als Verbandsadmin im SAC Wagon
möchte ich auf den Kurskategorien zusätzlich die Attribute "Kostenstelle" und "Kostenträger" führen,
um eine automatisierte Verrechnung zu ermöglichen.

# Tech-Spec

Die beiden Attribute sind Referenzen auf entsprechende Tabellen (siehe #348). Entsprechend braucht es auf der Kurskategorie (Events::KindCategory) zwei zusätzliche Attribute:
- cost_center (belongs_to, not null)
- cost_unit (belongs_to, not null)

Kostenstellen/-träger, welche mit einer nicht gelöschten Kategorie assoziiert sind, können nicht gelöscht werden (`has_many :event_kind_categories, dependent: :restrict_with_error`). Falls alle assoziierten Kategorien gelöscht sind, kann der Eintrag ebenfalls soft deleted werden.

Das Formular der Kurskategorie wird entsprechend um zwei Dropdowns ergänzt, wo die Werte ausgewählt werden können. 

Bei der Migration soll automatisch die erste Kostenstelle/-träger zugeordnet werden. Falls dort kein Eintrag existiert, wird einer erstellt.

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez Nachfolgend meine Testergebnisse.

- Die zwei Felder "Kostenstelle" und "Kostenträger" sind auf der Kurskategorie erhältlich. Bestehende Kurskategorien können mutiert werden, somit OK.

![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/c9e61906-8154-4e3e-a4d3-7ecf4e309629)
