### ISSUE TITLE
PEOPLE: Anpassungen Selbstregistrierung Mitgliedschaft Eintrittsdatum per

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#350]
dies ist ein follow up von #295

Selbstregistrierung Mitgliedschaft: Die Auswahl des Eintrittsdatum und die zugehörige Info-Text-Box soll noch weiter angepasst werden damit diese die Spezifikation erfüllt. 

### Case 1: Datum 1.1 - 30.6, es wird Option sofort ausgewählt

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/c15f1750-f45b-47cb-bc27-b2ab1f2e07df)

- Datum 1.1 - 30.6 -> Optionen sofort, 1. Juli
- Das aktuelle Jahr als Variable im Translated Text

### Case 2: Datum 1.1 - 30.6, es wird Option 1. Juli ausgewählt

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/7be7ab47-57a2-4382-9edd-0dfbe71332bd)

- Datum 1.1 - 30.6 -> Optionen: sofort, 1. Juli

### Case 3: Datum 1.7 - 30.9, es wird Option sofort ausgewählt

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/b96608c5-72a3-409b-bfa3-c9e77d1adb48)

- Datum Datum 1.7 - 30.9 -> Optionen: sofort, 1. Oktober

### Case 4: Datum 1.7 - 30.9, es wird Option 1. Oktober ausgewählt

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/b26738ad-2c93-4347-a67f-db8259aa5723)

- Datum Datum 1.7 - 30.9 -> Optionen: sofort, 1. Oktober

### Case 5: Datum 1.10-31.12

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/134b9a8d-94bf-44a4-8e5a-0aeaa754185c)

- Datum Datum  1.10 - 31.12 -> Optionen: sofort

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/config/locales/wagon.de.yml#L402
- das Von-Datum der Neuanmeldung Rolle(n) auf das gewählte Datum setzen
- Falls sofort gewählt ist, das aktuelle Datum verwenden
- Datum bei allen Familien/Haushaltsmitglieder setzen
- Standardmässig ist immer sofort ausgewählt

# ToDo

- [ ] Sicherstellen das die 3 Texte im de locale file vorhanden ist
- [ ] Anzeige des richtigen Textes nach der Logik oben (client side Text switchen nach Auswahl option)
- [ ] manuelles Testen

**Comment by mtnstar** [comment]
@sykesonrocks und noch ein follow up ticket.
habe ich das mit dem Text so richtig verstanden und spezifiziert ?

**Comment by mtnstar** [comment]
![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/83dc0200-a007-4410-b76a-7cf96f9eefa0)

- Es gibt jetzt eine weitere Anforderung mit dem konfigurierbaren Datum (hier 3.12). Braucht es das wirklich? 
- Die ganze Info ist sehr an die Faktura angegliedert. z.B. auch wann das welche Rabattstufe gilt. Mein Vorschlag wäre hier zu warten bis wir das Faktura Modul umgesetzt haben und die Info dieser Texte aus diesem Modul zu beziehen. So laufen die effektive Faktura sowie die Info die dem Neumitglied angezeigt werden nie auseinander

**Comment by amaierhofer** [comment]
Obsolete und mit https://github.com/hitobito/hitobito_sac_cas/issues/935 ersetzt
