### ISSUE TITLE
EVENTS: Zusätzliche Attribute Kursart

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#352]
Als Verbandsadmin im SAC Wagon
möchte ich auf der Kursart zusätzliche Attribute,
um eine automatisierte Verrechnung zu ermöglichen.

# Tech-Spec

Neu sollen folgende Attribute auf der Kursart bearbeitbar sein:
- Kursstufe / level_id (belongs_to :event_level, not null, siehe #351)
- Kostenstelle / cost_center_id (belongs_to, not null)
- Kostenträger / cost_unit_id (belongs_to, not null)
- Maximale Teilnehmerzahl / maximum_participants (integer, nullable)
- Minimale Teilnehmerzahl / minimum_participants (integer, nullable)
- Ausbildungstage / training_days (decimal, 3 Vor-, 1 Nachkommastellen, nullable)
- Saison / season (enum/Select: winter, summer; nullable)
- Unterkunft reservieren durch SAC / reserve_accommodation (boolean, not null, default true)
- Unterkunft (enum/Select: no_overnight, hut, pension, pension_or_hut, bivouac; nullable, default no_overnight; DE: ohne Übernachtung, Hütte, Pension/Berggasthaus, Pension/Berggasthaus oder Hütte, Übernachtung im Freien/Biwak; FR: sans nuitée, en cabane, en pension/auberge, en pension/auberge ou cabane, nuitée en plein air/en bivouac)

Folgende bestehenden Felder sind neu Pflichtfelder und sollen im Model entsprechend validiert werden:
- Kurskategorie
- Kurzname

Kostenstellen/-träger und Kursstufen, welche mit einer nicht gelöschten Kursart assoziiert sind, können nicht gelöscht werden (has_many :event_kinds, dependent: :restrict_with_error). Falls alle assoziierten Kursarten und Kurskategorien gelöscht sind, kann der Eintrag ebenfalls soft deleted werden.

Bei der Migration sollen für Kurstufe und Kostenstelle/-träger bei bestehenden Kursarten jeweils automatisch der erste Eintrag ausgewählt werden. Falls dort keine Einträge existieren, wird jeweils ein Dummy Eintrag erstellt.

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez Ich kann diese Anpassung nicht testen, erhalte eine 500-Fehlermeldung, wenn ich eine bestehende Kursart versuche zu editieren:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/4db7213f-fe14-49d1-b0ab-e37c873e41aa)

**Comment by sykesonrocks** [comment]
@amaierhofer Ich glaube hier handelt es sich um ein Typo, müsste "Kursstufe" lauten:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/38059822-bab5-47f2-bce2-c61e37216e90)
