### ISSUE TITLE
EVENTS: Zusätzliche Attribute Kurse

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#353]
Als Kursadministrator:in im SAC Wagon
möchte ich zusätzliche Attribute verwalten können.

## Formular

Neu sollen die folgenden Attribute auf Kurse bearbeitet werden können:

Fields:
- Sprache / language (enum: de_fr, de, fr, it; Labels Deutsch/Französisch, Deutsch, Französisch, Italienisch; Dropdown)
- Kostenstelle / cost_center_id (belongs_to, nullable)
- Kostenträger / cost_unit_id (belongs_to, nullable)
- Jährlich wiederkehrend / annual (boolean, not null, default true)
- Link Teilnehmer / link_participants (string)
- Link Kurskader / link_leaders (string)
- Link Umfrage / link_survey (string)

Location Fields:
- Unterkunft reservieren durch SAC / reserve_accommodation (boolean, not null, default true)
- Unterkunft (enum/Select: no_overnight, hut, pension, pension_or_hut, bivouac; nullable, default no_overnight; DE: ohne Übernachtung, Hütte, Pension/Berggasthaus, Pension/Berggasthaus oder Hütte, Übernachtung im Freien/Biwak; FR: sans nuitée, en cabane, en pension/auberge, en pension/auberge ou cabane, nuitée en plein air/en bivouac)

Date Fields:
- Saison / season (enum: winter, summer; nullable)
- Kursbeginn / start_point_of_time (enum: day, evening; nullable; DE: Tag, Abend)

Application Fields:
- Mindestalter / minimum_age (integer)

Die folgenden bestehenden Felder werden zusätzlich konfiguriert:
- Kursnummer: Presence & Uniqueness Validation
- Kosten sollen komplett ausgeblendet werden

## Show Seite

Auf der Kurs Show Seite werden folgende Anpassungen gemacht:

Attrs Main:
- Kursstufe (von Kursart)
- Saison
- Daten werden mit Wochentagen angezeigt (zwei Buchstaben, Anpassung im Core)

Attrs Primary:
- Sprache
- Unterkunft
- Kursbeginn

Attrs Application
- Mindestalter wird vom Kurs genommen, nicht von der Kursart (im Core auf Event::Course eine Methode `minimum_age` erstellen, welche `kind.minimum_age` zurückgibt. Diese Methode wird im Wagon überschrieben).

## Weiteres

- Kostenstellen/-träger, welche mit einem Kurs assoziiert sind, können nicht hart gelöscht werden, nur soft (`has_many :events, dependent: :restrict_with_error`). 

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez wie besprochen habe ich noch das Feld “Automatische Zuteilung“ (Pflichtfeld | Boolean | Standard: nein) im Register “Anmeldung” hinzugefügt (siehe https://saccas.atlassian.net/browse/HIT-248)

**Comment by codez** [comment]
Zusätzliche Anmeldefelder sind in #358 definiert.

**Comment by sykesonrocks** [comment]
@codez Ich kann diese Anpassung nicht testen, erhalte eine 500-Fehlermeldung, wenn ich einen bestehenden Kurs versuche zu editieren:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/4b486059-13e0-4f96-afcc-afb5aa1105ef)
