### ISSUE TITLE
EVENTS: Vererbung Kursart -> Kurs

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#355]
Als Verbandsadministrator im SAC Wagon
möchte ich gewisse Attribute einer Kursart in den Kurs übernehmen.

# Tech-Spec

Wenn im Formular des Kurses eine Kursart ausgewählt wird, werden die folgenden Werte übernommen, sofern die entsprechenden Felder noch leer sind:
- Mindestalter
- Aufnahmebedingungen
- Maximale Teilnehmerzahl
- Minimale Teilnehmerzahl
- Saison
- Ausbildungstage
- Unterkunft reservieren durch SAC
- Unterkunft
- Kostenstelle
- Kostenträger

Siehe auch `events/course_description_handler.js.coffee`.

Zudem wird hinter oder unter dem Dropdown für die Kursart ein Link "Daten übernehmen" hinzugefügt. Beim Klicken auf diesen Link werden die oben erwähnten Felder mit den Werten aus der Kursart ersetzt (auch wenn diese bereits Werte enthalten).

# ToDo

- [ ] View anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez works as designed. @tobiasstern Details, aber evt. kann ich dir solche Punkte einfach dir delegieren und du nimmst den Prozess Jira->Git auf, oder wir überlegen uns für solche Punkte einen festen/"kürzeren" Admin/Jira-Prozess..:
- Wenn man die Werte übernimmt, aber in der höheren Hierarchiestufe kein Wert definiert ist, wird "undefined" als Wert eingefügt (z.B. im Feld Beschreibung). Wäre schöner, wenn das Feld leer bleibt..
- Der User weiss nicht welche Werte übernommen werden, oder ich habe es übersehen. Irgendwo als Tooltip oder festen Text anzeigen wäre hilfreich..

**Comment by sykesonrocks** [comment]
@codez @amaierhofer Beim Feld "Beschreibung" resp. "Standardbeschreibung" scheint es noch ein Problem zu geben. Wenn ich auf der Kursart im Feld "Standardbeschreibung" ein Wert eintrage, speichere und danach auf "Daten auf Kurse übertragen" klicke, wird die Standardbeschreibung nicht auf die Kurse übertragen. Auf dem Kurs aber, wenn ich auf "Werte übernehmen" klicke, wird der Wert aus dem Feld "Standardbeschreibung" in das Feld "Beschreibung" eingetragen. 

TODO: Wert im Feld "Standardbeschreibung" gilt es ebenfalls zu vererben - sorry, habe ich in der oberen Spez übersehen. Danke!

**Comment by sykesonrocks** [comment]
Dürfte ich bitten die Umsetzung abzuschliessen:
1. Tooltip bei "Werte übernehmen", sodass User eine Liste der betroffenen Werte einsehen kann
2. Wenn auf der höheren Hierarchiestufe kein Wert definiert ist und der User die Werte übernimmt, soll ein leerer String übernommen werden (und nicht "undefined" eingetragen werden)

Danach bitte https://saccas.atlassian.net/browse/HIT-249 mir zuweisen und auf "Verifikation" setzen - danke!

**Comment by tobiasstern** [comment]
Tooltip wurde integriert und leere Felder werden nun auch leer übertragen 👍 ich schliesse dieses Ticket
