### ISSUE TITLE
EVENTS: Vererbung Kursart -> Kurse (Push)

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#360]
Als Verbandsadmin im SAC Wagon
möchte ich bestimmte Attribute der Kursart auf die zugeordneten Kurse pushen
 
# Tech-Spec

Auf der Bearbeiteansicht der Kursart gibt es neu eine Toolbar mit dem Button "Daten auf Kurse übertragen".  Icon turn-down.

Darauf folgt ein Bestätigungsdialog: "Wollen Sie wirklich die gespeicherten Daten auf alle aktiven Kurse übertragen? Dabei werden die aktuellen Werte überschrieben."

Falls der Dialog akzeptiert wird, werden die folgenden Attribute auf allen zugeordneten Kurse angepasst, welche sich nicht im Status Abgeschlossen oder Annuliert befinden:
- Mindestalter
- Aufnahmebedingungen
- Maximale Teilnehmerzahl
- Minimale Teilnehmerzahl
- Saison
- Ausbildungstage
- Unterkunft reservieren durch SAC
- Unterkunft
- Kostenstelle
- Kostenträger

# ToDo

- [ ] View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Hey @amaierhofer

Wenn ich auf der Kursart https://sac-cas.puzzle.ch/de/event_kinds/72/edit die neue Aktion ausführe, dann lande ich auf einer 404 Seite mit der URL https://sac-cas.puzzle.ch/de/event_kind_categories/72/push_down 
Ich denke das ist noch etwas falsch verlinkt. Kannst du das bitte beheben?
LG

**Comment by amaierhofer** [comment]
@tobiasstern wurde behoben und deployed

**Comment by tobiasstern** [comment]
@amaierhofer danke, konnte es nun testen. Es funktioniert grundsätzlich. Mir sind aber noch diese Fehler aufgefallen:

- **Aufnahmebedingungen**: Der Vererbungs-Push beeinflusst auch Kurse im Status _Abgeschlossen_ und _Annulliert_
- **Max TN, Min TN, Ausbildungstage**: Wenn die Kursart hier keine Werte hat, dann werden mittels Push vorhandene Werte in den Kursen nicht überschrieben

Kannst du dies bitte beheben?

**Comment by tobiasstern** [comment]
Ah, Mindestalter konnte ich nicht testen, weil das zweimal auf dem UI angezeigt wird. Das eine wird vom push angekickt, das andere nicht. Habe @codez informiert. Wird getestet sobald behoben.

**Comment by codez** [comment]
Das doppelte Mindestalter wird mit https://github.com/hitobito/hitobito/pull/2558 und https://github.com/hitobito/hitobito_sac_cas/pull/465/ behoben.

**Comment by codez** [comment]
Das mit den Aufnahmebedingungen von der Kursart und dem Kurs ist schon verwirrend, insbesondere weil es sich um eine Ausnahme handelt. Können wir das anpassen, dass immer nur die Anmeldebedinungen vom Kurs angezeigt werden? Initial werden diese von der Kursart vererbt und können dann bei Bedarf angepasst werden, wie die anderen vererbten Felder auch.

**Comment by amaierhofer** [comment]
Aufnahmebedingungen wurden mit 8fec6ba angepasst.

**Comment by amaierhofer** [comment]
@sykesonrocks die Beschreibungen werden mit dd85709  ebenfalls übernommen

**Comment by sykesonrocks** [comment]
Die Beschreibung wird nun korrekt von der Kursart auf den Kurs geerbt/gepushed.
