### ISSUE TITLE
EVENTS: Kursstatus Anmeldung abgeschlossen automatisch setzen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#361]
Als Kursadmin im SAC Wagon
möchte ich dass der Kursstatus automatisch auf "Anmeldung abgeschlossen" gesetzt wird, wenn der Anmeldeschluss verstrichen ist.

# Tech-Spec

Es braucht einen täglichen Background Job, welcher alle Kurse im Status "Publiziert" oder "Anmeldung pausiert", deren Anmeldeschluss vorbei ist (< heute), auf den Status "Anmeldung abgeschlossen setzt.

Als zusätzliches Model before save Callback wird der Status ebenfalls angepasst, wenn der Anmeldeschluss verändert wird:
- Status "Publiziert" oder "Anmeldung pausiert" & Anmeldeschluss < heute: => Status "Anmeldung abgeschlossen"
- Status "Anmeldung abgeschlossen" & Anmeldeschluss >= heute: => Status "Publiziert"

# ToDo

- [ ] Model anpassen
- [ ] Jobklasse erstellen
- [ ] Specs schreiben

**Comment by tobiasstern** [comment]
@amaierhofer 

- der Statuswechsel funktioniert, wenn ich den Anmeldeschluss in die Vergangenheit setze 👍
- bei https://sac-cas.puzzle.ch/de/groups/1/events/5 habe ich getestet: Den Anmeldeschluss habe ich gestern (08.04.) auf den 08.04. gesetzt, aber heute ist der Status des Kurs immer noch publiziert. Ich habe erwartet, dass dieser Job aktiv wird und die Anmeldung heute geschlossen ist. Ist das noch ein Bug?


@codez Ähnlich wie das manuelle setzen eines Datums in der Vergangenheit den Status auf "Anmeldung abgeschlossen" ändert, sollte das manuelle setzen eines Datums in die Zukunft die Anmeldung wieder öffnen (vgl. Jira ticket HIT-250). Ist dieses Verhalten irgendwo spezifiziert? Ich finde es nicht in den Tickets.

**Comment by amaierhofer** [comment]
@tobiasstern, ich habe nochmals lokal gestet und aus meiner Sicht funktionieren die Statuswechsel in beide Richtigungen, jedoch jeweils nur wie im ticket spezifiziert wenn das Anmeldeschluss datum angepasst wird. 

Der nächtliche status Wechsel allerdings hat nicht funktioniert, da der entsprechene job nicht geseeded wurde, dass hab ich angepasst.

**Comment by codez** [comment]
@amaierhofer Der Wechsel von "Anmeldung abgeschlossen" zu "publiziert" funktioniert nicht, wenn man den Anmeldeschluss von der Vergangenheit auf Heute setzt:
* Anmeldeschluss ist 1.4.2024, Status ist entsprechend "Anmeldung abgeschlossen"
* Wird der Anmeldeschluss auf heute (= 9.4.2024) gesetzt, bleibt der Status bestehen. In diesem Fall sollte er aber auf "Publiziert" wechseln. 
* Wird der Anmeldeschluss auf morgen (= 10.4.2024) gesetzt, wechselt der Status korrekt auf "Publiziert"

**Comment by amaierhofer** [comment]
fixed mit 69b3dbd7a0f5be438f47de8c2f3c294629988e4a

**Comment by sykesonrocks** [comment]
@amaierhofer Ich kann bestätigen, dass der Statuswechsel für https://sac-cas.puzzle.ch/de/groups/1/events/5 automatisch vorgenommen wurde. Der Status lautet im Moment "Anmeldung abgeschlossen". 
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/a236eb10-c2e3-483e-a320-cc6644bb76bf)
Ich kann auch bestätigen, dass wenn ich das Anmeldedatum anpasse, dass der Status auf "Publiziert" zurück wechselt:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/b24b059c-d70d-4d63-9dcb-b7bb3162f398)

Somit OK!
