### ISSUE TITLE
EVENTS: Statuswechsel

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#362]
Als Kursadmin im SAC Wagon
möchte ich explizitie Buttons haben, um den Kursstatus zu ändern,
so dass abhängige Aktionen explizit getriggert werden müssen.

# Tech-Spec

In der Toolbar eines Kurses erscheint an erster Stelle ein oder mehrere Buttons, um den Status zu ändern. Dabei werden potentiell weitere Aktionen ausgelöst (in weiteren Tickets spezifiziert). Es gibt folgende Übergänge ("[Status]: [mögliche Buttons]"; siehe auch #245):

- Entwurf: Publizieren
- Publiziert: Anmeldung pausieren; Zurück als Entwurf; Absagen
- Anmeldung pausiert: Publizieren (falls Anmeldefenster noch offen ist, sonst gelang der Kurs in den Status Anmeldung abgeschlossen. Falls ein anderer Status gewünscht wird, kann dieser von dort ausgehend über die Buttons manuell erreicht werden.)
- Anmeldung abgeschlossen: Zuteilung abschliessen; Absagen
- Zuteilung abgeschlossen: Bereit zur Durchführung; Absagen
- Bereit zur Durchführung: Abschliessen; Absagen
- Abgesagt: Publizieren (falls Anmeldefenster noch offen ist, sonst gelang der Kurs in den Status Anmeldung abgeschlossen. Falls ein anderer Status gewünscht wird, kann dieser von dort ausgehend über die Buttons manuell erreicht werden.)
- Abgeschlossen: Bereit zur Durchführung

Das Feld "Status" im Bearbeitenformular wird entfernt. Dazu kann das Feld im Core in ein eigenes Partial extrahiert werden, welches vom Wagon ohne Inhalt überschrieben wird.

Vor dem Statuswechsel können auch noch bestimmte Validierungen geprüft werden (#230). Falls diese fehlschlagen, wird eine entsprechende Flash Meldung angezeigt. Der Status bleibt in diesem Fall unverändert.

# ToDo

- [x] Domainklasse erstellen
- [x] View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez 
_Anmeldung pausiert: Publizieren_ --> falls Anmeldefenster noch offen ist, sonst gelang der Kurs in den Status Anmeldung abgeschlossen. Falls ein anderer Status gewünscht wird, kann dieser von dort ausgehend über die Buttons manuell erreicht werden.

**Comment by codez** [comment]
> Gemäss Spezifikation können alle Stati manuell gesetzt werden, mit Ausnahme von Anmeldung abgeschlossen, was Sinn ergibt. 

@sykesonrocks Ist das eine Feststellung oder muss noch irgendetwas angepasst werden?

**Comment by tobiasstern** [comment]
Spezifikation passt so für die Umsetzung. Die Aktionen Anmeldung abgeschlossen: **Zuteilung abschliessen** und Bereit zur Durchführung: **Abschliessen** waren zwar nicht in der Jira-Spez drin aber sind sinnvolle Ergänzungen.

@codez Dieses Ticket hier behandelt ja die manuellen Statuswechsel via Aktionsbutton. Gibt es auch ein anderes Ticket für die automatischen Statuswechsel? Und die Spez der ausgelösten Aktionen durch die Statuswechsel, gibt es die bereits (du hast oben geschrieben "in weiteren Tickets spezifiziert")?

**Comment by ThomasEllenberger** [comment]
Da dieses Ticket noch im Progress ist, kann  das gerne gleich noch mit erledigt werden (ist durch die Komentare hier auch gut dokumentiert).

@codez Kannst du die entsprechenden Anforderungen auch noch in den Techspec übernehmen und dies bei der Umsetzung entsprechend berücksichtigen?

**Comment by codez** [comment]
@TheWalkingLeek Kannst du bitte die zwei zusätzlichen Übergänge (s.o.) noch einbauen?

**Comment by mtnstar** [comment]
dropdown button mit exchange-alt icon einbauen

**Comment by tobiasstern** [comment]
@mtnstar Die beiden Statusübergänge aus meinem Kommentar unten sind nicht umgesetzt. Wurde das vergessen?

> Gemäss aktuellem Statuskonzept https://miro.com/app/board/uXjVKNxrsFE=/?share_link_id=400309719998 braucht es noch die beiden Übergänge:
> 
> * Zuteilung abgeschlossen: Zurück zur abgeschlossenen Anmeldung (zurück zu "Anmeldung abgeschlossen")
> * Bereit zur Durchführung: Zurück zur Zuteilung (zurück zu "Zuteilung abgeschlossen")
> 
> Für den Fall, dass man den Status aus Versehen gesetzt hat.
> 
> **TBD ob dies in eigenem Ticket nachgeliefert wird, Diskussion mit Scrum Master @ThomasEllenberger noch offen.**

**Comment by tobiasstern** [comment]
> @mtnstar Die beiden Statusübergänge aus meinem Kommentar unten sind nicht umgesetzt. Wurde das vergessen?
> 
> > Gemäss aktuellem Statuskonzept https://miro.com/app/board/uXjVKNxrsFE=/?share_link_id=400309719998 braucht es noch die beiden Übergänge:
> > 
> > * Zuteilung abgeschlossen: Zurück zur abgeschlossenen Anmeldung (zurück zu "Anmeldung abgeschlossen")
> > * Bereit zur Durchführung: Zurück zur Zuteilung (zurück zu "Zuteilung abgeschlossen")
> > 
> > Für den Fall, dass man den Status aus Versehen gesetzt hat.
> > **TBD ob dies in eigenem Ticket nachgeliefert wird, Diskussion mit Scrum Master @ThomasEllenberger noch offen.**

Wird nach Rücksprache mit Päscu in einem neuen Ticket erledigt.
