### ISSUE TITLE
PEOPLE: Mitgliedschaft Willkommens E-Mail

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#364]

**Comment by mtnstar** [comment]
Aktuell erhält ein Mitglied folgendes Mail beim Beitritt:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/f0cc4706-cda3-47ed-9cfc-a9b0ff21fba9)

**Comment by daniel-illi** [comment]
ersetzt durch #941
