### ISSUE TITLE
GROUPS: E-Mail Kursadministration

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#365]
Als Verbandsadmin im SAC Wagon
möchte ich ein Feld auf dem Nationalverband haben, 
um die E-Mail Adresse der Kursadministration zu hinterlegen

Neu soll auf dem Nationalverband ein Mounted Attribute vom Typ String namens "E-Mail Kursadministration" vorhanden sein. Dieses erscheint im Tab SAC/CAS Attributes.

# ToDo

- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben

**Comment by sykesonrocks** [comment]
Ich kann bestätigen, dass das Feld "E-Mail Kursadministration" auf dem Top-Layer SAC/CAS konfigurierbar ist: 
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/51867aed-9262-4b3a-876c-b47cc17e640f)
Ich schliesse hiermit das Ticket.
