### ISSUE TITLE
EVENTS: Kursfragen nach x Monaten automatisch löschen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#367]
Als Kursadmin 
möchte ich dass die Antworten zu den Kursfragen nach x Monaten automatisch gelöscht werden,
um potentiell sensitive Daten nicht unbeschränkt aufzubewahren.

Es gibt ein zusätzliches Setting `event.participations.delete_answers_after_months`

Neu sollen im `Event::ParticipationCleanupAnswersJob` alle Antworten gelöscht werden, wenn der Kurs länger als die konfigurierten Anzahl Monate her ist. Analog `Event::ParticipationCleanupJob` (hitobito/hitobito#2129) und hitobito/hitobito#2238. Falls das Setting nil ist, returned der Job unmittelbar; es werden keine Antworten gelöscht.

Im SAC Wagon werden folgende Werte konfiguriert:
`Settings.event.participations.delete_additional_information_after_months = 6`
`Setting.sevent.participations.delete_answers_after_months = 6`

# ToDo

- [ ] Domainklasse anpassen
- [ ] Specs schreiben
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by tobiasstern** [comment]
Nach Rücksprache mit Pascal habe ich einen Kurs erstellt, der länger als 6 Monate zurück liegt und eine Anmeldung dafür erstellt.

@codez die Löschung scheint nicht ganz geklappt zu haben, siehe Anmeldung https://sac-cas.puzzle.ch/de/groups/1/events/22/participations/86 Die beiden Notfallkontakte sind noch da. Beim Kommentar wurde aber geleert (?), bin aber nicht sicher und teste nochmal.

**Comment by tobiasstern** [comment]
@amaierhofer Prüft der Job täglich, welche Kurse vor == 6 Monaten oder vor >= 6 Monaten geendet haben?

**Comment by tobiasstern** [comment]
![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/be63ba9f-9f56-4e46-be1c-8d5c0380e55c)

**Comment by tobiasstern** [comment]
Es wurde nur der Kommentar gelöscht, nicht aber die weiteren Anmeldeangaben. Dort können sensitive Informationen stehen, die wir nicht speichern dürfen.

@amaierhofer bitte anpassen.

**Comment by amaierhofer** [comment]
Job war nicht gescheduled, wurde mit 1ca43038649ee6d4f7a1e1a9ae5793b810b1e616 ergänzt.

**Comment by tobiasstern** [comment]
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/ff1d2585-cff7-47e1-818d-999b7fa9f862)
https://sac-cas.puzzle.ch/de/groups/1/events/22/participations/104

**Comment by tobiasstern** [comment]
Infos wurden korrekt gelöscht:


![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/5903eb82-9b0e-41ce-b806-476583191ad3)

--> Closed
