### ISSUE TITLE
PEOPLE: Verbesserungen Wechsel Stammsektion / Beitritt Zusatzsektion

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#368]
Einige Verbesserungen/Anpassungen rund um die Self Inscription

Anpassungen der Preisinfo/Beitritt ab wird mit #350 umgesetzt. Funktionalität wird geshared mit der Selbstregistrierung

## 1. Self Inscription verhindern

Zugriff auf Self Inscription Sektion > **Neuanmeldungen** / **Neuanmeldungen (zur Freigabe)** für eine Person verhindern falls:

- sie irgend eine terminierte Stammsektions-Rolle hat die noch aktiv ist
- sie bereits eine aktive Mitglied Rolle in der gleichen Sektion der aktuellen self inscription hat

## 3. Handling Familien Mitgliedschaften

Muss noch konzipiert werden:

https://github.com/hitobito/hitobito_sac_cas/issues/150#issuecomment-2003325495

Ruft eine Person mit aktiver **Mitglied (Stammsektion) (Familie)** Rolle Self-Inscription einer Sektion auf:
- soll die Person wählen können ob ein Antrag Zusatzsektion nur für die Einzelperson oder für die ganze Familie gemacht werden soll
- Für einen Wechsel der Stammsektion für nur die Person selber, muss diese erst aus dem Haushalt entfernt werden. Ansonsten erfolgt der Wechsel der Stammsektion immer für die ganze Familie

**Comment by daniel-illi** [comment]
1. Selfinscription wird bei SAC vorläufig nicht verwendet
2. mit HIT-516 umgesetzt
3. Selfinscription wird bei SAC vorläufig nicht verwendet
