### ISSUE TITLE
EVENTS: Nationale Warteliste ausblenden

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#370]
Im SAC Wagon soll das Attribut `waiting_list` aus den `used_attributes` des Kurses entfernt werden. Damit sollten keine Artefakte der nationalen Warteliste in der Ansicht "Anmeldungen" mehr sichtbar sein.

# ToDo

- [x] Model anpassen
- [x] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
OK, die nationale Warteliste ist nicht mehr sichtbar unter Anmeldungen:
![Uploading image.png…]()
