### ISSUE TITLE
EVENTS: TN-Status auf Listen anzeigen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#374]
Als Kursadmin im SAC Wagon
möchte ich auf der TN Liste eines Kurses sowie auf der Anmeldungen-Ansicht den Status aller TN sehen können

Neu soll auf der TN Liste in der letzen Spalte (über `render_extensions :list`) der TN-Status angezeigt werden (falls der Event Typ TN Status hat). 

Auch auf der Ansicht "Anmeldungen" soll bei jeder Person der TN Status als letzte Spalte angezeigt werden. Dazu muss im Core ebenfalls ein `render_extension` hinzugefügt werden.

Die Liste der zugeteilten Anmeldungen soll im Wagon neu nur nach Anmeldedatum sortiert sein (gleich wie die nicht zugeteilten).

Der bisher in den Listen nach dem Namen angezeigte Status (via Youth `Event::ParticipationDecorator#to_s_with_state`) wird für den SAC Wagon entfernt.

Falls bei der Umsetzung dieses Issues die Warnungen wegen nicht erfüllten Vorbedinungen im Tooltip nicht als HTML gerendert werden, sind die Tooltips hiermit anzupassen, dass HTML Inhalte wieder korrekt funktionieren.

# ToDo

- [ ] View/Decorator/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
@codez Bin nicht sicher, wie die letzte Zeile der Spez zu verstehen ist. Aktuell sieht es bei mir so aus:

![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/c9ac6908-d8bf-404a-b3e8-9b5913374aca)

Habe hier getestet: https://sac-cas.puzzle.ch/de/groups/1/events/36/application_market

ist das korrekt umgesetzt?

**Comment by codez** [comment]
Merci für das Feedback. Und nein, dass HTML sollte für die User nicht mehr sichtbar sein :disappointed:

**Comment by tobiasstern** [comment]
Passt
