### ISSUE TITLE
EVENTS: Abmelden mit Begründung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#375]
Im SAC Wagon sollen sich TN bis vor dem ersten Kursdatum von einem Kurs abmelden können (ausser der Kurs ist im Status annuliert). Dabei wird die Teilnahme immer in den Status "Abgemeldet" gesetzt. Ein Löschen der Teilnahme durch die TN ist nicht mehr möglich.

Auf der Teilnahme wird ein zusätzliches Feld `cancel_statement` (text) erstellt.

Der Abmeldebutton im entsprechenden Banner soll analog wie der Abmeldebutton in der Toolbar, ein Popover zur Bestätigung anzeigen. Dort steht der folgende Hinweis: "Bist du sicher, dass du mit der Abmeldung fortfahren möchtest? Eine Abmeldung kann nicht rückgängig gemacht werden. Mit der Abmeldung werden allfällige Bearbeitungs- und Annullationsgebühren in Rechnung gestellt." Darunter kann in einem Textfeld eine Begründung eingegeben werden (`cancel_statement`). Über den Bestätigungsbutton "Abmelden" wird die Abmeldung abgeschickt. Der aktuelle Zeitpunkt wird als `canceled_at` gesetzt. 

Diese Funktion ist nur möglich, wenn das bisherige Flag "Teilnehmende können sich selbst abmelden" gesetzt ist.

Neu soll im Popover beim Abmeldebutton (für Kursadmin) unterhalb des Abmeldedatums ebenfalls das Textfeld für die Begründung angezeigt werden.

Die Begründung wird auf der TN Seite unterhalb des Abmeldedatums angezeigt.

Die `cancel` Action für den TN selbst benötigt in dem Moment eine spezifische Konfiguration in der Ability, da dies bisher noch nicht möglich war.

PS: Momentan hat der Abmeldebutton in der Toolbar einen "Wackelkontakt". Nach dem ersten Öffnen des Popovers braucht es teilweise mehrere Klicks, um es erneut anzuzeigen. Dieses Problem bitte auch hierbei beheben.

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@amaierhofer 
Ich habe https://sac-cas.puzzle.ch/de/groups/1/events/12/participations/55 für den Kurs https://sac-cas.puzzle.ch/de/groups/1/events/12 angemeldet (anhand der "Imitieren"-Funktion).

Ich habe dann versucht die Person vom Kurs abzumelden:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/c0d95a95-b5cd-497a-9ba5-67926f55251c)
**Das Freitextfeld müsste ein Pflichtfeld sein.**

Wenn ich auf "Abmelden" klicke erhalte ich folgende **Fehlermeldung**:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/cf6a0a45-2b2b-45bf-bd58-43da3d202c2b)

Die Abmeldung wurde nicht vorgenommen:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/52e44192-c424-4ae1-a27f-2c9ea50dedc7)

Der **Status** der Anmeldung bleibt unverändert (auf "Bestätigt")
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/8cc0ca01-eb08-4231-8990-e7fb135f4f68)

Wenn ich auf "Trail Running" klicke, sehe ich **kein Button** um mich abzumelden:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/4cd5851f-2e79-4970-89a9-aee80f2c59da)

Die restlichen Anforderungen konnte ich noch nicht testen, da ich den **Statuswechsel von Entwurf-->Publiziert** nicht vornehmen kann (da die Personensuche / Kontaktperson keine Treffer zurück liefert).

**Comment by tobiasstern** [comment]
@amaierhofer Ich habe auf dem Kurs hier https://sac-cas.puzzle.ch/de/groups/1/events/15 das Flag gesetzt "Abmeldung möglich", aber wenn ich den TN imitiere, habe ich keinen Abmelde-Button auf der Anmeldung: https://sac-cas.puzzle.ch/de/groups/1/events/15/participations/72

Ist das ein Bug oder verstehe ich was falsch?

**Comment by tobiasstern** [comment]
@codez Bitte Besprechung mit Andreas bezüglich Pflichtfeld hier dokumentieren

**Comment by codez** [comment]
Bitte die Begründung als Pflichtfeld überprüfen.

Braucht https://github.com/hitobito/hitobito_sac_cas/issues/375#issuecomment-2084823016 auch noch eine Anpassung oder Klärung?

**Comment by tobiasstern** [comment]
Ja, das braucht bitte auch noch Klärung.

**Comment by amaierhofer** [comment]
Ich denke https://github.com/hitobito/hitobito_sac_cas/issues/375#issuecomment-2084823016 kann damit erklärt werden, dass das erste Kursdatum (22.04.2024) in der Vergangenheit liegt. Wenn ich das Datum anpasse (neu auf 13.05) erscheint der Button.

Und ich schaue noch wegen dem Pflichtfeld für die Begründung.

**Comment by amaierhofer** [comment]
Begründung ist jetzt ein Pflichfeld mit client seitiger Validierung.

**Comment by tobiasstern** [comment]
Danke für die Änderungen und Antworten, ich konnte jetzt weiter testen 🤝 

Dabei ist mir das Folgende aufgefallen aus Sicht TN.

Auf dem Kurs: 
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/63ddd550-30f4-4a06-bba0-4fb33e78ce5f)

Auf der Anmeldung:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/b1a8cbd4-0456-44f2-8ddf-0b22a089b248)

Und dazu verschwindet manchmal der Titel:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/165cd33a-559a-42f9-ba4b-06a9904f278c)

**Comment by tobiasstern** [comment]
Ein Fehler ist aber noch, dass ich auf dem Kurs dann diese info sehe, obwohl ich bereits abgemeldet bin:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/d34e4fbe-1409-4ea3-b6da-6d8caaa25792)

Ich teste hier: https://sac-cas.puzzle.ch/de/groups/1/events/15

**Comment by tobiasstern** [comment]
Wurde behoben 👍 

Somit -> closed
