### ISSUE TITLE
EVENTS: E-Mail Anmeldehinweis Kursadmin

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#379]
Als Kursadmin im SAC Wagon
möchte ich nur E-Mails zu Kursanmeldungen erhalten, wenn diese im Status "Unbestätigt" sind,
um nicht in E-Mail zu ertrinken.

Die bestehende Funktionalität mit "Kontaktperson über neue Anmeldung per Mail benachrichtigen" bleibt bestehen, funktioniert jedoch wie bisher und unabhängig von diesen E-Mails hier. 

Falls die Anmeldung im Status "Unbestätigt" ist, wird dieselbe E-Mail an die auf dem Nationalverband hinterlegten "E-Mail Kursadminstration" (#365) geschickt. Dies auch wenn obiges Flag auf dem Kurs deaktiviert ist. Dazu sollte eine entsprechende Anpassung des `Event::ParticipationNotificationJob` im SAC Wagon reichen.

# ToDo

- [ ] Domainklasse  anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Dies wurde anders gelöst als hier angedacht. -> closed
