### ISSUE TITLE
EVENTS: E-Mail Abmeldebestätigung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#380]
Als Kurs Teilnehmer:in im SAC Wagon
möchte ich eine Bestätigungs-E-Mail erhalten, wenn ich mich selbst abgemeldet habe oder abgemeldet wurde.

Die Abmeldelogik wurde im SAC Wagon angepasst (#375). Neu soll, wenn eine Teilnahme auf abgemeldet gesetzt wird (ausser vom Status "Annuliert"), das bestehende Mail mit der Abmeldebestätigung an den TN geschickt werden.

Zusätzlich soll, nur falls die Person sich selbst abmeldet, ein zweites Mail an die Kursadmin geschickt werden. Dessen Inhalt wird durch einen eigenen Text (`CustomContent`) definiert. Platzhalter sind `{event-name}, {participant-name}, {application-url}`. Diese E-Mail wird an die auf dem Nationalverband hinterlegten "E-Mail Kursadminstration" (#365) geschickt.

# ToDo

- [ ] Domainklasse erstellen oder anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Wurde in #637 umgesetzt -> closed
