### ISSUE TITLE
PEOPLE: Import MailingLists (Abos) Subscriptions Personen für Newsletter, SAC Insight, ... (aus NAV1)

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#391]
Mitglieder und andere Personen haben aktuell z.B. den SAC Newsletter abonniert oder diesen explizit abbestellt. Welche Abos eine Person abonniert oder abbestellt hat muss ebenfalls zusammen mit den Personen mit importiert werden.

## Abos

- SAC/CAS Newsletter
- SAC Insight
- Spenden aufrufe
- weitere ?

**Comment by openscript** [comment]
@ThomasEllenberger Hier warten wir noch auf die Daten, damit wir das Vorgehen spezifizieren und den Aufwand abschätzen können.
