### ISSUE TITLE
PEOPLE: Mitgliederverwaltung (Sektion/Nationalverband) fügt neues Kind einer Person/Familie hinzu

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#393]
wie kann die Mitgliederverwaltung einer Sektion oder des NV ein neues Kind zu einer Person hinzufügen?
Grundsätzlich soll das durch das Mitglied selber passieren, es sollte aber auch durch die Mitgliederverwaltung möglich sein

**Comment by daniel-illi** [comment]
Aktueller Stand ist, dass das Mitglied sich an die Geschäftsstelle wenden muss um ein Kind hinzuzufügen.
Falls es da noch Änderungen gibt, wird dies in einer späteren Jira Story geschehen.
