### ISSUE TITLE
PEOPLE: Externe erwachsene Person wird neu Familienmitglied

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#394]
1. Externe Person registriert sich für Basis Konto (gratis)
2. Mitgliederverwaltung NV fügt die Person dem Haushalt einer anderen Person hinzu

Haben wir hier an alles gedacht? 
- Basis Konto sollte nicht mehr existieren sobald Person aktives Mitglied
- Muss dieser Prozess auch durch Mitgliederverwaltung Sektion möglich sein?
- Ist es möglich unter dem Jahr in diesem Szenario von Einzel nach Familie zu wechseln? Faktura wie?

**Comment by daniel-illi** [comment]
* Basis Konto muss vom Mitarbeiter der Geschäftsstelle manuell entfernt werden
* Faktura, Beitragskategorie wechsel etc. sind in separaten stories behandelt
