### ISSUE TITLE
PEOPLE: Neuanmeldungen ablehnen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#395]
Aktuell wird bei der Ablehung einer Neuanmeldung die Rolle der Person einfach gelöscht:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/05112a41-d49a-4c32-b127-652e303448de)

Bemerkung wird als Notiz auf der Person hinterlegt:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/4a56b8cb-9f88-4e29-a6a3-5ee01fe06acc)

## Offene Punkte

- Muss die Person vollständig gelöscht werden? wenn ja, wie erkennt dann die Mitgliederverwaltung das diese Person in der Vergangenheit abgelehnt wurde?
- Darf man die Daten dieser Person beibehalten?
- Soll die Person eine Rolle in einer Blacklist Gruppe auf dem Top-Layer erhalten?

**Comment by mtnstar** [comment]
@sykesonrocks glaube dieses Feature ist nicht das dringenste, wir sollten aber trotzdem mal definieren was in diesem Fall genau passieren soll. 
Dieser Use Case das jemand abgelehnt wird kommt laut deiner Aussage sehr selten vor, wie viel Zeit wollen wir hier investieren?

**Comment by daniel-illi** [comment]
ersetzt durch https://github.com/hitobito/hitobito_sac_cas/issues/681
