### ISSUE TITLE
PEOPLE: Selbstregistrierung Telefon Beispiel Platzhalter

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#411]
Bitte bei ALLEN Selbstregistrierungsformularen wie bereits z.B. in #305 spezifiziert bei Telefon anstatt nur Nummer eine Beispiel-Nummer als Platzhalter anzeigen. (das war soweit ich weiss mal so implementiert, einem Merge zum Opfer gefallen?)

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/e5a0d78c-5b80-48b9-910a-ef2a494ab244)

**Comment by sykesonrocks** [comment]
@mtnstar Können wir dieses Ticket bitte kommenden Donnerstag am CoWorking-Tag besprechen, bevor wir dies in Umsetzung weitergeben? Ich habe diverse Feedbacks von Marketing erhalten, die ich mit dir durchgehen möchte:
- https://saccas.atlassian.net/browse/HIT-273
- https://saccas.atlassian.net/browse/HIT-274
