### ISSUE TITLE
PEOPLE: Sektion Selfreg vergisst housemates

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#415]
### Aktuelles Verhalten

Im Selfreg Wizard mit erfassten Familienmitglieder, wenn von der letzten Wizard Seite zurück auf die erste Seite navigiert wird mit dem "Zurück" Button, und danach wieder vorwärts, dann fehlen die erfassten Familienmitglieder (das Formular ist wieder leer).

### Gewünschtes Verhalten

Housemates bleiben erhalten beim hin und her navigieren.

### TODO

- [x] fix
- [x] feature spec aktualisieren (beim TODO comment): spec/features/signup/sektion_spec.rb:636

**Comment by ThomasEllenberger** [comment]
Gemäss Jira wurde das am 04.09.2024 erfolgreich getestet und scheint wieder zu funktionieren.
Kann dieses Ti
cket abgeschlossen werden?

**Comment by njaeggi** [comment]
Ist noch nicht gefixed, auf der Int besteht der Bug noch, ich vermute das beim Testen nur ein Schritt zurück getsestet wurde, der Bug passiert erst sobald man zwei Schritte nach hinten und zwei Schritte nach vorne navigiert.
