### ISSUE TITLE
PEOPLE: Mitgliederausweis Druckvorlage

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#419]
- A4, vorderseite, rückseite
- Der neue Ausweis soll mehrjährig sein
- Unterschiede zu aktuellem Papierausweis:
  - kein Jahr mehr (2024)
  - ohne Mitgliederjahre
  - ohne Auflistung Sektionen
  - ohne PUK
  - ohne QR-Code auf der Rückseite
  - neu mit dem Hitobito QR Code auf der Vorderseite
  - wie best. Ausweis mit: Gegenrechtslogo, Sponsorenlogos, www.sac-cas.ch, Notfallnummer, REGA, SOS Europe, SAC Logo, usw.
- PDF soll unter person#show > Export > SAC Mitgliederausweis PDF heruntergeladen werden können

**Comment by daniel-illi** [comment]
abgelöst durch #530
