### ISSUE TITLE
PEOPLE: Mitgliederausweis QR Code via API/download zur Verfügung stellen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#420]
- PDF mit Verify QR Code soll unter person#show > Export > SAC Mitglieder-QR-Code PDF heruntergeladen werden können
- PDF enthält einfach nur den QR Code auf einer A4 Seite (Grösse muss noch definiert werden), Für Print-At-Home
-

**Comment by daniel-illi** [comment]
Das "analoger Mitgliederausweis" PDF aus HIT-41/#530 enthält bereits diesen QR code.
