### ISSUE TITLE
EVENTS: Neues Feld Kursstufe

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#452]
Neu soll im SAC Wagon auf der Kursstufe ein Feld "Beschreibung" / `description` (Text, mehrsprachig) vorhanden sein. 

Das Feld wird ebenfalls im API Endpoint zu den Kursstufen zurückgegeben.

# ToDo

- [ ] Migration erstellen
- [ ] Model/View/Controller anpassen
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
OK
