### ISSUE TITLE
EVENTS: Weitere Felder

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#453]
Im SAC Wagon sollen folgende zusätzliche Felder auf dem Kurs hinzugefügt werden:

Im Formular in einem neuen Tab "Kommunikation":

* “Kurzbeschreibung“: `brief_description`, Text, mehrsprachig
* “Besonderes“: `specialities`, Text, mehrsprachig
* “Vergleichstouren“: `similar_tours`, Text, mehrsprachig
* “Programm“: `program`,  Text, mehrsprachig

Unterhalb Unterkunft:
* “Verpflegung“: `meals`, Drop-Down, mögliche Werte: Frühstück; Halbpension; Lunch; selbst gekochte Mahlzeiten; Vollpension (`breakfast`, `half_board`, `lunch`, `self_cooking`, `full_board`)

Nach Link Umfrage (wird auf Show Seite nicht angezeigt):
* “Rabattcode Buchversand”: `book_discount_code`, String

Alle Felder ausser "Rabattcode Buchversand" werden ebenfalls im Events JSON API hinzugefügt.

Das Feld "Motto" soll nicht angezeigt werden.

# ToDo

- [x] Migration erstellen
- [x] Model/View/Controller anpassen
- [x] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez @amaierhofer Die Felder werden in der Kurserfassungsmaske angezeigt und das Feld "Motto" wurde entfernt. Die API wurde gemäss Swagger UI noch nicht angepasst, sprich die neuen Felder sind noch nicht integriert und das Feld "Motto" ist noch ersichtlich:
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/6596449f-8290-44d4-b3e2-97b409f95464)
Falls meine Aussage falsch ist und die Anpassungen in der API vorgenommen wurden, könnte ihr das Ticket direkt schliessen (unassigned).

**Comment by codez** [comment]
@sykesonrocks Weiter unten in der Swagger Dok gibt es noch einen Typ `courses`. Dort sind die neuen Attribute drin. 

Die ausgeblendeten Attribute erscheinen im API weiterhin, da sich diese hier nicht so einfach entfernen lassen.
