### ISSUE TITLE
INVOICES: Parameter Zentralverband

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#471]
Als Zentralverbandsadmin möchte ich die Parameter für die Mitgliedsrechnungen verwalten können.

Diese Parameter sind versioniert und können pro Kalendarjahr wechseln, müssen aber nicht.

# Model

Der Einfachheit halber halten wir das Model flach in einer Tabelle `sac_membership_configs`:

- Gültig ab / `valid_from` (integer, not null, 4 digits, unique)

Folgende Attribute sind alle Frankenbeträge und entsprechend decimal, 2 Nachkommastellen, not null:
- Zentralverbandsbeitrag, Einzelmitgliedschaft / `sac_fee_adult`
- Zentralverbandsbeitrag, Familienmitgliedschaft / `sac_fee_family`
- Zentralverbandsbeitrag, Jugendmitgliedschaft / `sac_fee_youth`
- Eintrittsgebühren, Einzelmitgliedschaft / `entry_fee_adult`
- Eintrittsgebühren, Familienmitgliedschaft / `entry_fee_family`
- Eintrittsgebühren, Jugendmitgliedschaft / `entry_fee_youth`
- Hüttensolidaritätsbeitrag Sektion mit Hütten, Einzelmitgliedschaft / `hut_solidarity_fee_with_hut_adult`
- Hüttensolidaritätsbeitrag Sektion mit Hütten, Familienmitgliedschaft / `hut_solidarity_fee_with_hut_family`
- Hüttensolidaritätsbeitrag Sektion mit Hütten, Jugendmitgliedschaft / `hut_solidarity_fee_with_hut_youth`
- Hüttensolidaritätsbeitrag Sektion ohne Hütten, Einzelmitgliedschaft / `hut_solidarity_fee_without_hut_adult`
- Hüttensolidaritätsbeitrag Sektion ohne Hütten, Familienmitgliedschaft / `hut_solidarity_fee_without_hut_family`
- Hüttensolidaritätsbeitrag Sektion ohne Hütten, Jugendmitgliedschaft / `hut_solidarity_fee_without_hut_youth`
- Abogebühr SAC Magazin, Einzelmitgliedschaft / `magazine_fee_adult`
- Abogebühr SAC Magazin, Familienmitgliedschaft / `magazine_fee_family`
- Abogebühr SAC Magazin, Jugendmitgliedschaft / `magazine_fee_youth`
 _

- Dienstleistungsgebühr / `service_fee` (fehlt noch im Mockup)
- Porto Ausland SAC Magazin / `magazine_postage_abroad`
_

- ~~Jugendmitgliedschaft ab Alter / `youth_age_minimum` (integer,  not null)~~ wird nicht umgesetzt
- ~~Jugendmitgliedschaft bis Alter / `youth_age_maximum` (integer,  not null)~~
- ~~Kindermitgliedschaft ab Alter / `child_age_maximum` (integer,  not null)~~
- ~~Kindermitgliedschaft bis Alter / `child_age_maximum` (integer,  not null)~~
_

- Reduktionsbetrag  / `reduction_amount`
- Reduktion ab Mitgliedsjahren / `reduction_required_membership_years` (integer, nullable)
_

- Zentralverbandsbeitrag, Artikelnummer / `sac_fee_article_number` (string, not null)
- Zentralverbandseintrittsgebühren, Artikelnummer / `sac_entry_fee_article_number` (string, not null)
- Hüttensolidaritätsbeitrag, Artikelnummer / `hut_solidarity_fee_article_number` (string, not null)
- Abogebühr SAC Magazin, Artikelnummer / `magazine_fee_article_number` (string, not null)
- Porto Ausland SAC Magazin, Artikelnummer / `magazine_postage_abroad_article_number` (string, not null)
- Sektionsbeitrag, Artikelnummer / `section_fee_article_number` (string, not null)
- Sektionseintrittsgebühren, Artikelnummer / `section_entry_fee_article_number` (string, not null)
- Porto Ausland Sektionsbulletin, Artikelnummer / `section_bulletin_postage_abroad_article_number` (string, not null)
- Servicegebühr, Artikelnummer / `service_fee_article_number` (string, not null)
- Ausgleichszahlungen, Artikelnummer / `balancing_payment_article_number` (string, not null)
- Kursbeitrag, Artikelnummer / `course_fee_article_number` (string, not null)
_

- Rabattdatum 1 / `discount_date_1` (string, null, Format `/\A[0123]?\d\.[012]?\d\.\z/`)
- Rabattprozent 1 / `discount_percent_1` (integer, null)
- Rabattdatum 2 / `discount_date_2` (string, null, Format s.o.)
- Rabattprozent 2 / `discount_percent_2` (integer, null)
- Rabattdatum 3 / `discount_date_3` (string, null, Format s.o.)
- Rabattprozent 3 / `discount_percent_3` (integer, null)

# View

Der Titel der Seite ist immer "Parameter für Mitgliedschaftsrechnungen". Die Seite wird als Sheet unterhalb der Gruppe angezeigt, so dass der Gruppenname weiterhin ersichtlich ist.

## Navigation

Da die Parameter nur selten bearbeitet werden müssen, erfolgt die Navigation über das Dropdown des "Bearbeiten" Buttons der Gruppe (nur auf der Root Gruppe "SAC / CAS"). Dort gibt es einen neuen Eintrag "Parameter Mitgliedsrechnungen".

## Formular

Die Felder sollen gemäss folgendem Mockup angeordnet werden:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/271590/aae5368e-984f-455b-9624-0a4335d84404)

Es gab noch kleinere Anpassungen an den Feldern. Die Liste oben ist verbindlich, das Mockup dient nur der Visualisierung.

## Auswahl Jahr

Es wird direkt das Formular mit den Parametern des aktuellen Jahres angezeigt, bzw. mit dem grössten `valid_from`, das kleiner gleich dem aktuellen Jahr ist.

Über eine Jahres-Pagination-Navigation analog bei Anlässen kann auf die Parameter von anderen Jahren navigiert werden. Es werden allerdings nur die in der DB existierenden `valid_from` Jahre aufgelistet. Möglicherweise reicht es, in `year_range` einen Array der vier "nähesten" und auch existierenden Jahre zurückzugeben. Falls nicht, kann das bestehende `page_per_year` Partial kann kopiert und entsprechend angepasst werden. 

Um Parameter ab einem noch nicht existierenden Jahr zu verändern, gibt es in der Toolbar einen Button "Für neues Jahr konfigurieren". Dadurch gelangt man auf die `new` Action. Dort ist zuoberst das Feld "Gültig ab" sichtbar, wo das entsprechende Jahr eingetragen werden kann. Die Werte des zuvor angezeigten Jahres werden in die Inputs übernommen. 

Falls noch kein Datensatz existiert, wird direkt das `new` Formular angezeigt.

Es gibt keine Index, Show oder Destroy Actions.

# ToDo

- [x] Migration erstellen
- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Das Form ist das https://sac-cas.puzzle.ch/de/groups/1/sac_membership_configs/new und funktioniert. 

@mtnstar Ich sehe viele Abweichungen von der Spez hier. Ist das mit Stefan besprochen worden?

**Comment by mtnstar** [comment]
> Das Form ist das https://sac-cas.puzzle.ch/de/groups/1/sac_membership_configs/new und funktioniert.
> 
> @mtnstar Ich sehe viele Abweichungen von der Spez hier. Ist das mit Stefan besprochen worden?

welche Abweichungen denn? Das Mockup ist  nicht massgebend bezüglich den Feldern, das ist explizit so erwähnt.

**Comment by tobiasstern** [comment]
@mtnstar Die Labels sind zum Teil anders als oben aufgeführt, der Button "Für neues Jahr konfigurieren" ist nicht da, Artikelnummern für Sektionsbeitrag, Ausgleichszahlungen und Kursbeitrag fehlen, Artikelnummer für Porto Ausland Sektionsbulletin ist zweimal da (eins davon ist wahrsch. SAC Magazin).

**Comment by codez** [comment]
Die `discount_percent` haben `length: 2`. Kann damit auch ein Rabatt von 100% eingetragen werden?
