### ISSUE TITLE
PEOPLE: Globale Suche nach Mitgliedernummer

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#476]
Als User im SAC Wagon möchte ich Personen nach Mitgliedernummer suchen können.

# Tech-Spec

In der globalen Suche soll die Suche nach Mitgliedernummer möglich sein. Ausserdem soll bei den Resultaten die Mitgliedernummer ebenfalls angezeigt werden.

# ToDo

- [ ] Domainklasse anpassen
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
@codez 
Bitte folgende Anforderungen mit berücksichtigen:
**Alle Suchresultate gilt es anzuzeigen. Falls keine Treffer gefunden werden, soll der Nutzer darüber informiert werden. Die passendsten Treffer gilt es zuoberst anzuzeigen. Die Suche nach Vorname, Nachname, E-Mail Adresse, Personen ID, Geburtsdatum muss möglich sein.**

Beispiel
Wenn ich unter https://sac-cas.puzzle.ch/de/groups/1/roles/new die Person "Martin Schmid" versuche hinzuzufügen, wird mir folgende Person in den Suchergebnissen nicht angezeigt: https://sac-cas.puzzle.ch/de/people/252249. Die Suchresultate sollten nicht auf eine bestimmte Anzahl Treffer beschränkt sein. Ich erwarte, dass 252249 zuoberst in den Suchresultaten angezeigt wird. Generell erwarte ich zuoberst alle gefundenen Personen mit dem Namen "Martin Schmid". Heute werden mir zuoberst Personen wie z.B. Breischmid, Fischer-Schmid, Martina, Hofer-Schmidhauser, Kupferschmid, Angelique angezeigt. Zudem kann aktuell nur mit dem Vor- und Nachnamen oder der Ortschaft gesucht werden. Die Suche basierend auf E-Mail Adresse, Mitgliedernummer und Geburtsdatum ist heute nicht möglich.

**Comment by codez** [comment]
@sykesonrocks Ich habe entsprechende weitere Tickets erstellt: #477, #478, #479. Insbesondere die Anpassung der Reihenfolge ist eher aufwändig. 

Die Anzahl Treffer müssen wir einschränken, da wir nicht alle 10000 "Peter" laden und darstellen können. Der maximal sinnvolle Werte erachte ich als 20 Treffer.

**Comment by sykesonrocks** [comment]
@codez Danke. Allenfalls würde es Sinn machen, beim 20. Treffer den Text "Weitere Treffer anzeigen" auszuweisen und wenn der User darauf klickt, werden alle Suchergebnisse in einer separaten Seite ("Suchresultate" oder "Gefundene Personen") dargestellt.

**Comment by mtnstar** [comment]
@codez Suche nach Mitglieder-Nr wurde schon länger implementiert und funktioniert auch so weit.
in #477 ist die gleiche Anforderung auch nochmals aufgelistet.
was muss denn genau mit diesem Ticket hier gemacht werden?
einfach nur die Mitglied-Nr bei den Suchresultaten anzeigen?

**Comment by codez** [comment]
Das Ticket hier betrifft die "Globale Suche" zuoberst im Layout, welche über Sphinx läuft. #477 betrifft die Suche nach Personen in Formularen, welche über den `Person::QueryController` geht.

Falls die Suche nach Mitgliedernummer bereits funktioniert, müsste diese in dem Fall hiermit noch angezeigt werden.

**Comment by sykesonrocks** [comment]
Funktioniert einwandfrei: die Mitgliedernummer wird in den Suchresultaten mit angezeigt und die Suche nach Mitgliedernummer ist möglich.
