### ISSUE TITLE
PEOPLE: Weitere Felder in Personensuche berücksichtigen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#477]
Als User im SAC Wagon möchte ich Personen in Formularen zusätzlich nach Mitgliedernummer, Geburtsdatum und E-Mail Adresse suchen können (`Person::QueryController`).

In der Spalte Mitgliedernummer (`id`) wird nur für diejenigen Suchtokens gesucht, welche ausschliesslich Zahlen enthalten. Die Spalte muss möglicherweise dazu als String gecastet werden.

In der Spalte Geburtsdatum wird nur für diejenigen Suchtokens im folgenden Format gesucht: "d.m.", "d.m.y", "y". Die Spalte muss wohl als String im Format "d.m.y" (ohne vorgestellte 0 bei Tag und Monat) gecastet werden.

Da das Feld `nickname` kann aus den Suchspalten entfernt werden, da es im SAC nicht verwendet wird.

Bei der Anzeige der Suchresultate soll nach dem Geburtsjahr auch noch die Mitgliedernummer angezeigt werden. Beispiel: "Max Muster, Bern (1990; 1235432)"

Die maximale Anzahl Suchresultate wird auf  20 erhöht.

Die Suche sollte bei 200'000 Personen nicht mehr als 5 Sekunden dauern.

# ToDo

- [ ] Controller anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by amaierhofer** [comment]
Antwortzeiten waren bei mir lokal mit ca 205.000 Personen unter 300ms

**Comment by sykesonrocks** [comment]
@amaierhofer @codez  Die Suche nach Name, Mitgliedernummer, E-Mail funktioniert in der globalen Personensuche einwandfrei. Es performt sehr gut. Die Suche aber nach Geburtsdatum funktioniert nicht (immer). Wenn ich nach meinem Geburtsdatum suche (04.06.1990), erhalte ich keine Resultate zurück. Das gleiche Verhalten erhalte ich, wenn ich das Datum als 4.6.1990 eingebe. Mit 1990 werden mir Treffer angezeigt.
![image](https://github.com/hitobito/hitobito_sac_cas/assets/132900428/0555106a-9a01-471a-a924-6e79a18aeb37)

**Comment by amaierhofer** [comment]
@sykesonrocks eventuell gibt es hier ein Missverständniss. Das Ticket beschreibt die Suche von Personen in Formularen und nicht in der globalen Suche wie in deinem Beispiel. Für die ergänzung vom Geburtsdatum in der globalen Suche sollten wir ein neues Ticket machen.

**Comment by ThomasEllenberger** [comment]
@codez Kannst du hierfür ein neues Github Issue eröffnen? Kann dem gleichen Jira Ticket angehängt werden. Suche nach Geburtsdatum ist meines Erachtens eine Anforderung von HIT-88 für alle Suchen.
