### ISSUE TITLE
PEOPLE: Feedback Personensuche

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#478]
Als User möchte ich mehr Feedback, wenn ich in einem Formular eine Person suche.

Neu soll sobald eine Sucheingabe bei einer Personensuche eingegeben wurde, ein Activity Indicator angezeigt werden. Das kann im einfachsten Fall ein Dropdown mit dem Eintrag "Suche läuft..." sein. Sobald ein Resultat geladen wurde, kann dieses mit dem bestehenden Resultate-Dropdown ersetzt werden. Falls die Suche keine (0) Resulate liefert, soll im Dropdown "Keine Personen gefunden" stehen.

# ToDo

- [x] View anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by sykesonrocks** [comment]
Funktioniert einwandfrei - leichte Abweichungen zur Spezifikation: 
- "Suche läuft.." wird als Text nicht dargestellt, sondern ein Timer-Icon.
- Wenn keine Personen gefunden werden, wird der User im Drop-Down nicht informiert ("Keine Personen gefunden").
- Der User kann aber auf Enter drücken und so auf die Ergebnisse gelangen (analog Google Suchmaschine) - dort steht dann "Keine Einträge gefunden".
