### ISSUE TITLE
ROLES: Für Tourenleiter*in Qualifikationen prüfen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#481]
Als Rollenersteller im SAC Wagon möchte ich gehindert werden, eine Tourenleiter*in Rolle zu erstellen, wenn die entsprechende Person über keine Qualifikationen verfügt.

Neu soll beim Erstellen einer Rolle "Tourenleiter*in" validiert werden, dass die Person zum Startzeitpunkt der Rolle mindestens eine aktive Qualifikation hat. Andernfalls wird ein Validierungsfehler angezeigt und die Rolle kann nicht erstellt werden.

# ToDo

- [ ] Model anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Habs kurz angeschaut. Fehler wird korrekt angezeigt, vgl Bild:

![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/83febcb1-bb07-4280-9826-7de1bd9fe88c)

Wenn ich jedoch ein Startzeitpunkt in der Zukunft wähle, kann ich die Rolle hinzufügen. Obwohl keine Quali.

Habe jetzt testweise eine Tourenleiter-Rolle hinzugefügt für ab morgen und prüfe morgen, was der Effekt ist im System. 
https://sac-cas.puzzle.ch/de/groups/1603/people/255725

**Comment by tobiasstern** [comment]
Tag danach: Die Rolle wurde bei den zukünftigen Rollen belassen und entsprechend markiert, vgl. Bild:

![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/437a7624-663c-4b8c-9df9-30a19e2bfb5b)


Und wenn man die Rolle editiert wird ebenfalls die Warnung bzw. der Fehler angezeigt:

![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/b01ffda3-ed31-468a-b832-bcf2c2aef6db)

Spec somit erfüllt und -> closed
