### ISSUE TITLE
ROLES: Tourenleiter*in automatisch terminieren

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#483]
Als Tourenchef im SAC Wagon möchte keine Personen ohne Qualifikationen mit der Rolle Tourenleiter*innen.

Neu soll ein nächtlicher Job bei allen Personen mit der Rolle Tourenleiter*in, welche keine (beliebige) aktive Qualifikation haben, diese Rolle per Vortag terminieren. Der Job soll täglich kurz nach Mitternacht laufen.

# ToDo

- [x] Jobklasse erstellen und schedulen
- [x] Specs schreiben

**Comment by tobiasstern** [comment]
Test in progress:

Habe heute hier die Rolle hinzugefügt: https://sac-cas.puzzle.ch/de/groups/901/people/419597 sollte morgen gelöscht sein.
Zum Vergleich auch hier hinzugefügt: https://sac-cas.puzzle.ch/de/groups/901/people/372831 sollte morgen noch da sein.

**Comment by tobiasstern** [comment]
Test erfolgreich.

Auf dem Profil 1 ohne Quali wurde die Rolle heute Nacht gelöscht. 
Auf dem Profil 2 mit Quali blieb die Rolle.

-> Closed
