### ISSUE TITLE
PEOPLE: Flag Digitaler Mitgliederausweis / Rechnungen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#485]
Als SAC Person möchte ich in meinen Daten einstellen können, ob ich den Mitgliederausweis sowie allfällige Rechnungen digital oder in Papierform erhalte.

Neu soll auf der Person das Boolean Flag `digital_correspondence` vorhanden sein. Default ist true. 

Im Bearbeiteformular erscheint es mit dem Label "Mitgliederausweis & Rechnungsstellung" und den beiden Radios "digital" (true) und "print" (false).

Auf der Show Seite wird es unter weiteren Angaben ebenso angezeigt.

Wenn ein initiales Passwort gesetzt wird (Passwort ändert von `blank?` auf `present?`), soll das Flag automatisch auf true gesetzt werden.

# ToDo

- [x] Migration erstellen
- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Funktioniert noch nicht ganz, bitte beheben.

**Comment by daniel-illi** [comment]
@tobiasstern korrigiert und auf INT deployt

**Comment by tobiasstern** [comment]
Funktioniert soweit gut 👍 

Der letzte Teil der Spezifikation "_Wenn ein initiales Passwort gesetzt wird (Passwort ändert von blank? auf present?), soll das Flag automatisch auf true gesetzt werden._" kann ich grad nicht testen, weil das self_registration kaputt ist.

**Comment by tobiasstern** [comment]
Ich habe doch noch etwas gefunden. Im Log ist es unklar, was wie gewechselt wurde, siehe Bild:

![Image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/a68e52af-70e6-416f-afa2-5f6cc48a0bc8)

@daniel-illi kannst du dies bitte so anpassen, dass klar ist, was gewechselt wurde? Es ist zwar nicht in der Spez. oben und ev. hast du dies mit Stefan anders besprochen. Ich habe den Punkt mit dem Log in der Jira Story gefunden https://saccas.atlassian.net/browse/HIT-79 und finde es aktuell nicht gut gelöst.

**Comment by daniel-illi** [comment]
@TheWalkingLeek könntest du bitte noch anpassen, wie die Papertrail Version im Log dargestellt wird? (Siehe vorheriger Kommentar von @tobiasstern)

Auf die schnelle habe ich nicht herausgefunden, ob wir das schon an anderen Stellen in Hitobito machen.
Ich denke du kannst hier customizen abhängig von model class und attr: `PaperTrail::VersionDecorator#normalize`
