### ISSUE TITLE
INVOICE: Mitgliedschaftsrechnung zusammenstellen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#502]
Als MV möchte ich für eine Person eine Mitgliedsschaftsrechnung automatisch erzeugen lassen.

In diesem Ticket wird erst die Funktionalität bereit gestellt. Die Integration ins Frontend oder ein Jahresinkassojob, welcher gewisse Vorbereitungen macht, erfolgt erst später.

Grundlage ist die [Referenzimplementation in Go](https://github.com/saccas/invoicing_reference_implementation). Diese soll in hitobito abgebildet werden. Entscheidend ist, dass bei gleichem Input der gleiche Output herauskommt, nicht eine 1:1 Nachimplementation auf Code Ebene. Einstiegspunkt ist die Methode [CentralAssociation->CollectPerson](https://github.com/saccas/invoicing_reference_implementation/blob/d7d9483b59cf17e214caaf31bc5fbb5603c439f4/central_association.go#L139).

Das `increaseMembershipYears` Argument brauchen wir nicht, da wir die Mitgliedschaftsjahre immer per Stichdatum berechnen.

Als Output wird pro Person eine Liste von Rechnungspositionen erwartet. Diese können auch den Betrag 0.0 aufweisen (z.B. für zusätzliche Familienmitglieder) oder für andere Rechnungsempfänger sein (z.B. Sektion).

## Datenmapping

Die Datenstrukturen der Referenzimplementation sind soweit selbsterklärend. Folgende Attribute aus Go werden in hitobito besonders abgebildet:

### Person

* `Age` -> Alter der Person per Ende Jahr des Stichdatums
* `LivingAbroad` -> `!person.swiss?`
* `Membership` -> Erste per Stichdatum aktive `Group::SektionsMitglieder::Mitglied` Rolle auf Person
* `MembershipYears` -> `person.membership_years` per Stichdatum, abgerundet auf eine Ganzzahl
* `AdditionalMemberships` -> Alle per Stichdatum aktive `Group::SektionsMitglieder::MitgliedZusatzsektion` Rollen auf Person
* `IsHonoraryMemberOfCentralAssociation` -> Existiert per Stichdatum eine aktive `Group::Ehrenmitglieder::Ehrenmitglied` Rolle auf Person? (siehe #503)
* `PhysicalAlpsMagazinOptOut` -> Ist die Person auf dem Abo `Group.root.sac_magazine_mailing_list_id` subscribed? (siehe #504)

### Membership

* `FamiliyAccountant` -> `person.family_main_person` (siehe #493)
* `IsHonoraryMember` -> Existiert per Stichdatum eine aktive `Group::SektionsMitglieder::Ehrenmitglied` Rolle derselben Sektionsgruppe auf Person?
* `IsBeneficiaryMember` -> Existiert per Stichdatum eine aktive `Group::SektionsMitglieder::Beguenstigt` Rolle derselben Sektionsgruppe auf Person?

### Section

* `HasHuts` -> Sektion hat indirekte Untergruppen vom Typ 'Group::SektionsHuette` in derselben Ebene

# ToDo

- [x] Domainklasse erstellen
- [x] Specs schreiben

**Comment by amaierhofer** [comment]
@codez ich bekomme ein 404 beim Link zur Go implementierung, ich nehme an die ist privat ..

**Comment by codez** [comment]
Die aktuellen Rechnungspositionen können pro Person getestet werden, in dem bei der URL einer Person `/membership_invoice_positions` angehängt wird (also z.B. `https://sac-cas.puzzle.ch/de/groups/881/people/498182/membership_invoice_positions`). Damit kann ein CSV der entsprechenden Positionen heruntergeladen werden.
