### ISSUE TITLE
PEOPLE: Bemerkungsfelder in API

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#518]
~blocked by #511~

Mit #511 werden auf `Person` 6 neue Bemerkungsfelder hinzugefügt: **"Bemerkung Sektion 1” … "Bemerkung Sektion 5”** sowie **"Bemerkung Geschäftsstelle"**
Diese Felder sollen im JSON:API ebenfalls zurückgegeben werden.

* Die Werte der Felder **"Bemerkung Sektion 1” … "Bemerkung Sektion 5”** dürfen nur sichtbar sein, wenn der user die Berechtigung `:manage_national_office_remark` auf der Person hat.
* Das Werte der Felder **"Bemerkung Geschäftsstelle"** dürfen nur sichtbar sein, wenn der user die Berechtigung `:manage_section_remarks` auf der Person hat.

# Tech-Spec

* in `SacCas::PersonResource` neue Attribute definieren:
  ```ruby
    with_options(writable: false) do
      attribute :remark_head_office, readable: :can_read_remark_head_office?

      (1..5).each do |num|
        attribute "remark_sektion_#{num}", readable: :can_read_remarks_sektion?
      end
    end
  ```

* guard Methoden:

  ```ruby
    def can_read_remark_head_office?(person) = can?(:manage_remark_head_office, person)
    def can_read_remarks_sektion?(person) = can?(:manage_remarks_sektion, person)
  ```
  
* schema.json aktualisieren: `rails graphiti:schema:generate` und resultierendes `schema.json` einchecken

# ToDo

* [x] Attribute in PersonResource einbauen
* [x] schema.json aktualisieren und einchecken
* [x] Specs schreiben

**Comment by tobiasstern** [comment]
Hi @hunchr Wenn ich das teste, indem ich (als Admin) https://sac-cas.puzzle.ch/api/people/459127 aufrufe, dann sehe ich dort keine Bemerkungen. Kannst du mir sagen, wieso?

**Comment by hunchr** [comment]
> Hi @hunchr Wenn ich das teste, indem ich (als Admin) https://sac-cas.puzzle.ch/api/people/459127 aufrufe, dann sehe ich dort keine Bemerkungen. Kannst du mir sagen, wieso?

@tobiasstern Die Bemerkungen sieht man nur über https://sac-cas.puzzle.ch/api/people/459127?extra_fields[people]=sac_remark_national_office,sac_remark_section_1,sac_remark_section_2,sac_remark_section_3,sac_remark_section_4,sac_remark_section_5. Dann werde ich das wohl noch ändern, damit es auch so geht.

**Comment by tobiasstern** [comment]
@hunchr bitte mit @daniel-illi abklären, ob das notwendig ist. Im Zweifelsfall mit mir Rücksprache halten :)

Übrigens sehe ich über deinen Link die Bemerkungen nicht:

`{"data":{"id":"459127","type":"people","attributes":{"first_name":"Wilfrid","last_name":"Lauriot","nickname":null,"company_name":null,"company":false,"email":"wilfridlauriot@orange.fr","address":"50, rue du clos neuf","zip_code":"25160","town":"Malpas","country":"FR","primary_group_id":1618,"gender":"m","birthday":"1972-02-25","language":"fr","family_id":null,"membership_number":459127},"relationships":{"primary_group":{"meta":{"included":false}},"layer_group":{"meta":{"included":false}},"roles":{"meta":{"included":false}},"phone_numbers":{"meta":{"included":false}},"social_accounts":{"meta":{"included":false}},"additional_emails":{"meta":{"included":false}}}},"meta":{}}`

Fehler?

**Comment by hunchr** [comment]
> Übrigens sehe ich über deinen Link die Bemerkungen nicht

@tobiasstern Mir fällt gerade auf, der PR ist ja noch nicht gemerged, also gibt es die Bemerkungen auch noch nicht auf sac-cas.puzzle.ch. Sorry, den Link von oben habe ich eben auf localhost getestet..

**Comment by rnestler** [comment]
> * Die Werte der Felder "Bemerkung Sektion 1” … "Bemerkung Sektion 5” dürfen nur sichtbar sein, wenn der user die Berechtigung :manage_national_office_remark auf der Person hat.
> * Das Werte der Felder "Bemerkung Geschäftsstelle" dürfen nur sichtbar sein, wenn der user die Berechtigung :manage_section_remarks auf der Person hat.


@daniel-illi Wie läuft das mit Tokens? Die sind ja nicht an einen user gebunden oder?

**Comment by mtnstar** [comment]
> > * Die Werte der Felder "Bemerkung Sektion 1” … "Bemerkung Sektion 5” dürfen nur sichtbar sein, wenn der user die Berechtigung :manage_national_office_remark auf der Person hat.
> > * Das Werte der Felder "Bemerkung Geschäftsstelle" dürfen nur sichtbar sein, wenn der user die Berechtigung :manage_section_remarks auf der Person hat.
> 
> @daniel-illi Wie läuft das mit Tokens? Die sind ja nicht an einen user gebunden oder?

Dani ist noch in den ferien.
ich denke es macht Sinn das man per Token NICHT auf die Bemerkungen zugreifen kann.
sehr gut hast du das bedacht, kannst du das noch so anpassen?
