### ISSUE TITLE
PEOPLE: Digitaler Mitgliederausweis aktive Tourenleiter

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#533]
>Als “Fotograf” resp. als Kontrolleur des digitalen Mitgliederausweises  
will ich sehen, ob die Person ein:e aktive:r Tourenleiter:in ist. 

Durch Fotografieren des QR-Code gelangt die prüfende Person auf die Verify Membership Seite, welche in #531 im Detail spezifiziert ist. Siehe auch das mockup in diesem ticket.

* Das Layout soll am mockup angelehnt sein, muss aber nicht pixelgenau übereinstimmen.  
  (Das mockup ist höher als ein mobile screen, es muss also gescrollt werden)

* Unter der Auflistung der Mitgliedschaften soll bei Personen mit aktiver Tourenleiter Rolle eine entsprechende Information angezeigt werden.

  DE "Aktive/r Tourenleiter/in"

  FR "Chef·fe de courses en activité"

  IT "Capogita attivo/a"

> [!TIP]
> Aktive Tourenleiter sind Personen, welche eine gültige Rolle `Group::SektionsTourenkommission::Tourenleiter` besitzen.

# Tech-Spec

- Helper Methode implementieren zum Prüfen, ob Person irgend eine aktive Tourenleiterrolle besitzt
- View anpassen (`app/views/people/membership/verify/_member_details_sac_cas.html.haml`)  
  Tourenleiter Info anzeigen falls aktiver Tourenleiter
- div für Tourenleiter sektion/abschnitt bereits vorhanden
- the QR code should only be clickable/linked in development environment

# Notes

 * Link de/groups/xx/person/xx
 * ~~QR-Code verlinken dass man es zum entwickeln nicht scannen muss~~ der QR code darf nicht verlinkt sein, das ist explizit von SAC so gewünscht

# ToDo

- [x] View anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by mtnstar** [comment]
@hunchr the QR code should only be clickable/linked in development environment?
could you adjust this?
