### ISSUE TITLE
ROLES: Neuanmeldungs-Rollen sollten kein Enddatum haben

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_sac_cas#535]
### Aktuelles Verhalten

Neuanmeldungsrollen sind bisher standardmässig bis 31.12 gültig. Was passiert, wenn jemand am 31.12 eintritt?

Jahresinkassolauf berücksichtigt nur Mitglieder mit Rolle “Mitglied”, aber nicht “Neuanmeldung”.

Jahresinkassolauf verlängert Mitglieder-Rolle um 3 Monate.

Personen mit Rolle Neuanmeldung können Kurse zum SAC Mitgliederpreis bereits buchen.

Personen mit Rolle Neuanmeldung, die ihre Rechnung nicht bis zum 31.12 registrieren, werden ab 1.1 ohne Rolle da stehen.

### Gewünschtes Verhalten

Eine Neuanmeldung soll unbeschränkt gültig bleiben.

### Schritte zu reproduzieren

Am 31.12. eine Neuanmeldung erfassen

### Wann ist der Fehler aufgetreten?

24.04.2024

### hitobito version

2.1.5

### Organisation

SAC

### Screenshots, weiterer Kontext

Kommt aus der Bugsammlung: https://saccas.atlassian.net/browse/HIT-161

# Tech-Spec

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/group/sektions_neuanmeldungen_sektion.rb#L13
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/group/sektions_neuanmeldungen_sektion.rb#L18
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/group/sektions_neuanmeldungen_nv.rb#L13
- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/models/group/sektions_neuanmeldungen_nv.rb#L18

**Comment by tobiasstern** [comment]
Kurz getestet: Neueintritt in Sektion SAC Testsektion. Auf dem Nutzerprofil war die Rolle Neuanmeldung ohne Start-/End-Datum vergeben.
Nichts anderes getestet.
