### ISSUE TITLE
EVENTS: Externe Ausbildungen können nicht in der Zukunft stattfinden

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#538]
Wenn eine externe Ausbildung erfasst wird, darf das Enddatum nicht grösser als heute sein.

# ToDo

- [x] Model anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Funktioniert, vgl Bild:


![Image](https://github.com/user-attachments/assets/e68df5d8-893d-484b-a04a-af562b6ab6a6)
