### ISSUE TITLE
PERSON: Event Headers im  Verlauf

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#541]
Bei den Tabellen der besuchten Events / Kursen im Verlauf einer Person gibt es momentan keine Spaltenheaders. 

Neu sollen die Spalten einen Header haben:
* Name / Gruppe
* Rolle
* Daten
* Qualifikation (nur Kurse)

# ToDo

- [x] View anpassen
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Works:

![Image](https://github.com/user-attachments/assets/dcd22ffe-14b9-4ae4-b734-8cb0e9fa973e)
