### ISSUE TITLE
PEOPLE: Controller zum Ändern der family main person

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#555]
blocks #550

Im SAC wagon gibt es auf der `Person` das bool Attribut `sac_family_main_person`.
Dieses ist für Familien relevant (abgebildet mit dem household feature in Hitobito). Anhand dieses flags wird z.B. der Familienrechnungsempfänger bestimmt.

Pro Familie muss es genau 1 Person mit `sac_family_main_person = true` geben.

Es soll ein Controller implementiert werden, mit welchem der user das Flag `sac_family_main_person` auf einer Person setzen kann, sofern diese einer Familie (einem Haushalt) zugeordnet ist.

- `sac_family_main_person` kann nur für Erwachsene in einem Haushalt gesetzt werden (adult)
- Aktion darf nur von jemandem der Schreibrechte auf alle Personen im Haushalt/SacFamily hat

# Tech-Spec

- Route
  ```ruby
  resources :people, except: [...] do
    resource :sac_family_main_person, only: :update
  end
  ```
- Controller `People::SacFamilyMainPersonController` mit `update` action
  * **noop** falls Person bereits `family_main_person == true`, redirect auf Person show view
  * 422 falls Person in keinem Haushalt (`household_key.blank?`)
  * prüfen, ob user Schreibrechte hat auf der Person, und auf jeder von `person.household_people.select(&:family_main_person)`
  * setzt `family_main_person=true` auf der Person, und `false` auf den anderen Personen `person.household_people`
  * in einer transaction
  * redirect auf Person show view

- Logik möglichst in: https://github.com/hitobito/hitobito_sac_cas/blob/master/app/domain/people/sac_family.rb und nicht im Controller
- Erweitern der PersonAbility
  - :set_sac_family_main_person ist erlaubt wenn Schreibrechte auf alle Personen im Haushalt vorhanden
  - authorize!(:set_sac_family_main_person, person)
  - permission(:any).may(:set_sac_family_main_person).if_person_is_adult_and_all_household_members_writable

``` 
def if_person_is_adult_and_all_household_members_writable
   return false unless SacCas::Beitragskategorie::Calculator.new(person).adult? && person.confirmed_at?

   subject ... get all household members
   household_members.all? ... can? update person
end

def person
  subject
end
```

- https://github.com/hitobito/hitobito_sac_cas/blob/master/app/abilities/sac_cas/person_ability.rb
- https://github.com/hitobito/hitobito_sac_cas/blob/master/spec/abilities/sac_cas/person_ability_spec.rb

# ToDo

- [x] Route
- [x] Controller
- [x] Specs schreiben

**Comment by Largo** [comment]
Nun nach feedback mocks entfernt in den ability tests.
Fehlerfix nach Pfadfinderprinzip: In anderem file war can?(:read, person)  drin, das gibts soweit ich weiss nicht.
