### ISSUE TITLE
EVENTS: Status Aufgeboten

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#557]
Anmeldungen mit Status “Aufgeboten” sind in der Anmelde-Übersicht auf der rechten Seite, vgl. Bild. Sie sollen aber auf der linken Seite sein.

![9cefb561-2ff4-453a-8f89-6866e25a20f0](https://github.com/hitobito/hitobito_sac_cas/assets/271590/e6b9bf9b-a0f4-4fb2-8c41-4f3eb272bff7)

Anmeldungen mit Status “Aufgeboten” sind in der Liste der Teilnehmenden gar nicht aufgeführt, vgl Bild. Sie sollen auch aufgeführt sein.

![9720b417-0d28-4cca-94ff-2c1b1736605e](https://github.com/hitobito/hitobito_sac_cas/assets/271590/95bd8d4d-2445-4ee1-9f3c-5c37a78236a5)

Der Status `summoned` muss sicher in die Listen `active_participation_states` sowie `countable_participation_states` aufgenommen werden.

änderungen im SAC wagon

# ToDo

- [x] Model anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by mtnstar** [comment]
please add this change to sac wagon, not youth.
add spec for this ... maybe controller or somewhere else where all the participations are loaded

**Comment by tobiasstern** [comment]
Erfolgreich getestet
