### ISSUE TITLE
EVENTS: E-Mail bei Ablehnung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#558]
Als Kursadmin möchte ich, dass alle abgelehnten Personen automatisch eine E-Mail erhalten, wenn der Kurs auf den Status "Zuteilung abgeschlossen" wechselt .

Neu soll der `Event::Courses::State` (#488) entsprechend angepasst werden, dass nach dem erfolgreichen Wechseln des Kurs Status an alle TN, welche sich zu diesem Zeitpunkt im Status "Abgelehnt" befinden, eine E-Mail verschickt wird. Die E-Mails sollen in einem Background Job verschickt werden, weshalb die Sache über ein after_commit Callback abgehandelt werden muss.

Der Inhalt der E-Mail ist über den folgenden CustomContent definierbar:

```ruby
{ key: Event::ParticipationMailer::CONTENT_REJECTED_PARTICIPATION, # 'event_participation_rejected`
  placeholders_required: 'participant-name',
  placeholders_optional: 'event-name, application-url, event-details' },
```

(siehe als Beispiel den PBS Event::ParticipationMailer).

# ToDo

- [x] Seed erstellen
- [x] Mailer erweitern
- [x] Controller/Domainklasse anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Erfolgreich getestet
