### ISSUE TITLE
EVENTS: TN aufbieten wenn Kurs auf "Bereit zur Durchführung" gesetzt wird

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#581]
Als Kursadmin will ich, dass wenn ich einen Kurs mit Status ”Zuteilung abgeschlossen” in den Status “Bereit zur Durchführung” versetze, das System alle Teilnahmen mit Status “Bestätigt” in den Status “Aufgeboten” ändert. 

Falls der Kurs von einem anderen Status auf "Bereit zur Durchführung" wechselt, werden die TN Status nicht angepasst.

Die Änderung kann über einen `after_save` Hook in `Events::Courses::State` angestossen werden.

In einem Folgeticket wird für jeden TN eine E-Mail versendet.

# ToDo

- [x] Model anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
@codez Beim notify_rejected_participants hook habe ich after_commit verwendet. Geht das hier auch anstatt after_save?
