### ISSUE TITLE
EVENTS: Zusätzliche Statuswechsel

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#583]
Neu soll es für Kurse zwei zusätzliche Statuswechsel geben:

- "Zurück zur abgeschlossenen Anmeldung" von "Zuteilung abgeschlossen"
- "Zurück zur Zuteilung" von "Bereit zur Durchführung"

Siehe `Events::Courses::State`. Nachfolgeticket zu #362

# ToDo

- [x] Model anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
Ich bin gerade wegen #558 am pruefen dieses Themas, somit sowieso im Thema drin und übernehme daher dieses Ticket.
