### ISSUE TITLE
PEOPLE: SektionSelfSignupController

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#587]
Im SAC wagon soll als universalen Einstiegspunkt zur Selbstregistrierung und Selbsteinschreibung in einer `Group::Sektion` ein neuer `Groups::SektionSelfSignupController` implementiert werden.

Dieser bietet für eine Sektion eine zentrale URL, über welche der Einschreibungsprozess gestartet wird und ist dafür zuständig, den user an den korrekten **self registration** Pfad resp. **self inscription** Pfad weiterzuleiten.

# Tech-Spec

- route `resources :groups { get 'self_registration' => 'groups/self_signup#dispatch' }`
- controller `Groups::SektionSelfSignupController` 
  - kein login required
  - `def groups = Group.find(params[:group_id])`
  - action `#new`
    - 404 rendern falls
      - `group` nicht gefunden
      - `group` ist keine `Group::Sektion`
      - Sektion hat Selbstregistrierung deaktiviert
    - user ist NICHT eingeloggt:   
      *ev `Groups::SektionSelfRegistrationLink#url` verwenden* 
      - Sektion hat eine Gruppe `Group::SektionsNeuanmeldungenSektion`:  
        redirect an `group_self_registration_path` dieser Gruppe
      - Sektion hat KEINE Gruppe `Group::SektionsNeuanmeldungenSektion`:  
        redirect an `group_self_registration_path` der Gruppe `Group::SektionsNeuanmeldungenNv` der Sektion
    - user IST eingeloggt:
      - user ist SAC Mitglied (besitzt aktuell gültige Mitgliedschaft)  
        redirect an `group_self_inscription_path` der Gruppe `Group::Mitglieder` der Sektion
      - user ist nicht Mitglied (keine aktuell gültige Mitgliedschaft)  
        **TODO**: redirect an *selfreg light* der Gruppe Neuanmeldungen (logik siehe oben "user ist nicht eingeloggt")
      - **TODO**: was, wenn `FutureRole(Mitgliedschaft)`?
- `Groups::SektionSelfRegistrationLink` anpassen
  + Methode `#self_signup_url`
    ```ruby
    group_self_signup_url(host: @host, group_id: sektion.id)
  + Methode `#url` umbenennen nach `#self_registration_path`, path helper statt url helper verwenden
- `Group::Sektion#sac_cas_self_registration_url` anpassen: `#self_signup_url` statt `#url` aufrufen


# ToDo

- [ ] Route
- [ ] Controller
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by carlobeltrame** [comment]
Die aktuelle Selbstregistrierungs-URL erfüllt doch diese Anforderungen bereits..? Sie ist zugänglich wenn man nicht eingeloggt ist, und leitet wenn man eingeloggt ist automatisch zur self_inscription weiter. Was fehlt da noch konkret?

**Comment by daniel-illi** [comment]
obsolet
