### ISSUE TITLE
MAIL: Sprachabhängiger Absendername

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#600]
Neu sollen alle E-mails der Applikation, welche als Absenderadresse die Standard-Absenderadresse verwenden (`Settings.email.sender`), je nach gewählter Sprache der E-Mail einen übersetzten Name vorgestellt erhalten.

Die Bezeichnung kann im Locale Yaml hinterlegt werden.

Für den SAC wäre das:
- de: "Schweizer Alpen-Club SAC <noreply@{mail_domain}>"
- fr: "Club Alpin Suisse CAS <noreply@{mail_domain}>"
- it: "Club Alpino Svizzero CAS <noreply@{mail_domain}>"
- en: "Swiss Alpine Club SAC <noreply@{mail_domain}>"

# ToDo

- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
Aufgefallene Schwierigkeiten:
- ActionMailer::Base.default from: Settings.email.sender sind globals und daher geteilt mit der ganzen Applikation. Kann daher also nicht per Sprache gesetzt werden. => wir müssen pro E-Mail setzen.
- Settings sind natuerlich auch global
- Sprache wird bei jedem Request und relativ spät geladen => dort muss angesetzt werden.

**Comment by tobiasstern** [comment]
Hallo

Ich habs auf der Integration getestet und habe hier die französische Mail bekommen, aber mit dem Default/deutschen Absender, siehe Bild:
![image](https://github.com/user-attachments/assets/7ed568ab-963b-4767-a6fe-c0c2a45bfc81)

Scheint also noch nicht zu funktionieren.

**Comment by Largo** [comment]
Ah ja. [Die Übersetzung](https://github.com/hitobito/hitobito_sac_cas/commit/422314e84bbdbbe06e6e61088e6077cef95d1ef9) muss noch ins Transifex.

**Comment by Largo** [comment]
Übersetzung ist nun im Transifex.

**Comment by tobiasstern** [comment]
Funktioniert 🙌
