### ISSUE TITLE
PEOPLE: PDF Generierung mit Emojis und anderen Unicode Zeichen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#610]
Mitglied kann in seinem Namen beliebige Unicode Zeichen verwenden (Chinesische Zeigen, emojis etc.)

Beim Generieren des Mitgliederausweis PDF gibt es einen Error, wenn Zeichen verwendet werden, welche im verwendeten font nicht vorkommen.

Dasselbe Problem wird bei weiteren PDF auftreten, z.B. generieren von Etiketten.

Möglicherweise werden auch Drittsysteme Probleme haben, wenn sie über das API Felder mit beliebigen Unicodezeichen erhalten.

Als Lösung sollen beim Generieren aller PDF die Texte transliteriert werden nach ISO 8859-1

**Comment by carlobeltrame** [comment]
Besser gleich im Core lösen, mit hitobito/hitobito#2372
