### ISSUE TITLE
EVENTS: E-Mail Anmeldebestätigung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#625]
Als Kurs-TN möchte ich, dass ich eine E-Mail erhalte, wenn ich für einen Kurs angemeldet bin.

## Textvorlage (`CustomContent`)

Neu soll es drei Textvorlagen für die Anmeldebestätigung bei einem Kurs geben:
- "Kurs: E-Mail Unbestätigte Kursanmeldung": TN-Status ist unbestätigt, `course_application_confirmation_unconfirmed`
- "Kurs: E-Mail Bestätigte Kursanmeldung": TN-Status ist bestätigt, `course_application_confirmation_assigned`
- "Kurs: E-Mail Unbestätigte Warteliste": TN-Status ist Warteliste, `course_application_confirmation_applied`

Diese Vorlagen haben die folgenden Platzhalter:

- recipient-name (auf `greeting_name`, optional)
- event-details  (optional)
- event-name (required)
- event-number  (optional)
- application-url  (optional)
- person-url  (optional)
- event-link (mit HTML Link auf den Kurs, Label "Name (Nummer)", optional)
- application-closing-at (Entsprechendes Datum gemäss locale, optional)
- missing-information (optional)

Die `missing-information` werden wie folgt aufgelöst: (gleich wie #628)

- Ein Paragraph mit einem fixen Text (aus den locales): "Für die Teilnahme an diesem Kurs sind die folgenden Nachweise zu erbringen. Bitte reiche diese noch ein, falls du dies nicht schon getan hast."
- Eine Bullet Point Liste mit allen Fragen aus den Administrationsangaben (Event::Question#admin), die entweder keine Antwort oder einen der Werte "nein"/"non"/"no" haben. Falls andere Antworten existieren, wird die Frage hier nicht aufgelistet. 
- Falls eine leere Liste resultiert, wird auch der Paragraph nicht angezeigt, der gesamte Platzhalter bleibt also leer.

Betreff und Inhalt können in den Seeds beliebig sein.

## Trigger

Wenn sich ein TN bei einem Kurs anmeldet, werden je nach resultierendem TN Status das zugehörige E-Mail verschickt. Via ParticipantAssigner wird momentan bei jeder Änderung eine E-Mail verschickt (z.B. beim hin und her schieben auf der Ansicht "Anmeldungen"). Dies soll neu nicht mehr der Fall sein, es sollen nur noch E-Mails raus, wenn der TN sich selbst anmeldet oder wenn ein Kursadmin die Anmeldung für einen TN erstellt.

Die E-Mails aus dem Core/Youth Wagon, welche bisher bei einer Anmeldung verschickt werden, sollen nur noch für reguläre Anlässe versendet werden.

Die Notification an den Course#contact wird für SAC Kurse nicht geschickt (siehe ParticipationsController). Dies muss entsprechend angepasst werden.

Die E-Mails werden via Background Job versendet.

## E-Mail (gleich wie #629)

- Die Email wird via BCC ebenfalls an die auf der Gruppe SAC/CAS definierte Kursadmin E-Mail Adresse geschickt (`course_admin_email`, falls vorhanden).
- Als Sprache/Locale beim E-Mail wird die Sprache auf dem Kurs verwendet (`language`). Falls die Sprache `de_fr` gewählt ist, wird der Inhalt einmal auf Deutsch und einmal auf Französisch generiert und mit einer Trennzeile "--------------------" (inkl. je eine Leerzeile davor und danach) in die E-Mail eingefügt. Die Absendeadresse wird in diesem Fall auf deutsch ausgegeben.

# ToDo

- [x] Seed erstellen
- [x] Domainklasse erstellen oder anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Wir haben die Spezifikation anpassen müssen und pro Platzhalter definiert, ob sie in der Vorlage optional oder required sind. Bitte bei Gelegenheit anpassen.

**Comment by tobiasstern** [comment]
Klappt gut
