### ISSUE TITLE
EVENTS: E-Mail Reminder TN Administrationsangaben

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#628]
Als Kurs-TN möchte ich eine E-Mail erhalten, falls ich 6 Wochen vor Kursbeginn noch nicht alle Nachweise eingereicht habe.

## Textvorlage (`CustomContent`)

Es gibt eine neue Textvorlage namens "Kurs: E-Mail Reminder TN Administrationsangaben" mit folgenden Platzhaltern:

- recipient-name (auf `greeting_name`. optional)
- event-details  (optional)
- event-name (required)
- event-number (optional)
- event-link (mit HTML Link auf den Kurs, Label "Name (Nummer)", optional)
- application-url  (optional)
- person-url  (optional)
- missing-information  (optional)

Die `missing-information` werden wie folgt aufgelöst: (gleich wie #625)
- Ein Paragraph mit einem fixen Text (aus den locales): "Für die Teilnahme an diesem Kurs sind die folgenden Nachweise zu erbringen. Bitte reiche diese noch ein, falls du dies nicht schon getan hast."
- Eine Bullet Point Liste mit allen Fragen aus den Administrationsangaben (`Event::Question#admin`), die entweder keine Antwort oder einen der Werte "nein"/"non"/"no" haben. Falls andere Antworten existieren, wird die Frage hier nicht aufgelistet.

Betreff und Inhalt der Textvorlage können in den Seeds beliebig sein.

## Trigger

Ein nächtlicher Job prüft für alle Kurse, deren erstes Datum in genau 6 Woche ist, bei welchen *aktiven* TN Kursfragen bei den Administrationsangaben (`Event::Question#admin`) nicht oder mit "nein"/"non"/"no" ausgefüllt sind. Für jeden betroffenen TN wird eine Email versendet.

## E-Mail (gleich wie #629)

- Die Email wird via BCC ebenfalls an die auf der Gruppe SAC/CAS definierte Kursadmin E-Mail Adresse geschickt (`course_admin_email`, falls vorhanden).
- Als Sprache/Locale beim E-Mail wird die Sprache auf dem Kurs verwendet (`language`). Falls die Sprache `de_fr` gewählt ist, wird der Inhalt einmal auf Deutsch und einmal auf Französisch generiert und mit einer Trennzeile "--------------------" (inkl. je eine Leerzeile davor und danach) in die E-Mail eingefügt. Die Absendeadresse wird in diesem Fall auf deutsch ausgegeben.

# ToDo

- [x] Seed erstellen
- [x] Job erstellen oder anpassen
- [x] Specs schreiben

**Comment by Largo** [comment]
Annahme: Das E-Mail soll täglich eintreffen, bis die Angaben ausgefüllt sind.

**Comment by Largo** [comment]
Ja stimmt, dann nur ein Mail. Ich bins noch am sorgfaeltig durchklicken.

**Comment by tobiasstern** [comment]
Hey, was passiert, wenn der Kurs mehrere Durchführungen hat an unterschiedlichen Daten? Bspw so:
![Image](https://github.com/user-attachments/assets/f76382b3-802d-440e-9f0b-debf5541b593)

Wird's dann einfach beim frühesten Datum ausgelöst oder für jedes Datum 6W vorher?

**Comment by tobiasstern** [comment]
Habe zum Testen diesen Kurs vorbereitet mit diversen Anmeldungen: https://sac-cas.puzzle.ch/de/groups/1/events/47 Frühestes Datum ist der 15.11. also morgen in 6W.
To be continued...

**Comment by hunchr** [comment]
Ich habe im Code nachgeschaut. Es wird aktuell für jedes Datum 6W vorher gesendet. Ist das so gedacht oder sollte es nur fürs Erste einen Reminder senden, @tobiasstern ?

**Comment by tobiasstern** [comment]
@hunchr danke. Nein, lass doch das so wie es jetzt ist. Ich kläre dann mit dem Fach ab, ob wir daran noch was ändern sollen.

**Comment by tobiasstern** [comment]
Erster Test hat prima funktioniert. Mails sind auch ans Kurskader raus (Leitung/Hauptleitung), was ich okay finde aber bespreche es dann auch noch mit dem Fach, ob das so passt.

Ich warte jetzt noch ein Tag um zu sehen, ob die Mails auch beim zweiten Datum rausgehen, um zu verifizieren, wie es sich verhält.

**Comment by tobiasstern** [comment]
Habs mit dem Fach abgeklärt: Sie werden die mehreren Durchführungen nicht verwenden, für sie gilt ein Datum pro Kurs. Daher ist dies hier vernachlässigbar und kann so belassen werden --> Done
