### ISSUE TITLE
EVENTS: E-Mail Reminder Kursleitung

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#629]
Als Kurs-Hauptleitung möchte ich eine E-Mail erhalten, wenn der Kurs in 8 Wochen stattfindet.

## Textvorlage (`CustomContent`)

Es gibt eine neue Textvorlage namens "Kurs: E-Mail Reminder Kursleitung" mit folgenden Platzhaltern:

- recipient-name (auf `greeting_name`, optional)
- event-details  (optional)
- event-name (required)
- event-number  (optional)
- event-link (mit HTML Link auf den Kurs, Label "Name (Nummer)", optional)
- six-weeks-before-start (Datum im Format gemäss locale, 6 Wochen vor dem ersten Startdatum, optional)

Betreff und Inhalt der Textvorlage können in den Seeds beliebig sein.

Achtung: Das Datum in der Vorlage ist 6 Wochen vor dem Kurs; verschickt wird die E-Mail 8 Wochen vor dem Kurs.

## Trigger

Ein nächtlicher Job prüft für alle Kurse, deren erstes Datum in genau 8 Wochen ist, und versendet jeder entsprechenden Kurs-Hauptleitung eine Email.

## E-Mail

- Die Email wird via BCC ebenfalls an die auf der Gruppe SAC/CAS definierte Kursadmin E-Mail Adresse geschickt (`course_admin_email`, falls vorhanden).
- Als Sprache/Locale beim E-Mail wird die Sprache auf dem Kurs verwendet (`language`). Falls die Sprache `de_fr` gewählt ist, wird der Inhalt einmal auf Deutsch und einmal auf Französisch generiert und mit einer Trennzeile "--------------------" (inkl. je eine Leerzeile davor und danach) in die E-Mail eingefügt. Die Absendeadresse wird in diesem Fall auf deutsch ausgegeben.

# ToDo

- [x] Seed erstellen
- [x] Domainklasse erstellen oder anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Testkurse erstellt, teste morgen ob E-Mails raus sind.

**Comment by tobiasstern** [comment]
Hi @hunchr 

Ich habe vier Testkurse erfasst, die in 8 Wochen stattfinden, am 01. Oktober, aber es wurden keine Mails verschickt. Bitte untersuchen, was der Grund sein könnte!

Meine Testkurse:
https://sac-cas.puzzle.ch/de/groups/1/events/40
https://sac-cas.puzzle.ch/de/groups/1/events/47
https://sac-cas.puzzle.ch/de/groups/1/events/48
https://sac-cas.puzzle.ch/de/groups/1/events/49

**Comment by hunchr** [comment]
> Und weisst du, warum es zwei gleichnamige Vorlagen hat im System? Siehe Bild:

Eine ist auf Deutsch und die andere auf Französisch

**Comment by codez** [comment]
@hunchr  Nein, das wird es nicht sein. Vorlagen sind grundsätzlich mehrsprachig und tauchen deshalb nicht mehrfach auf. Da gibt es wohl ein anderes Problem.

**Comment by hunchr** [comment]
Hey @tobiasstern

Ich habe herausgefunden, was das Problem war. Der Job wurde gar nie aufgerufen. Jetzt sollte es gehen.

Das mit den Vorlagen werde ich mir noch anschauen. Lokal gibts die bei mir nämlich nur einmal.

**Comment by tobiasstern** [comment]
Hey @hunchr 

Danke fürs Update. Ich hatte gestern bei den Kursen die Durchführungen auf heute in 8 Wochen gesetzt. Aber es sind bisher keine Mails eingegangen dafür im Mailtrap.

Kannst du dir das bitte nochmal anschauen?

**Comment by hunchr** [comment]
> Ich hatte gestern bei den Kursen die Durchführungen auf heute in 8 Wochen gesetzt. Aber es sind bisher keine Mails eingegangen dafür im Mailtrap.

@tobiasstern der job läuft ja 5 min nach mitternacht, also nehme ich an, dass die mails nicht gesendet wurden, weil der kurs dann schon *heute in 7 wochen und 6 tagen* ist. kannst du es bitte nochmals versuchen mit 8 wochen und 1 tag als puffer?

**Comment by tobiasstern** [comment]
Okay, ich habe bei den Testkursen die Durchführung auf 09.10.2024

https://sac-cas.puzzle.ch/de/groups/1/events/40
https://sac-cas.puzzle.ch/de/groups/1/events/47
https://sac-cas.puzzle.ch/de/groups/1/events/48
https://sac-cas.puzzle.ch/de/groups/1/events/49

Testing folgt.

**Comment by tobiasstern** [comment]
Wir haben die Spezifikation anpassen müssen und pro Platzhalter definiert, ob sie in der Vorlage optional oder required sind. Bitte bei Gelegenheit anpassen.

**Comment by tobiasstern** [comment]
Die E-Mails werden korrekt verschickt 👍 

@hunchr kannst du bitte noch auf der Integration die nicht verwendete Mail-Vorlage entfernen? Dann ist dieses Ticket abgeschlossen.

**Comment by hunchr** [comment]
moved to #819
