### ISSUE TITLE
EVENTS: E-Mail Anmeldung pausiert

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#630]
Als Kursadmin möchte ich eine E-Mail erhalten, wenn der Kurs in den Status "Anmeldung pausiert" wechselt

## Textvorlage (`CustomContent`)

Es gibt eine neue Textvorlage namens "Kurs: E-Mail Anmeldung pausiert" mit folgenden Platzhaltern:

- event-details  (optional)
- event-name (required)
- event-number  (optional)
- event-link (mit HTML Link auf den Kurs, Label "Name (Nummer)",  optional)

Betreff und Inhalt der Textvorlage können in den Seeds beliebig sein.

## Trigger

Wenn der Status des Kurses zu "Anmeldung pausiert" wechselt, wird eine E-Mail ausgelöst. Die Email wird an die auf der Kursegruppe definierten Kursadmin E-Mail Adresse geschickt (`course_admin_email`, falls vorhanden; sonst keine E-Mail).

Die E-Mail wird via Background Job versendet.

## E-Mail

- Als Sprache/Locale beim E-Mail wird die Sprache auf dem Kurs verwendet (`language`). Falls die Sprache `de_fr` gewählt ist, wird der Inhalt einmal auf Deutsch und einmal auf Französisch generiert und mit einer Trennzeile "--------------------" (inkl. je eine Leerzeile davor und danach) in die E-Mail eingefügt. Die Absendeadresse wird in diesem Fall auf deutsch ausgegeben.

# ToDo

- [x] Seed erstellen
- [x] Domainklasse erstellen oder anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Wir haben die Spezifikation anpassen müssen und pro Platzhalter definiert, ob sie in der Vorlage optional oder required sind. Bitte bei Gelegenheit anpassen.

**Comment by tobiasstern** [comment]
@hunchr Die Placeholder sind nicht optional, kannst du dies bitte noch anpassen?

**Comment by hunchr** [comment]
> @hunchr Die Placeholder sind nicht optional, kannst du dies bitte noch anpassen?

sie sind optional, das habe ich letzte woche gemacht. anscheinend gibt es probleme mit der integration, dort werden sie nicht aktualiert. ich frage mal nach weshalb.

**Comment by hunchr** [comment]
@tobiasstern ama hat es jetzt gefixt
