### ISSUE TITLE
EVENTS: E-Mail Keine Teilnahme

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#631]
Als Kurs-TN möchte ich, dass ich eine E-Mail erhalte, wenn ich nicht an einem Kurs teilnehmen kann.

## Textvorlage (`CustomContent`)

Neu soll es zwei Textvorlagen für TN bei einem Kurs geben, wenn diese nicht teilnehmen können:
- "Kurs: E-Mail Keine Teilnahme 'Warteliste'": TN-Status ist Warteliste/`applied`, `course_no_participation_applied`
- "Kurs: E-Mail Keine Teilnahme 'Abgelehnt'": TN-Status ist Abgelehnt/`rejected`, `course_no_participation_rejected`

Die in #558 erstellte Vorlage soll entsprechend zu "Kurs: E-Mail Keine Teilnahme 'Warteliste'" umbenannt werden.

Diese Vorlagen haben die folgenden Platzhalter:

- recipient-name (auf `greeting_name`, optional)
- event-details  (optional)
- event-name (required)
- event-number  (optional)
- application-url  (optional)
- person-url  (optional)
- event-link (mit HTML Link auf den Kurs, Label "Name (Nummer)", optional)

Betreff und Inhalt können in den Seeds beliebig sein.

## Trigger

Wenn der Kurs Status auf "Zuteilung abgeschlossen" wechselt, wird für alle TN, welche entweder im Status Warteliste / `applied` oder Abgelehnt / `rejected` sind, eine entsprechende E-Mail versendet.

Due in #558 verschickten Mails für Abgelehnt werden entsprechend beibehalten, zusätzlich werden auch solche für Warteliste verschickt.

Die E-Mails werden via Background Job versendet.

## E-Mail

- Die Email wird via BCC ebenfalls an die auf der Gruppe SAC/CAS definierte Kursadmin E-Mail Adresse geschickt (`course_admin_email`, falls vorhanden).
- Als Sprache/Locale beim E-Mail wird die Sprache auf dem Kurs verwendet (`language`). Falls die Sprache `de_fr` gewählt ist, wird der Inhalt einmal auf Deutsch und einmal auf Französisch generiert und mit einer Trennzeile "--------------------" (inkl. je eine Leerzeile davor und danach) in die E-Mail eingefügt. Die Absendeadresse wird in diesem Fall auf deutsch ausgegeben.

# ToDo

- [x] Seed erstellen
- [x] Mailer erstellen oder anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by hunchr** [comment]
> Die in https://github.com/hitobito/hitobito_sac_cas/issues/558 erstellte Vorlage soll entsprechend zu "Kurs: E-Mail Keine Teilnahme 'Warteliste'" umbenannt werden.

und

> Die in https://github.com/hitobito/hitobito_sac_cas/issues/558 verschickten Mails für Abgelehnt werden entsprechend beibehalten, zusätzlich werden auch solche für Warteliste verschickt.

wiedersprechen sich. @codez ist 558 nun `warteliste` oder `abgelehnt`? abgelehnt würde mehr sinn machen.

**Comment by tobiasstern** [comment]
Konnte den Versand der Mails noch nicht testen, aber in der Maske der Vorlage "Abgelehnt" ist mir schonmal aufgefallen, dass ein paar Platzhalter fehlen in der Beschreibung unter dem Textfeld, siehe Bilder:

Abgelehnt:
![Image](https://github.com/user-attachments/assets/ea0eabe2-2bbd-4279-b5da-ccf3e921bde1)

Warteliste:
![Image](https://github.com/user-attachments/assets/1141f9a9-84b0-478c-92de-fe1a13f76848)

Bitte bei Gelegenheit noch hinzufügen.

**Comment by tobiasstern** [comment]
Klappt prima 👍
