### ISSUE TITLE
EVENTS: E-Mail Aufgebot

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#633]
Als Kurs-TN möchte ich, dass ich eine E-Mail erhalte, wenn ich an einem Kurs teilnehmen kann.

## Textvorlage (`CustomContent`)

Neu soll es eine Textvorlage names "Kurs: E-Mail Aufgebot" mit den folgenden Platzhalter geben:

- recipient-name (auf `greeting_name`) (anmerkung largo: ist der default, optional)
- event-details  (optional)
- event-name (required)
- event-number  (optional)
- application-url  (optional)
- person-url  (optional)
- event-link (mit HTML Link auf den Kurs, Label "Name (Nummer)", optional)
- book-discount-code  (optional)

Betreff und Inhalt können in den Seeds beliebig sein.

## Trigger

Wenn der TN Status auf "Aufgeboten" / `summoned` wechselt, wird eine entsprechende E-Mail versendet.

Info: Der Status kann sowohl für einen TN wechseln wie auch für alle, wenn der Kursstatus auf "Bereit zur Durchführung" gesetzt wird (siehe #581).

Die E-Mails werden via Background Job versendet.

## E-Mail (gleich wie #629)

- Die Email wird via BCC ebenfalls an die auf der Gruppe SAC/CAS definierte Kursadmin E-Mail Adresse geschickt (`course_admin_email`, falls vorhanden).
- Als Sprache/Locale beim E-Mail wird die Sprache auf dem Kurs verwendet (`language`). Falls die Sprache `de_fr` gewählt ist, wird der Inhalt einmal auf Deutsch und einmal auf Französisch generiert und mit einer Trennzeile "--------------------" (inkl. je eine Leerzeile davor und danach) in die E-Mail eingefügt. Die Absendeadresse wird in diesem Fall auf deutsch ausgegeben.

# ToDo

- [ ] Seed erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Wir haben die Spezifikation anpassen müssen und pro Platzhalter definiert, ob sie in der Vorlage optional oder required sind. Bitte bei Gelegenheit anpassen.

**Comment by Largo** [comment]
@tobiasstern Chris hat die Platzhalter optional gemacht, aber vielleicht muss der Inhalt der Mails angepasst werden, wenn der Platzhalter optional ist. Bitte beachten, das diese momentan einfach leer gelassen werden. Da der Inhalt dort sowieso noch nicht fertig spezifiziert ist, sollte dies in einem anderen Ticket geschehen.

**Comment by tobiasstern** [comment]
Danke Largo. Ja, die Inhalte der Mails werden noch im Betrieb über das "Einstellungen > Texte" UI in Hitobito angepasst. Das ist ja Kundenkommunikation, welche die Kolleginnen und Kollegen vom SAC so anpassen können müssen, wie sie es für richtig halten.

**Comment by hunchr** [comment]
@tobiasstern werden die mails gesendet? falls ja, dann würde ich dieses issue schliessen und die platzhalter stattdessen im #819 fixen

**Comment by hunchr** [comment]
platzhalter gefixt

**Comment by tobiasstern** [comment]
yes, passt alles jetzt
