### ISSUE TITLE
EVENTS: E-Mail Vorbereitung abschliessen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#634]
Als Kurs-Hauptleitung möchte ich eine E-Mail erhalten, wenn der Kurs demnächst statt findet.

## Textvorlage (`CustomContent`)

Neu soll es eine Textvorlage namens "Kurs: E-Mail Kursvorbereitungen abschliessen" geben, welche die folgenden Platzhalter enthält:

- recipient-name  (optional)
- event-name (requried)
- event-number  (optional)
- event-details  (optional)
- event-link (mit HTML Link auf den Kurs, Label "Name (Nummer)", optional)

Betreff und Inhalt können in den Seeds beliebig sein.

## Trigger

Ein nächtlicher Job versendet für alle Kurse, deren erstes Datum in genau 1 Woche ist, den entsprechenden Kurs-Hauptleitungen ein entsprechendes E-Mail.

## E-Mail (gleich wie #629)

- Die Email wird via BCC ebenfalls an die auf der Gruppe SAC/CAS definierte Kursadmin E-Mail Adresse geschickt (`course_admin_email`, falls vorhanden).
- Als Sprache/Locale beim E-Mail wird die Sprache auf dem Kurs verwendet (`language`). Falls die Sprache `de_fr` gewählt ist, wird der Inhalt einmal auf Deutsch und einmal auf Französisch generiert und mit einer Trennzeile "--------------------" (inkl. je eine Leerzeile davor und danach) in die E-Mail eingefügt. Die Absendeadresse wird in diesem Fall auf deutsch ausgegeben.

# ToDo

- [x] Seed erstellen
- [x] Domainklasse erstellen oder anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Habe Testkurse erstellt mit Durchführung am 21.08.2024

https://sac-cas.puzzle.ch/de/groups/1/events/52
https://sac-cas.puzzle.ch/de/groups/1/events/53
https://sac-cas.puzzle.ch/de/groups/1/events/54
https://sac-cas.puzzle.ch/de/groups/1/events/55

Testing folgt.

**Comment by tobiasstern** [comment]
Wir haben die Spezifikation anpassen müssen und pro Platzhalter definiert, ob sie in der Vorlage optional oder required sind. Bitte bei Gelegenheit anpassen.
