### ISSUE TITLE
EVENTS: E-Mail Umfrage

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#635]
Als Kursadmin möchte ich nach dem Kurs allen TN eine E-Mail mit einer Umfrage schicken.

## Textvorlage (`CustomContent`)

Es gibt eine neue Textvorlage namens "Kurs: E-Mail Umfrage" mit folgenden Platzhaltern:

- recipient-name (auf `greeting_name`, optional)
- event-details  (optional)
- event-name (required)
- event-number  (optional)
- event-link (mit HTML Link auf den Kurs, Label "Name (Nummer)", optional)
- application-url  (optional)
- person-url  (optional)
- survey-link (mit HTML Link auf Event#link_survey, Label "Umfrage", required)

Betreff und Inhalt der Textvorlage können in den Seeds beliebig sein.

## Trigger

Ein nächtlicher Job versendet für alle Kurse, deren letztes Datum vor genau 3 Tagen ist und welche das Feld `link_survey` ausgefüllt haben, an alle TN im Status "Teilgenommen" / `attended` eine E-Mail.

## E-Mail

- Die Email wird via BCC ebenfalls an die auf der Gruppe SAC/CAS definierte Kursadmin E-Mail Adresse geschickt (`course_admin_email`, falls vorhanden).
- Als Sprache/Locale beim E-Mail wird die Sprache auf dem Kurs verwendet (`language`). Falls die Sprache `de_fr` gewählt ist, wird der Inhalt einmal auf Deutsch und einmal auf Französisch generiert und mit einer Trennzeile "--------------------" (inkl. je eine Leerzeile davor und danach) in die E-Mail eingefügt. Die Absendeadresse wird in diesem Fall auf deutsch ausgegeben.

# ToDo

- [x] Seed erstellen
- [x] Job und Mailer erstellen
- [x] Specs schreiben

**Comment by tobiasstern** [comment]
Habe einen Testkurs vorbereitet: https://sac-cas.puzzle.ch/de/groups/1/events/53 Teste dann morgen, ob die Mails rausgingen

**Comment by tobiasstern** [comment]
Test hat funktioniert, die Mail ist raus 👍  

Im Body der Mail ist mir aufgefallen, dass der Umfragelink nicht als hyperlink formatiert wird i.e. man kann ihn nicht anklicken. Andere Links die über andere Placeholder eingefügt werden kann ich anklicken, vgl Bild
![Image](https://github.com/user-attachments/assets/d682c9ea-6f9c-4582-9b62-9ab5b8a8f9f9)

Mir ist bewusst, dass der Umfrage-Link ein von User abgefüllter string ist, den wir hier verwenden. Können wir ihn trotzdem als klickbaren Link anzeigen im Mail oder spricht aus deiner Sicht etwas dagegen?

**Comment by Largo** [comment]
@hunchr 
Der Kurslink kommt zwar vom admin, aber es waere vermutlich schlau, falls man das mal aendert, den Link trotzdem nicht nur als html_safe zu markieren. Kannst du den mit dem link_to helper aus application_mailer einbinden?

**Comment by hunchr** [comment]
[done](https://github.com/hitobito/hitobito_sac_cas/commit/9499f9142f5e48a098aa7bd4dfd0009ba79d805a)

**Comment by tobiasstern** [comment]
Danke, habe den Testkurs https://sac-cas.puzzle.ch/de/groups/1/events/53 wieder vorbereitet und teste morgen das Ergebnis.

**Comment by tobiasstern** [comment]
Hat geklappt 👍
