### ISSUE TITLE
PEOPLE: Beitragskategorie reference date

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#655]
Im `SacCas::Beitragskategorie::Calculator` wird zur Berechnung der Beitragskategorie als Referenzdatum heute verwendet sofern nichts anderes angegeben.

Es sollte immer der 31.12. des aktuellen Jahres verwendet werden sofern nichts anderes angegeben.

**Comment by Largo** [comment]
@daniel-illi Ich nehme das Referenzdatum gilt auch für die Selbstregistrierung und die person ability set_sac_family_main_person. Falls nicht bitte ticket anpassen
