### ISSUE TITLE
EVENTS: Effektive Tage Kurs-Teilnahme

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#670]
Neu soll beim Bearbeiten der Teilnahme bei einem Kurs (`Event::Participation`) ein zusätzliches Eingabefeld "Effektive Tage" / `actual_days` (decimal 4/1, nullable) vorhanden sein. In einem zusätzlichen Hilfetext zum Feld steht: "Geplante Kursdauer: n Tage". Die Kursdauer berechnet sich aus den Kursdaten, wobei jeder Kurstag gezählt wird, auch angebrochene.

Das Feld wird beim Bearbeiten einer Teilnahme unterhalb des Kommentars angezeigt, falls der User :participations_full Berechtigungen hat. Es soll also insbesondere bei der Selbst-Anmeldung eines TN *nicht* angezeigt werden. Es wird sowohl bei regulären TN wie auch beim Leitungs-Team angezeigt.

Das Feld erhält die folgende Validierung: Der Wert muss grösser oder gleich 0 sein und kleiner oder gleich der Kursdauer in Tagen. 

Auf der TN Leseansicht wird das Feld unterhalb des "Anmeldedatum" angezeigt.

# ToDo

- [x] Migration erstellen
- [x] Model/View/Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Hey @TheWalkingLeek 

Beim kurzen Test ist mir das aufgefallen:

- Man kann keine 0 eingeben
- Im Hilfetext fehlt das " Tage"
- Es ist nicht nötig, das nach dem Komma zwei Stellen angezeigt werden, aber ist auch nicht so schlimm.
