### ISSUE TITLE
PEOPLE: Mitgliederausweis download button

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#672]
Der button um den Mitgliederausweis herunterzuladen muss angepasst werden damit er der Spezifikation entspricht: 

> Aktuell heisst der Button “Download” statt “Mitgliederausweis herunterladen” und wenn man darauf klickt, wird eine Liste angezeigt. Wir haben definiert, dass der Button wie unten dargestellt heisst und sich beim Klick direkt das PDF in einem neuen Tag öffnet. 

![b9d08d7c-fa75-4f73-8d66-a23412025fec](https://github.com/hitobito/hitobito_sac_cas/assets/636849/4413850a-22f8-4e74-bb7a-9b808a5c2505)

> [!NOTE]
> als icon weiterhin das `fa-file-download` verwenden, nicht das `fa-plus` vom screenshot

**Comment by tobiasstern** [comment]
Hallo, warum wurde es so umgesetzt und nicht wie spezifiziert?:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/249e5ecb-9134-443e-abd4-26bb23eeccf0)
![image](https://github.com/hitobito/hitobito_sac_cas/assets/11408951/484e0bf5-0ab3-48ea-9113-9a2498bbc3ba)
