### ISSUE TITLE
ROLES: Validierungsfehler bei FutureRoles

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#678]
### Aktuelles Verhalten

Im `People::CreateRolesJob` kam es zu folgendem Validierungsfehler:

### Gewünschtes Verhalten

Solche Rollen können z.B. gar nicht in der Zukunft erstellt werden
wir finden einen anderen Weg um solchen Validierungsproblemen aus dem Weg zu gehen

### Schritte zu reproduzieren

1. Tourenleiter Rolle mit Start Datum in der Zukunft für Person ohne Qualifikation erstellen
2. Warten bis CreateRolesJob versucht die Rolle zu erstellen

### Screenshots, weiterer Kontext

- https://sentry.puzzle.ch/pitc/hitobito-backend/issues/69800/?environment=integration

```
People::CreateRolesJob::Error

Gültigkeitsprüfung ist fehlgeschlagen: Person muss mindestens eine aktive Qualifikation besitzen. - FutureRole(1111)
```

**Comment by codez** [comment]
In diesem Fall ist es möglicherweise ok, wenn die Rolle einfach nicht erstellt wird.

**Comment by daniel-illi** [comment]
`FutureRole` gibt es nicht mehr
