### ISSUE TITLE
PEOPLE: Neuanmeldungen ablehnen - Person löschen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#681]
Aktuell wird beim Ablehnen einer Neuanmeldung diese Rolle gelöscht, aber die Person bleibt erhalten.

Neu soll die Person komplett gelöscht werden, falls die Neuanmeldungsrolle die einzige Rolle der Person ist (gelöschte Rollen berücksichtigen).

# Tech-Spec

Anpassung in `People::Neuanmeldungen::Reject`:

- auf jeder `#applicable_roles` prüfen, ob die Person noch weitere Rollen besitzt, inkl. gelöschten Rollen
  - wenn ja: bisheriges Verhalten beibehalten, aber ohne Reset des Passwortes
  - wenn nein: Person löschen

# ToDo

- [x] Domainklasse anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by openscript** [comment]
Hallo @daniel-illi

Eine `Role` hat `deleted_at` und `delete_on`. Im Issue steht:

> noch weitere Rollen besitzt, inkl. gelöschten Rollen 

Heisst dies für mich, dass ich die Person löschen darf, wenn sie keine Rollen im Sinne vom gesetzten Scope (`deleted_at`) hat? Das SQL vom Scope sieht so aus:
```sql
SELECT `roles`.* FROM `roles` WHERE `roles`.`deleted_at` IS NULL AND `roles`.`person_id` = 123
```

**Comment by openscript** [comment]
@daniel-illi Wäre es sinnvoll abgelehnte `Neuanmeldung (Zusatzsektion)` im Log zu vermerken?

**Comment by daniel-illi** [comment]
@openscript oh das war ich mir nicht bewusst 😯
Die `Neuanmeldung (Zusatzsektion)` sollten genau gleich behandelt werden wie die `Neuanmeldung (Stammsektion).

**Comment by openscript** [comment]
> @openscript oh das war ich mir nicht bewusst 😯 Die `Neuanmeldung (Zusatzsektion)` sollten genau gleich behandelt werden wie die `Neuanmeldung (Stammsektion).

Kein Problem. Ich baue es gerne noch ein :)
