### ISSUE TITLE
EVENTS: Datenmodell Vergütungskategorien/ansätze

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#683]
blocks #641, #642

Neu soll ein Model Vergütungskategorie / `CourseCompensationCategory` mit folgenden Spalten erstellt werden:

- Kurzname / 'short_name`, string, not null, unique
- Typ / `kind`, string / enum, not null. Werte Tag / `day`, Pauschale / `flat`, Budget / `budget`
- Beschreibung / `description`, string
- Bezeichnung Kursleitung / `name_leader`, string, translatable, present
- Bezeichnung Klassenleitung / `name_assistant_leader`, string, translatable, present
- created_at
- updated_at

Die `to_s` Methode soll den Kurzname und die Bezeichnung des Typs in Klammern in der aktuellen Sprache ausgeben, damit dies so in Selects usw angezeigt wird.

Neu soll ein Model Vergütungsansatz / `CourseCompensationRate` mit folgenden Spalten erstellt werden:

- Vergütungskategorie / `course_compensation_category_id`, int, not null, indexed
- Gültig ab / `valid_from`, date, not null
- Gültig bis / `valid_to`, date, nullable
- Ansatz Kursleitung / `rate_leader`, decimal, not null, 2 Nachkommastellen, 7 Total
- Ansatz Klassenleitung / `rate_assistant_leader`, decimal, not null, 2 Nachkommastellen, 7 Total
- `created_at`
- `updated_at`

Modelvalidierung: Zum definierten Zeitraum darf kein anderer Eintrag existieren, welcher die gleiche Vergütungskategorie referenziert.

Auf der Vergütungskategorie muss die entsprechende `has_many` Beziehung mit `dependent: :restrict_with_error` definiert werden. 

# ToDo

- [x] Migration erstellen
- [x] Models erstellen

**Comment by openscript** [comment]
Kann dies geschlossen werden @tobiasstern

**Comment by tobiasstern** [comment]
Ja, ich dachte eig. ich hätte es geschlossen.
