### ISSUE TITLE
Grundpaket: Mehrsprachigkeit

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_sac_cas#7]
Gewünschte Sprachen: DE, FR

- [x]  settings.yml
- [x]  transifex -> eigenes Projekt (für Wagon spezifische Übersetzungen)
- [x] Anbindung an transifex
- [x] Kunde berechtigen
- [x] Kunde instruieren

See: #1

**Comment by sykesonrocks** [comment]
@mtnstar "Kunde [...] instruieren" ist noch nicht passiert..

**Comment by mtnstar** [comment]
@ThomasEllenberger kannst du diese Instruktion noch übernehmen?

**Comment by ThomasEllenberger** [comment]
@mtnstar 
@sykesonrocks 
Stefan ist bereits seit Dezember Übersetzer im SAC Wagon für Französisch und Italienisch.
Wenn Bedarf an Übersetzungen im Youth oder Core besteht, bitte melden.
