### ISSUE TITLE
INVOICE: Erzeugen von Rechnungen nach Mitgliedschafts-Mutationen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#719]
Als SAC Backoffice MA nehme ich Mitgliedschafts-Mutationen vor (Eintritt/Austritt Zusatzsektion, Stammsektionswechsel, Familienmutation). 

Vor dem Abschliessen der Mutation gebe ich an, für welche der betroffenen Rechnungsempfänger eine neue Jahresrechnung generiert werden soll und wähle dabei, welcher Rabatt gewährt wird und ob die Eintrittsgebühr verrechnet wird.

Beim Abschliessen der Mutation sollen für alle gewählte Rechnungsempfänger je einen Hintergrundjob `CreateMembershipInvoiceJob` enqueued werden, der asynchron die entsprechende Rechnung erstellt und an Abacus übermittelt.

Mit diesem ticket wird der Hintergrundjob `CreateMembershipInvoiceJob` implementiert.

Argumente:
* `person_id`
* `entry_fee`: boolean
* `discount`: integer

# Mockup

![Screenshot from 2024-07-16 16-48-38](https://github.com/user-attachments/assets/d3e57f46-78fa-4917-a5ad-ecbf9ef5597f)

# ToDo

- [ ] Domainklasse erstellen oder anpassen
- [ ] Specs schreiben

**Comment by codez** [comment]
Braucht der Job für einen Eintritt Zusatzsektion nicht auch noch die Rolle der Zusatzsektion, damit dafür nur die Gebühren der entsprechenden Zusatzsektion verrechnet werden und nicht die gesamte Jahresrechnung?
