### ISSUE TITLE
INVOICES: Ansicht für externe Rechnungen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#734]
blocks #735 

Als SAC Backoffice MA möchte ich die Rechnungen einer Person sehen können.

Neu soll auf der Person in neues Tab "Rechnungen" angezeigt werden. Dieses ist unabhängig des bestehenden Tabs "Rechnungen" aus dem hitobito Core, welches im SAC nicht verwendet wird. Es wird die Ability `index_external_invoices` auf der Person geprüft.

Wenn das Tab angewählt wird, werden alle Rechnungen / `ExternalInvoice` dieser Person aufgelistet. Neueste Rechnungen werden zuoberst angezeigt (nach created_at).

Die Tabelle enthält folgende Spalten:
- Titel / `to_s`
- Status (Als Badge, analog Invoice Status)
- Abacus Nummer / `abacus_sales_order_id`
- Total
- Rechnungsdatum / `issued_at`
- Erstellt / `created_at`
- Aktualisiert / `updated_at`

Der Button "Mitgliedschaftsrechnung erstellen" von der Person Show Seite wird hierhin verschoben.

Das Model und die ExternalInvoiceAbility existieren bereits.

# ToDo

- [x] View/Controller/Sheet erstellen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by openscript** [comment]
Hi @Largo
Der PR ist nicht verlinkt.

**Comment by openscript** [comment]
> Bevor ichs vergesse: ExternalInvoice ist ja neu, können wir dort payed als paid schreiben?

Das fände ich auch toll @codez
