### ISSUE TITLE
INVOICES: Rechnungen stornieren

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#735]
blocked by #734 

Als SAC Backoffice MA möchte ich die Rechnungen einer Person stornieren können.

Neu soll auf der Liste der externen Rechnungen in der letzten Spalte ein Button "Stornieren" (`btn-sm`) sein, mit welchem eine Rechnung storniert werden kann.

Der Button wird nur angezeigt, falls die Rechnung nicht bereits im Status Storniert / `cancelled`  oder Fehler / `error` ist und einen `abacus_sales_order_key` hat.

Wenn der Button geklickt wird, erscheint zuerst ein Confirmation Dialog: "Wollen Sie diese Rechnung wirklich stornieren? Diese Aktion kann nicht rückgängig gemacht werden."

Die Aktion im Controller scheduled einen BackgroundJob `CancelExternalInvoiceJob` mit der entsprechenden Rechnung. Der Status der Rechnung wird (optimistischerweise) bereits auf `cancelled` gesetzt. Eine Flash Message "Die Rechnung #{to_s} (Auftrags-Nr. #{abacus_sales_order_key}) wird storniert" wird angezeigt. Der Redirect erfolgt wieder auf die Liste der externen Rechnungen.

Der Background Job storniert die entsprechende `ExternalInvoice` via Abacus API:

```ruby
sales_order = Invoices::Abacus::SalesOrder.new(external_invoice)
Invoices::Abacus::SalesOrderInterface.new.cancel(sales_order)
```

Bei allfälligen Exceptions soll der Job regulär via Delayed Job Mechanismus retried werden. Es wird allerdings via das `error` Callback von Delayed Job ein der Rechnung zugehöriger `HitobitoLogEntry` erstellt (category: "rechnungen"), wo die entsprechende Fehlermeldung ebenfalls sichtbar ist. Falls alle Versuche fehlschlagen, wird über das `failure` Callback der Status der Rechnung auf `error` gesetzt.

# ToDo

- [x] Controller anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
UI funktioniert soweit korrekt, ich gebe es weiter an den SAC zum ausführlichen Testing.
