### ISSUE TITLE
INVOICES: API für externe Rechnungen

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#736]
Neu soll unter `api/external_invoices` ein API Endpoint für die externen Rechnungen (`ExternalInvoice`) angeboten werden. Diese sollen gelesen und aktualisiert werden können (index, show, update).

Filter sind für person_id, type, issued_at, year, state und abacus_sales_order_key möglich.

Beim Aktualisieren darf einzig der Status, das Total und das Versanddatum verändert werden. 

Die Berechtigungen erfolgen analog zum bestehenden Invoice Enpoint über das invoices Flag des ServiceTokens.

# ToDo

- [x] Domainklasse erstellen oder anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by Largo** [comment]
Bitte TokenAbility reviewen. In Spec schauen warum ServiceToken Fixture ExternalInvoice von Mitglied nicht anzeigen/editieren darf.
