### ISSUE TITLE
PEOPLE: Password Hashes aus altem IDP authentifizieren

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#756]
Damit die Benutzer ihre Passwörter nach der Migration zu Hitobito nicht neu setzen müssen, wollen wir die bestehenden Hashes übernehmen. 

Der Hash wird auf dem heutigen System wiefolgt generiert:

```
#!/bin/bash

preparePassword() {
    local password="$1"
    local saltValue="$2"
    
    local digestInput="$password"
    if [ ! -z "$saltValue" ]; then
        digestInput="$password$saltValue"
    fi

    # Using openssl to compute the SHA-256 hash
    local hash=$(echo -n "$digestInput" | openssl dgst -sha256 -binary | openssl base64)
    echo "$hash"
}

main() {
    local password="$1"
    local saltValue="$2"
    
    if [ -z "$password" ]; then
        echo "Usage: $0 <password> [saltValue]"
        exit 1
    fi
    
    local encodedPassword
    encodedPassword=$(preparePassword "$password" "$saltValue")
    echo "$encodedPassword"
}

main "$@"
```

# Tech-Spec

- 

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by daniel-illi** [comment]
wird mit https://github.com/hitobito/hitobito_sac_cas/issues/772 implementiert
