### ISSUE TITLE
404 Fehler bei Globaler Suche nach Personen

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#759]
Gemäss Bug Report https://saccas.atlassian.net/browse/HIT-486

Bei manchen Treffern via Globalsuche erhalte ich folgende Fehlermeldung:

![Image](https://github.com/user-attachments/assets/f654636a-5ed4-41de-aee1-4d42bee6199f)

Beispiel:

![Image](https://github.com/user-attachments/assets/6bdb9ef0-79e6-4816-a6d5-3d51059f3d9b)

Siehe

https://sac-cas.puzzle.ch/de/groups/1797/people/104251

https://sac-cas.puzzle.ch/de/groups/1797/people/104478

Gemeldet durch: Stefan, 02.06.2024

**Comment by ThomasEllenberger** [comment]
Hat sich meines erachtens tatsächlich mit dem PG-Search behoben.
Ich konnte das Problem auf alle fälle mit den oben genannten Personen nicht mehr nachvollziehen.

@tobiasstern ich schliesse das issue hier.
