### ISSUE TITLE
GROUPS: Fakturarelevante Stammdaten auf Top-Layer

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#76]
https://saccas.atlassian.net/browse/HIT-6?atlOrigin=eyJpIjoiOWM0YzIxYzJkMmQzNDg4ODgwZjViNzljMTAzMTc0NGMiLCJwIjoiaiJ9

**Comment by codez** [comment]
implemented by https://github.com/hitobito/hitobito_sac_cas/issues/471
