### ISSUE TITLE
PEOPLE: Import `7_wso2_people` erstellen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#772]
Aktuell verwendet der SAC WSO2 als Idenity Provider. Künftig wird Hitobito diese Funktion übernehmen. Es geht hier darum, die WSO2 Daten zu importieren.

# Tech-Spec

Blockiert durch https://github.com/hitobito/hitobito_sac_cas/pull/892 wegen Migration.

## 1. Arbeitsvorbereitung

- Quelldaten `WSO21_Personen_2024_08_24_2_prod.csv` von NextCloud herunterladen (**ACHTUNG: Sensitive Daten**)
- **Anonymisiertes** Fixture erstellen (Verschiedene Fälle: Mit und ohne `ContactNo`, mit und ohne Email verifiziert, ...)
- Testdatensatz für die Entwicklung erstellen. Bspw.:
  ```bash
  head -n 1 input.csv > output.csv && tail -n +2 input.csv | shuf -n 2000 >> output.csv
  ```

## 2. CSV Datei lesen

- `app/domain/sac_imports/csv_source.rb` anpassen
- Vorschlag für Mapping:

| **Ruby Hash Attribut** | **WSO21 CSV Export Spaltenname** |
|---|---|
| wso2_legacy_password_hash | UM_USER_PASSWORD |
| wso2_legacy_password_salt | UM_SALT_VALUE |
| navision_id | ContactNo |
| gender | Anredecode |
| first_name | Vorname |
| last_name | FamilienName |
| address_care_of | Addresszusatz |
| address | Strasse |
| postbox | Postfach |
| town | Ort |
| zip_code | PLZ |
| country | Land |
| phone | TelefonMobil |
| phone_business | TelefonG |
| language | Korrespondenzsprache |
| email | Mail |
| birthday | Geburtsdatum |
| email_verified | Email verified |
| role_basiskonto | Basis Konto |
| role_abonnent | Abonnent |
| role_gratisabonnent | NAV_FSA2020FREE |

## 3. Report vorbereiten

- In `app/domain/sac_imports` neue `Wso2PeopleImporter` Klasse erstellen
- Gruppe für neue Personen: Basis Konto/Gruppe=SAC/CAS Login
- Zu jedem Import wird ein Report zu handen des Kunden erstellt.
- Folgende Header hat der Report in diesem Fall:
  ```ruby
  REPORT_HEADERS = [
    :navision_id,
    :first_name,
    :last_name,
    :errors
  ]
  ```

## 4. Import umsetzen

- In `app/domain/sac_imports` neue `Wso2PersonEntry` Klasse erstellen
- Falls `navision_id != nil` prüfen, ob es eine Person mit der ID gibt und sonst Fehler in Report schreiben. Falls es eine Person gibt, die **Person** wie folgt **aktualisieren**:
  - `navision_id` ist der Primärschlüssel der Person in Hitobito 
  - Nur `wso2_legacy_password_hash`, `wso2_legacy_password_salt` und `email_verified` berücksichtigen und importieren
  - Falls `email_verified == "1"` -> `person.confirmed_at = Time.zone.at(0)`
  - Falls die `email` aus dem CSV ungleich der vorhandenen Email in Hitobito ist, soll ein Fehler rapportiert werden.
  - Es muss das `correspondence` Attribut nachgeführt werden: Falls `email_verified` soll `correspondence` auf `digital` gesetzt werden
- Falls `navision_id == nil`, muss eine **neue Person** erstellt werden:
  - Daten aus Quelldaten in Hitobito übernehmen (siehe Mapping)
  - Falls es die `email` schon gibt, soll ein Fehler rapportiert werden.
  - Falls `email_verified == "1"` -> `person.confirmed_at = Time.zone.at(0)`
  - Folgendes Daten-Mapping:
    - `address` zu `street` und `housenumber` aufteilen (mit `Address::Parser` aus `app/domain/address/parser.rb`)
    - `gender` mit `HERR` zu `m` und `FRAU` zu `f` mappen
    - `language` mit `D` zu `de`, `F` zu `fr`, `E` zu `en` und `I` zu `it` mappen
    - Telefonnummern mit `Phonelib.valid` prüfen
- Falls die E-Mail Adresse nicht verifiziert ist, importieren wir das WSO2 Passwort denoch, erstellen aber einen Logeintrag im Report als Info. 
- Folgende **Rollen** sind zu**zuweisen**:
  - **Wichtig**: Wenn der Kontakt bereits eine aktive Stammmitgliedschaftsrolle besitzt, dann darf man der Person nicht zusätzlich die Rolle “Basis Konto”, “Abonnent” oder “Gratisabonnent” vergeben. 
  - Falls `role_basiskonto == "1"`: `Group::AboBasicLogin::BasicLogin`
  - Falls `role_abonnent == "1"`: `Group::AboTourenPortal::Abonnent`
  - Falls `role_gratisabonnent == "1"`: `Group::AboTourenPortal::Gratisabonnent` 

# Fragen

### Anredecode

Bei Anredecode gibt es folgendes in den Sourcedaten:
```
Anredecode,HERR,63424
Anredecode,FRAU,37069
Anredecode,NULL,28978
Anredecode,(NULL),17
Anredecode,FIRMA,5
```

Sollen wir "Firma" auch auf `nil` mappen?
 
 -> Vorerst Error für "Firma".

### Locked accounts

Kann ich das `accountState_DISBALED_LOCKED_UNLOCKED` Feld ignorieren? Das wären ja gesperrte accounts
```
accountState_DISBALED_LOCKED_UNLOCKED,NULL,100638
accountState_DISBALED_LOCKED_UNLOCKED,UNLOCKED,28849
accountState_DISBALED_LOCKED_UNLOCKED,DISABLED,6
```

### `NULL` Land

Wie sollen wir Land `NULL` handhaben?

 -> Auf schweiz mappen

### Rollen

Gilt  "Folgende **Rollen** sind zu**zuweisen**" nur für neue Personen oder auch für existierende?

 -> Für beide

### `email_verified` bei neuen personen

Soll bei einer neuen Person auch `email_verified` beachtet werden?

 -> Ja (ensprechend angepasst)

### Adresse 

Soll die Adresse wie bei `app/domain/sac_imports/person_entry.rb` in `address` und gesplittet gespeichert werden?

 -> Ja

### Mehrfache Durchläufe

Wenn bei einem Import neue Personen erstellt werden, führen die bei einem zweiten Versuch zu einem Fehler, da die Person mit der E-Mail schon existiert.

Wie wollen wir das handhaben?

 -> Wenn keine navision ID da ist, soll in der `Group::AboBasicLogin` nach einer Person mit der E-Mail Adresse gesucht und diese dann entsprechend angepasst werden.

### Gruppen / Rollen

> Gruppe für neue Personen: Basis Konto/Gruppe=SAC/CAS Login

Was ist damit genau gemeint? Gilt das nicht nur wenn  `role_basiskonto == "1"`: `Group::AboBasicLogin::BasicLogin`".

Was wenn `roles_basiskonto` nicht gesetzt ist?

 -> Dieser Fall kann nicht auftreten, da nur alle Rollen Flags `0` sind wenn dafür eine Navision ID da ist.

# ToDo

- [x] Fixture erstellen
- [ ] Importer schreiben
- [ ] Import lokal laufen lassen und erster Report an Kunden übergeben
- [ ] Specs schreiben

**Comment by openscript** [comment]
Ich habe noch folgenden Satz hinzugefügt:

Falls die E-Mail Adresse nicht verifiziert ist, importieren wir das WSO2 Passwort denoch, erstellen aber einen Logeintrag als Info.
