### ISSUE TITLE
ROLES: Berechtigung Hitobito Log

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#778]
Als MA der SAC Geschäftsstelle möchte ich ebenfalls die Meldungen im Hitobito Log sehen.

Neu soll für die Rollen `Group::Geschaeftsstelle::Mitarbeiter` und `Group::Geschaeftsstelle::MitarbeiterLesend` ebenfalls Lesezugriff (`index`, `show`) auf die Entität `HitobitoLogEntry` gewährt werden. Die Ability soll entsprechend angepasst werden.

Es muss sichergestellt werden, dass die Navigation zu Einstellungen > Hitobito Log für diese Personen ebenfalls klappt.

# ToDo

- [x] Ability anpassen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"

**Comment by tobiasstern** [comment]
Zugriff funktioniert.

Getestet mit den beiden Profilen
https://sac-cas.puzzle.ch/de/groups/1237/people/600297
https://sac-cas.puzzle.ch/de/groups/2/people/357008
