### ISSUE TITLE
IMPORT: Import `8_wso2_people_roles` erstellen

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#782]
Blockiert durch #772

Aktuell verwendet der SAC WSO2 als Idenity Provider. Künftig wird Hitobito diese Funktion übernehmen. Es geht hier darum, die Rollen aus den WSO2 Daten zu applizieren.

# Tech-Spec

## 1. Arbeitsvorbereitung

- Quelldaten `WSO21_Personen_2024_08_24_2_prod.csv` von NextCloud herunterladen (**ACHTUNG: Sensitive Daten**)
- Fixture ggf. anpassen (Verschiedene Rollenfälle)
- Testdatensatz für die Entwicklung erstellen. Bspw.:
  ```bash
  head -n 1 input.csv > output.csv && tail -n +2 input.csv | shuf -n 2000 >> output.csv
  ```

## 2. Report vorbereiten

- In `app/domain/sac_imports` neue `WSO2PeopleRoleImporter` Klasse erstellen
- Zu jedem Import wird ein Report zu handen des Kunden erstellt.
- Folgende Header hat der Report in diesem Fall:
  ```ruby
  REPORT_HEADERS = [
    :navision_id,
    :first_name,
    :last_name,
    :errors
  ]
  ```

## 3. Personen zu Rollen hinzufügen (Datenimport)

- WSO21 mit `SacImports::CsvSource` laden und:
  - Personen

# ToDo

- [ ] Fixture ggf. anpassen
- [ ] Importer schreiben
- [ ] Import lokal laufen lassen und erster Report an Kunden übergeben
- [ ] Specs schreiben

**Comment by openscript** [comment]
Es ist schwierig und aufwendig die WSO2 Personenrollen separat mit den Personen zu assoziieren.
 - Da Hitobito teilweise IDs vergeben muss, ist bei einem zweiten Durchlauf schwierig die Rollen den Personen zuzuordnen.
