### ISSUE TITLE
GROUPS: Import-Script für Sektionen Stammdaten aus Typo3

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#788]
Mit #73 und #84 wurde das Import-Script zum Importieren der Sektionen mit dem Navision Import implementiert.

Nun sollen noch weitere Stammdaten für die Sektionen aus dem Typo3 importiert werden:
* Textelemente für Sektion Steckbrief (siehe z.B. SAC Aarau) - bspw. 
  - Kurzbeschrieb
  - Beschreibung
  - Angebote

Dazu soll ein weiteres Import-Script implementiert werden.

# Tech-Spec

# ToDo

- [ ] Migration erstellen
- [ ] Domainklasse erstellen oder anpassen
- [ ] Model/View/Controller anpassen
- [ ] Neues Feature mit FeatureGate deaktivierbar machen
- [ ] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by openscript** [comment]
@ThomasEllenberger Leider fehlen uns dazu noch ein Teil der Angaben, um den Aufwand genau abzuschätzen. Ich habe diese angefordert.

**Comment by openscript** [comment]
@ThomasEllenberger Dies können wir nicht machen, bis wir Feedback vom SAC erhalten.

**Comment by openscript** [comment]
Laut SAC wird dies nicht im MVP gemacht. Siehe Jira
