### ISSUE TITLE
PEOPLE: Stammsektionwechsel nur per sofort erlauben

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#810]
Aktuell ist ein Stammsektionwechsel (`Wizards::Memberships::SwitchStammsektion`)  per sofort oder per 1. Januar im  Folgejahr möglich. 

Neu soll der Wechsel nur noch per sofort möglich sein. Somit kann der Wizard Schritt "Datumwahl" entfernt werden und beim Rollen erstellen (`Memberships::SwitchStammsektion`) müssen keine FutureRoles mehr berücksichtig werden. 

# TODO

- [x] Domain Klassen entsprechend Anpassen
- [x] Tests entsprechend Anpassen

**Comment by tobiasstern** [comment]
@amaierhofer Habs kurz getestet, der Schritt 2 ist korrekt entfernt. Zwei Anmerkungen:

- Die Reihenfolge der Sektionen im Dropdown ist nicht ideal. Es scheint keiner Logik zu folgen, eine bestimmte Sektion ist schwierig zu finden. Am besten wäre alphabetisch. Vgl. screenshot:
![Image](https://github.com/user-attachments/assets/2c6d0d30-146d-4f8c-9617-bbde665af291)

- Wenn ich einen Wechsel vornehmen und danach gleich noch ein Wechsel, wird mir diese Fehlermeldung angezeigt, siehe Screenshot. Ist das working as designed oder ein Fehler?
![Image](https://github.com/user-attachments/assets/e078b208-4887-4c0a-9b8e-da5d9250171c)

**Comment by tobiasstern** [comment]
@hunchr Könnt ihr hier bitte noch die Reihenfolge im Dropdown verbessern, siehe mein vorheriger Kommentar? Z.B. alphabetisch.

**Comment by tobiasstern** [comment]
Prima, danke
