### ISSUE TITLE
Onboarding Familienmitgliedschaft: E-Mail von Familienmitgliedern wird nicht geprüft

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#832]
In https://github.com/hitobito/hitobito_sac_cas/issues/758 wurde die Prüfung der E-Mail-Adressen von Familienmitgliedern angepasst. Dazu soll hier ein Bug behoben werden:

Man kann bei den Familienmitgliedern Personen hinzufügen und ihnen im optionalen Feld eine E-Mail-Adresse geben, die bereits im System von einem anderen Konto verwendet wird! Beim Abschicken des Formulars gibt es kein Feedback für den User, in der Konsole erscheint aber eine Fehlermeldung _"Failed to load resource: the server responded with a status of 422 (Unprocessable Content)"_

Dies muss behoben werden. Man darf keine Personen erfassen können mit einer E-Mail, die bereits im System verwendet wird.

Testen unter https://sac-cas.puzzle.ch/de/groups/942/self_registration

**Comment by hunchr** [comment]
@tobiasstern ich wollte den bug reproduzieren, aber anscheinend geht es jetzt. kannst du das bitte nochmals testen?

**Comment by tobiasstern** [comment]
Ja, der Fehler ist nicht mehr reproduzierbar, vgl. screenshot:

![Image](https://github.com/user-attachments/assets/fa76f1b0-a9d3-4294-92df-062db1924c49)
