### ISSUE TITLE
PEOPLE: Exakte Berechnung für Mitgliedschaftsjahre

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#835]
Momentan werden für die Berechnung der Mitgliedschaftsjahre die Anzahl Tage aller Hauptmitgliedschafts-Rollen gezählt und durch 365 geteilt. Damit werden die Schaltjahre nicht berücksichtigt, wodurch der "Jubiläumstag" im Jahr immer weiter nach vorne wandert. Ist eine Person z.b. am 1.1.2000 eingetreten, so ist die Anzahl Mitgliedschaftsjahre bereits am 25.12.2019 *20*. Dies verursacht bei der Berechnung von Reduktionen für langjährige Mitglieder Probleme.

Neu sollen die Mitgliedschaftsjahre korrekt gezählt werden. Das heisst z.B.:
- Bei einem Eintritt am 1.1.2000 ist die (abgerundete) Anzahl Jahre am 31.12.2019 *19*, am 1.1.2020 *20*
- Bei einem Eintritt am 1.1.2000 und einem Austritt am 31.12.2009  ist die (abgerundete) Anzahl Jahre am 1.1.2010  *10* (wie bisher)
- Bei einer Rolle vom 1.1.2000 bis am 31.3.2009, einer zweiten Rolle vom 1.4.2009 bis am 31.12.2009 und einer dritten Rolle vom 1.1.2010  ist die (abgerundete) Anzahl Jahre am 31.12.2019 *19*, am 1.1.2020 *20*

Die Queries sollen auch mit Postgres funktionieren oder eine mit Postgres funktionierende Alternative haben.

# ToDo

- [x] Model anpassen
- [x] Specs schreiben

**Comment by amaierhofer** [comment]
@njaeggi gibts hier noch einen branch dazu?
