### ISSUE TITLE
PEOPLE: Initiale Übermittlung der Mitglieder an Abacus

### ISSUE THREAD

**Issue by codez** [hitobito/hitobito_sac_cas#843]
Als Datenimporteur möchte ich die Personendaten erst an Abacus übermitteln, wenn alle Daten vollständig importiert sind, damit diese von Abacus Batch Requests profitieren können.

### Background Job

Es wird ein Background Job `Invoices::Abacus::TransmitAllMembersJob` erstellt, welcher über alle SAC Mitglieder (Rolle `Group::SektionsMitglieder::Mitglied` und `Group::SektionsNeuanmeldungenNv::Neuanmeldung`) ohne Datenqualitäts-Issues mit level=Error iteriert und diese in Batches an Abacus übermittelt.  Der Job wird dann nach allen initialen Importen manuell (z.B. via Konsole) angestossen (zwingend nach dem Job zur Überprüfung der Datenqualität #800).

Die Aufteilung in Batches und die parallele Verarbeitung erfolgt analog zu #803. Von den entsprechenden Personen (sortiert nach ID) können erstmals nur die IDs in Batches von 1000 geladen werden. Diese Batches werden dann in Slices zu 50 IDs aufgeteilt und in 4 parallelen Threads (nicht Prozessen) abgearbeitet. Beim Laden der Personenmodels werden idealerweise nur die für Abacus relevanten Attribute (siehe auch #841, plus id und abacus_subject_key) geladen.

```ruby
subject_interface = Invoices::Abacus::SubjectInterface.new
slices = ids.each_slice(50).to_a
Parallel.map(slices, in_threads: PARALLEL_THREADS) do |slice|
    ActiveRecord::Base.connection_pool.with_connection do
      people = Person.where(id: slice).select(RELEVANT_ATTRIBUTES)
      subject = people.map { |person| Invoices::Abacus::Subject.new(person) }
      subject_interface.transmit_batch(subjects)
   end
end
```

Die `max_run_time` für diesen Job wird auf 12 Stunden gestellt.

### Übermittlung (Bereits in Invoices::Abacus::SubjectInterface#transmit_batch implementiert)

Da dieser Job mehrmals gegen denselben Abacus Mandant ausgeführt werden kann, ist es möglich, dass die Hitobito Models noch keinen `abacus_subject_key` gesetzt haben (z.B. weil die DB zurückgesetzt und nochmals neu importiert wurde), die Person aber trotzdem bereits in Abacus vorhanden ist. Standardmässig wird die hitobito Person ID auch als Subject ID in Abacus verwendet. 

Daher werden für `transmit_batch` erst alle Subjects des Batches aufgrund  `abacus_subject_key || id` abgefragt. Dies soll ebenfalls als Batch Request erfolgen. 

Für die Subjects, welche bereits existieren, wir allenfalls der `abacus_subject_key` gesetzt, danach werden sie als Batch aktualisiert (`client.batch { existing_subjects_and_their_remotes.each { |subject, remote| update(subject, remote) } }` sollte funktionieren). Allenfalls muss geprüft werden, ob im BatchRequest überhaupt etwas drin ist. Falls er leer ist (=alles ist bereits up to date), muss er natürlich nicht abgeschickt werden.

Die Subjects, welche noch nicht existieren (404 im Part), werden via `create_batch_subjects` auf Abacus erstellt, die `abacus_subject_key`s gesetzt und dann auch die `create_batch_subject_associations` erstellt. Hier muss auf geeignete Weise noch ein Error Handling (siehe unten) für die einzelnen Parts der Batch Request eingebaut werden.

### Fehlerbehandlung

Grundsätzlich soll dieser Job so aufgebaut sein, dass jederzeit, insbesondere natürlich bei den API Requests, Fehler auftreten können oder der Job Server terminiert wird. Danach wird der Job über Delayed Jobs retried. Bei einem Retry können bereits abgearbeitete Personen erneut verarbeitet werden. Diese Grundsätze sind in jedem Moment zu prüfen.

Im folgenden die offensichtlichen Fehlerquellen:

Falls in der BatchResponse einzelne Parts nicht den Status `success?` haben, wird für diese je ein Hitobito Log Entry erstellt:
* subject: Die entsprechende Person ( `part.context_object.entity`) 
* category: rechnungen
* level: error
* message: Die Personendaten konnten nicht an Abacus übermittelt werden
* payload: part.error_payload`
Es erfolgt für diese Person keine weitere Aktion (wie ein Retry), der Job läuft weiter.

Bei allfälligen Exceptions (insbesondere komplett failende Batch Requests bei gröberen Abacus/Netzwerk Problemen) soll der Job regulär via Delayed Job Mechanismus retried werden. Diese Exceptions können auch innerhalb der parallelen Threads auftreten und müssen entsprechend korrekt abgefangen werden, die parallele Verarbeitung gestoppt werden und die ursprüngliche Exception propagiert werden. 

Via das error Callback von Delayed Job wird im Exception Fall ein HitobitoLogEntry erstellt (category: "Stapelverarbeitung", kein Subject, Level Error, Message "Übermittlung Personendaten: Personendaten konnten nicht an Abacus übermittelt werden. Es erfolgt ein weiterer Versuch.", Payload exception.message). Falls alle Versuche fehlschlagen, wird über das failure Callback ein letzter HitobitoLogEntry mit der Message "Übermittlung Personendaten abgebrochen" erstellt.

### Gracefull Termination

Abhängig von hitobito/hitobito#2772

Die Methode `check_terminated` wird dann in jeder Iteration aufgerufen (z.B. bevor eine neue Slice mit Personen zusammengestellt und abgefragt wird, sowie bevor dann die Änderungen übermittelt werden). So kann der aktuelle Schritt noch beendet werden. 

# ToDo

- [x] Jobklasse erstellen
- [x] Specs schreiben
- [x] Mit angemessener Rolle "durchklicken"
- [x] Zum Review an @codez zuweisen

**Comment by Largo** [comment]
Bitte um kurzes Feedback. Ich habe getestet und konnte sehen das Daten zu Abacus uebertragen wurden.

Noch offen / unklar:
- Check Terminated  (abhaengig vom Issue hitobito/hitobito#2772
- Evtl. Exceptionhandling bei Fehlern noch nicht ausreichend?
-  Relevant Attributes

**Comment by rnestler** [comment]
@codez Was ist da noch offen?
