### ISSUE TITLE
ROLES: Bei Stammsektionswechsel alte Rolle löschen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_sac_cas#858]
Bei einem Stammsektionswechsel wird die aktuelle Stammsektionsrolle der Person per gestern beendet (deleted_at resp. end_on auf gestern gesetzt)
und eine neue Stammsektionsrolle per heute erstellt.

Falls die aktuelle Stammsektionsrolle gestern noch gar nicht aktiv war da sie erst heute erstellt wurde (z.B. durch einen vorgängigen Stammsektionswechsel am selben Tag), dann würde sie nach dem Stammsektionswechsel ablaufen bevor sie startet (end_on > start_on) was nicht gültig ist.

Neu soll die aktuelle Stammsektionsrolle gelöscht werden falls ihre Gültigkeit erst heute beginnt.
Im Log auf der Person soll die Löschung der Rolle ersichtlich sein.

# ToDo

- [x] Domainklasse `Memberships::SwitchStammsektion` anpassen
- [x] Specs schreiben

**Comment by amaierhofer** [comment]
blockiert durch hitobito/hitobito#2775
