### ISSUE TITLE
Onboarding Familienmitgliedschaft: Keine Kinder bei Newsletter-Abo

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_sac_cas#865]
Wenn bei der Selbstregistrierung ein Familie erfasst werden soll und man im letzten Schritt die Checkbox “Ich möchte einen Newsletter abonnieren“ anwählt, dann kann man zwar die Erfassung abschliessen, jedoch wird nur die Hauptperson erstellt, alle weiteren Personen fehlen dann bzw gehen verloren.

Getestet per SelfReg Form wie z.b. https://sac-cas.puzzle.ch/de/groups/917/self_registration

Eingegebene Daten:
1. Hauptperson mit allen Pflichtfeldern
2. Ein Kind (Jhg 2016), ohne E-Mail-Adresse
3. Ein zweites Kind (Jhg2017), ohne E-Mail-Adresse

Bei meinen Tests scheint es keine Rolle zu spielen, ob die zusätzlichen Personen (Kind 1 und 2 hier) eine E-Mail-Adresse haben oder nicht.

**Comment by tobiasstern** [comment]
@hunchr Wenn ich das teste, erhalte ich beim abschicken des Formulars einen Fehler 500. Hat das bei dir geklappt?

**Comment by hunchr** [comment]
> @hunchr Wenn ich das teste, erhalte ich beim abschicken des Formulars einen Fehler 500. Hat das bei dir geklappt?

komisch, bei mir funktioniert es sehr gut

**Comment by tobiasstern** [comment]
Hast du auch auf Staging/Integration getestet?

**Comment by hunchr** [comment]
habe es jetzt dort getestet, bekomme leider auch einen 500

**Comment by ThomasEllenberger** [comment]
@hunchr Habe das zurück in Progress gezogen. Bitte nochmals anschauen.

**Comment by njaeggi** [comment]
@tobiasstern Ich habe es auf der Int bei drei verschiedenen Self registrations nachgespielt und keinen 500er mehr bekommen...

- https://sac-cas.puzzle.ch/de/groups/917/self_registration
- https://sac-cas.puzzle.ch/de/groups/907/self_registration
- https://sac-cas.puzzle.ch/de/groups/1133/self_registration

Eventuell kam der Bug beim Entwickeln von anderen Tickets auf die Int, kann nochmal überprüft werden ob der 500er immernoch auftritt?

**Comment by tobiasstern** [comment]
Tatsache, es klappt! Danke 🙏
