### ISSUE TITLE
PEOPLE: Personen-Import und Familien

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sac_cas#90]
blocked_by: #98

Der Personen-Import soll so angepasst werden das Familien importiert werden.

- Im XLSX Export File gibt es die Spalte Familien-Nr. sowie Kategorie FAMILIE

# Tech-Spec

# ToDo

**Comment by carlobeltrame** [comment]
Wird direkt in #98 umgesetzt
