### ISSUE TITLE
MEMBERSHIP: Austritt  "Aufbewahrung deiner Daten" und "SAC Spenden" werden nicht berücksichtigt

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#901]
sicherstellen, dass anforderungen aus https://github.com/hitobito/hitobito_sac_cas/issues/626 korrekt implementiert und getestet sind. 

Zudem soll beim Austritt die Checkbox " Aufbewahrung deiner Daten" automatisch gechecked werden sobald, entweder "Newsletter" oder "Spenden" angewählt wird.

Am besten über einen generischen  `form_field_check_depdent_stimulus` controller im core lösen und mit einer Feature spec verifizieren
![image](https://github.com/user-attachments/assets/6534affa-97fd-4e2f-a2be-ab7e33f08479)

**Comment by hunchr** [comment]
`subscribe_fundraising_list` funktioniert und die person wird beim austritt auf die liste aufgenommen. datenaufbewahrung habe ich nicht getestet.

**Comment by rnestler** [comment]
> subscribe_fundraising_list funktioniert und die person wird beim austritt auf die liste aufgenommen. 

Ist das auch in einer spec irgendwo abgedeckt?

**Comment by hunchr** [comment]
> Ist das auch in einer spec irgendwo abgedeckt?

wahrscheinlich hier https://github.com/hitobito/hitobito_sac_cas/blob/master/spec/models/memberships/terminate_sac_membership_spec.rb#L199

**Comment by njaeggi** [comment]
Anforderungen aus #626 sollten alle funktionieren und mit Tests abgedeckt sein:
SAC Spenden: https://github.com/hitobito/hitobito_sac_cas/blob/7c48828bd7c358694eaebb7ed942d3bd9826002d/spec/models/memberships/terminate_sac_membership_spec.rb#L174
Aufbewahrung deiner Daten: https://github.com/hitobito/hitobito_sac_cas/blob/7c48828bd7c358694eaebb7ed942d3bd9826002d/spec/models/memberships/terminate_sac_membership_spec.rb#L141

**Comment by njaeggi** [comment]
Wenn eine der beiden unteren Checkboxen ausgewählt wird, wird die obere "Daten aufbewahren" Checkbox automatisch ausgewählt, sobald diese wieder vom Benutzer unchecked wird, sollen alle dependent Checkboxen automatisch auch unchecked werden.
