### ISSUE TITLE
SIGNUP: Eintritt nur mehr per sofort erlauben

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#935]
Neu soll der Eintritt nur noch per sofort erlaubt werden

- VariousFields#register_on entfernen
- `shared/register_on` partial entfernen
- Text "Eintrittsdatum per sofort" oberhalb vom Eintrittsgrund ergänzen

Zudem soll unterhalb von "Eintrittsdatum per sofort" eine graue box (`alert-secondary`) angezeigt werden, die 
Information zur Korrespondenz ins Ausland enthält sowie informationen zum etwaigen Rabatt

Zeitraum des Antrags: von 01.01 – 30.06

> Bis 30. Juni ist der volle Beitrag des laufenden Jahres geschuldet.
> Es können noch weitere Gebühren anfallen, falls die Korrespondenzadresse im Ausland registriert ist.

Zeitraum des Antrags: von 01.07 – 30.09

> Bei Eintritt zwischen dem 01. Juli und dem 30. September erhältst du 50% Rabatt auf den jährlichen Beitrag des laufenden Jahres.
> Es können noch weitere Gebühren anfallen, falls die Korrespondenzadresse im Ausland registriert ist.

Zeitraum des Antrags: von 01-10 - 31.12

> Bei Eintritt ab dem 01. Oktober entfällt der jährliche Beitrag des laufenden Jahres.
> Es können noch weitere Gebühren anfallen, falls die Korrespondenzadresse im Ausland registriert ist.

**Comment by ThomasEllenberger** [comment]
Reopened:

Texte werden noch nicht korrekt dargestellt:
![grafik](https://github.com/user-attachments/assets/a01019d1-3be8-4a35-8155-dc21e52db4c3)

**Comment by njaeggi** [comment]
Ich vermute das auf der Integration keine SacMembershipConfig existiert...

Lokal werden die Datumsinformationen korrekt dargestellt, wenn jedoch jede SacMembershipConfig gelöscht wird, hab ich lokal das gleiche Problem.

Ob wir das ganze mit einer Validation lösen das immer ein SacMembershipConfig existieren muss oder einen zusätzlichen Text hinzufügen falls dies nicht der Fall ist, werde ich noch abklären

**Comment by njaeggi** [comment]
Der Bug war das SacMembership.last nicht das aktuelle war, damit der Bug lokal nachgestellt werden kann, muss eine weitere Config erstellt werden, welche valid_from vor der Config der Seeds (2024) hat.

Ich habe zum testen 2000 verwendet, genau wie es auch auf der Integration war.
