### ISSUE TITLE
MAILS: SAC Eintritt Bestätigungs Emails mit und ohne Freigabeprozess

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#941]
Nachdem ein Antragssteller die Selbstregistrierung auf einer Sektion via `Wizards::Signup::SektionWizard` abgeschlossen hat, soll ein Bestätigungsemail ausgelöst werden.
- neuer `Signup::SektionMailer` mit `confirmation` und `approval_pending_confirmation` methoden
- emails gehen direkt an den Antragssteller (aktuelle locale verwenden)
- bcc: mv@sac-cas.ch und hauptemail von sektion falls gesetzt
- Mailer von der `SektionOperation` aufrufen, nur für hauptperson (analog `generate_invoice`, `can_receive_invoice?` nach `main_person?` umbennenen)

**CustomContent - Signup::SektionMailer::CONFIRMATION**
- label: "SAC Eintritt: Bestellbestätigung ohne Freigabe"
- subject: "SAC Eintritt Bestellbestätigung"
- required_placeholders: siehe template
- links to FAQs sollen in die locales gepackt und von dort gelesen werden
- invoice-details soll eine HTML tabelle sein, siehe abschnitt unten

```
Hallo {first-name}

Wir freuen uns sehr, dass du dich für eine SAC-Mitgliedschaft entscheiden hast und nun Teil des grössten Bergsportverbands der Schweiz bist. 

Folgende Angaben haben wir von dir erhalten. Sollten diese nicht korrekt sein, kannst du sie im 
<a href="#{person_path(@person)}">SAC-Portal</a> selbstständig anpassen.

<h2>Sektion und Mitgliedschaft</h2>

Sektion: %{group-name}
Mitgliedschaftskategorie: %{membership-category}
Eintritt per: sofort

%{invoice-details}

<h2>Personendaten</h2>

Kontaktperson
Vorname: %{first-name}
Name: %{last-name}
Geburtsdatum: %{birthday}
E-Mail: %{email}
Telefonnumer: %{phone-number}
Adresszusatz: %{address-care-of}
Strasse und Nr: %{street-with-number}
Postfach: %{postbox}
PLZ: %{zip_code}

Du wirst in kürze eine weitere E-Mail mit der Rechnung erhalten. Sobald die Zahlung bei uns eingegangen ist, wird deine Mitgliedschaft vollständig aktiviert und alle Dienste können genutzt werden.

Den digitalen Mitgliederausweis findest du in deinem <a href="#{person_path(@person)}">SAC-Portal</a> Profil. Weitere Details zum digitalen Mitgliederausweis findest um im <a href="%{faq-link}">FAQ</a>.

Viel Spass beim SAC!
```

**CustomContent - Signup::SektionMailer::APPROVAL_PENDING_CONFIRMATION**
- label: "SAC Eintritt: Bestellbestätigung mit Freigabe"
- subject: "SAC Eintritt Bestellbestätigung"
- required_placeholders: siehe template
- links to FAQs sollen in die locales gepackt und von dort gelesen werden
- invoice-details soll eine HTML tabelle sein, siehe abschnitt unten

```
Hallo {first-name}

Wir freuen uns sehr, dass du dich für eine SAC-Mitgliedschaft interessierst und eine Mitgliedschaft beantragt hast.

Dein Antrag wurde an die Sektion %{group-name} weitergeleitet. Über die Aufnahme eure Mitglieder entscheidet die Sektion.


Folgende Angaben haben wir von dir erhalten. Sollten diese nicht korrekt sein, kannst du sie im 
<a href="#{person_path(@person)}">SAC-Portal</a> selbstständig anpassen.

<h2>Sektion und Mitgliedschaft</h2>

Sektion: %{group-name}
Mitgliedschaftskategorie: %{membership-category}
Eintritt per: sofort

%{invoice-details}

<h2>Personendaten</h2>

Kontaktperson
Vorname: %{first-name}
Name: %{last-name}
Geburtsdatum: %{birthday}
E-Mail: %{email}
Telefonnumer: %{phone-number}
Adresszusatz: %{address-care-of}
Strasse und Nr: %{street-with-number}
Postfach: %{postbox}
PLZ: %{zip_code}

Du wirst in kürze eine weitere E-Mail mit der Rechnung erhalten. Sobald die Zahlung bei uns eingegangen ist, wird deine Mitgliedschaft vollständig aktiviert und alle Dienste können genutzt werden.

Den digitalen Mitgliederausweis findest du in deinem <a href="#{person_path(@person)}">SAC-Portal</a> Profil. Weitere Details zum digitalen Mitgliederausweis findest um im <a href="%{faq-link}">FAQ</a>.

Vielen Dank
```

**Rechnungsdetails `invoice-details`**

Soll als html tabelle in das Email integriert werden, localisiert sein zweispaltig sein. Die Preisberechnung soll dabei mit der in   #933 implemtentierten Komponente gemacht werden.

**FAQ**

unter  key `global.links.faq`
- DE: https://www.sac-cas.ch/de/meta/faq/mitgliedschaft/ 
- FR: https://www.sac-cas.ch/fr/meta/faq/membres/ 
- IT: https://www.sac-cas.ch/en/meta/faq/faq-membership/ 
- ENG: https://www.sac-cas.ch/en/meta/faq/faq-membership/ 

Footer wird mit https://saccas.atlassian.net/browse/HIT-505 umgesetzt

**Comment by hunchr** [comment]
@amaierhofer welchen wert sollte die `Mitgliedschaftskategorie: {membership-category}` haben?

**Comment by amaierhofer** [comment]
@hunchr 
1. soll die werte Jugend, Einzel, Familie haben siehe `I18n.t('roles.beitragskategorie')`
2. siehe `Wizards::Signup::SektionOperation#no_approval_needed?`
