### ISSUE TITLE
Roles: Editieren/löschen von Wizard Rollen anpassen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#963]
Die unten stehenden Rollen werden via Wizards bearbeitet und dürfen sonst noch eingeschränkt verwaltet werden.

- Group::SektionsMitglieder::Mitglied (Stammsektion)
- Group::SektionsMitglieder::MitgliedZusatzsektion
- Group::SektionsNeuanmeldungenNv::Neuanmeldung (Stammsektion)
- Group::SektionsNeuanmeldungenNv::NeuanmeldungZusatzsektion

Hinzufügen und Löschen dieser Rollen soll unterbunden werden, beim Bearbeiten ist nur noch ein Anpassen des "Bis Datums" möglich. Es existieren mehrere Absprungspunkte zum Bearbeiten der Rollen, die alle geprüft werden müssen

- Hinzufügen von Personen auf Gruppen
- Editieren/Löschen von Rollen von der Personen Liste der Gruppe (Direkt und Multiselekt)
- Editieren/Löschen von Rollen auf der Personen Seite

**Technische Umsetzung**

Die Rollen am besten in einer Konstante `SacCas::WIZARD_MANAGED_ROLES` zusammenfassen. Dann `GroupDecorator#possible_roles` so anpassen, dass diese Rolen nicht mehr zurückgeliefert werden. Zudem müssen noch die relevanten partials(`roles/_fields.html.haml`, `roles/_modal.html.haml`) in den wagon kopiert und wie folgendermassen angepasst werden

1. Für normale Rolle partial aus dem core rendern (absoluten Pfad via `Rails.root.join` verwenden)
2. Für `WIZARD_MANAGED_ROLES` nur das "bis Datum" rendern

Das Löschen der Rollen kann via abilities unterbunden werden

**Comment by hunchr** [comment]
anmerkungen:
- `roles/_modal.html.haml` musste nicht angepasst werden (wird schon von `roles/_fields.html.haml` gedeckt?)
- `render` mit absoluten pfad geht nicht; relativer wurde verwendet
