### ISSUE TITLE
SIGNUP: VariousStep Eintrittsgründe sollen mehr Platz haben

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#986]
Momentan kommt es zu unschönen Linebreaks bei den Eintrittsgründen.
![image](https://github.com/user-attachments/assets/f023114d-b30d-4bf4-ac65-475b1e5a76f0)

 Ursache ist die `labeled` Methode vom `StandardFormBuilder`, welche die `mw-63ch` Klasse setzt. 

Ich habe den Eindruck diese CSS Klasse könnte im Core entfernt werden. Vielleicht kann @njaeggi das noch besser beurteilen. Falls es die Klasse tatsächlich braucht, müssten wir noch schauen wie wir das am besten für diesen Screen anpassen.

**Comment by njaeggi** [comment]
`mw-63ch` entfernen bringt hier leider nichts, wenn das Label noch länger wäre, würde der Umbruch immernoch gemacht werden (weil das div Element auch ohne `mw-63ch` eine bestimmte Width hat), ich habe mal eine PR mit einem Fix erstellt, welcher keine anderen Wagons betreffen sollte und irgendwelche Styling Options kaputt macht.
