### ISSUE TITLE
SIGNUP: InfosComponent um weitere Card "Mitglied werden" erweitern

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_sac_cas#987]
Unter Kontakt soll eine zusätzliche `card` Mitglied werden gemäss Screenshot angezeigt werden.

![image](https://github.com/user-attachments/assets/64e3baf3-95f5-4186-bb6b-43b64f76b166)

Die Links werden analog den FAQ Links in den locales versorgt (französische und italienische links gibts es aktuelle nicht), prüfen dass das default feedback auf de funktioniert.

- de https://www.sac-cas.ch/de/mitgliedschaft/mitglied-werden/
- en https://www.sac-cas.ch/en/mitgliedschaft/mitglied-werden/

**Comment by hunchr** [comment]
@amaierhofer den englischen links gibts auch nicht

**Comment by ThomasEllenberger** [comment]
Reopened:

Die Links  zu den FAQ's haben sich noch einmal geändert.
Bitte noch entsprechend anpassen

DE https://www.sac-cas.ch/de/meta/faq/mitgliedschaft/

FR https://www.sac-cas.ch/fr/meta/faq/membres/

IT https://www.sac-cas.ch/it/meta/faq/faq-mitgliedschaft/

ENG https://www.sac-cas.ch/en/meta/faq/faq-membership/
